### ISSUE TITLE
KIFTester loaded on non KIFTestCase

### ISSUE THREAD

**Issue by ohadnav** [kif-framework/KIF#1001]
The title pretty much says it all. On some test cases I wouldn't like KIF to load my app (say, when I test my view models), but it loads it anyhow, and so testing take longer.

Is there a way to quiet KIF for these test cases?

**Comment by justinseanmartin** [comment]
If I understand your situation correctly, KIF isn't responsible for loading your app, that happens from having an app host set for your test target. If you want to avoid having a test host for some tests, make a separate test target and unset the app host in the General tab.
