### ISSUE TITLE
How to run a single test bundle/test method from terminal.

### ISSUE THREAD

**Issue by gkrinord** [kif-framework/KIF#1002]
I want to run a single test from my test file.How can I do that?
Tried the following but it didn't work.
`xcodebuild test -workspace abc.xcworkspace -sdk=iphonesimulator -scheme myscheme -destination 'platform=iOS Simulator,name=iPhone 6' -only-testing:mytarget/SignInTest/funnc_1234`

**Comment by justinseanmartin** [comment]
That is a general xcodebuild question, better suited for StackOverflow. Should work fine for KIF though. 

We use `-skip-testing` instead of `-only-testing` to ensure consistent alphabetical test ordering (thanks Apple 👎 ). Hopefully that gets fixed in the future.

**Comment by gkrinord** [comment]
Thanks for the quick reply. Could you please help me on how to run a specific function or specific test file in KIF via command line.
