### ISSUE TITLE
How to tap specific child element with KIF?

### ISSUE THREAD

**Issue by Nmbr-13** [kif-framework/KIF#1005]
I use KIF 3.6.0 in Xcode 8.3.3 for UI-testing of the application on my job. One of the application's screens outputs the information in cells with text-fields and buttons which have the same accessibility labels in each cell, moreover some of them have dinamically changeable values: 

<a href="http://tinypic.com?ref=2vxeopj" target="_blank"><img src="http://i63.tinypic.com/2vxeopj.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

So if I use

`[tester tapViewWithAccesibilityLabel:@"<buttonName>"];`

the button in the first cell will be tapped. I know how to specify the the button in definite cell, like

`[[[XCUIApplication alloc] init].tables.cells[@"<cellName>"].buttons[@"<buttonName>"] tap];`

So how can I specify the same way using KIF to get access for such elements? 
Or maybe, there is some special method for that?

**Comment by justinseanmartin** [comment]
There are a couple of different approaches that you could use, but none of them are quite as streamlined as the UIApplication format when the syntax was designed for finding elements within elements within elements.

Option 1 - You could change the app code to emit a unique accessibilityValue or accessibilityHint 
or combination of the two. These are user facing via screen reader, but overall may improve accessibility of your application. If you don't want them to be user facing, you  accessibilityIdentifier instead.

Option 2 - Use KIFUIViewTestActor's `usingPredicate:` matcher. This allows you to specify any conditions you'd like to find the element. For example, we have a category on UIView like this:

```
@implementation UIView (RKTMatchingExtensions)

+ (UIView *)RKT_viewMatching:(BOOL (^)(UIView *))block;
{
    __block UIView *match = nil;

    [UIApplication.sharedApplication.windowsWithKeyWindow enumerateObjectsUsingBlock:^(UIWindow *window, NSUInteger idx, BOOL *stop) {
        match = [window RKT_descendantMatching:block];

        if (match != nil) {
            *stop = YES;
        }
    }];

    return match;
}

- (UIView *)RKT_descendantMatching:(BOOL (^)(UIView *))block;
{
    NSParameterAssert(block);

    if (block(self)) {
        return self;
    }

    for (UIView *subview in self.subviews) {
        UIView *matchingView = nil;
        if ((matchingView = [subview RKT_descendantMatching:block]) != nil) {
            return matchingView;
        }
    }

    return nil;
}

- (UIView *)RKT_ancestorMatching:(BOOL (^)(UIView *))block;
{
    NSParameterAssert(block);

    UIView *view = self.superview;
    while (view) {
        if (block(view)) {
            return view;
        }

        view = [view superview];
    }

    return nil;
}

@end
```

An example of using this is:

```
    [[viewTester usingPredicate:[NSPredicate predicateWithBlock:^BOOL(UIView *_Nullable view, NSDictionary<NSString *, id> *_Nullable bindings) {
        return [view isKindOfClass:[UITableViewCell class]] && [view RKT_descendantMatching:^BOOL(UIView *descendant) {
            return [descendant.accessibilityLabel containsString:@"Help"];
        }];
    }]] tap];
```

It isn't nearly as clean of an interface and requires you to have more knowledge about the app's structure, but gives you full control of what you want to interact with.

**Comment by justinseanmartin** [comment]
I think it should be fairly easy to streamline the syntax with some changes to KIF to end up looking something like:

```
[[[viewTester usingClass:UITableViewCell.class] usingDescendantMatcher:[viewTester usingLabel:@"Help"]] tap];
```

I need to think a little more on how the actual syntax would look. It needs to be clear as to whether the element being interacted with is a descendant being matched or the element with the descendant that was matched. In our case, we specifically wanted to interact with the UITableViewCell.

Another option to get syntax that looks more like UITesting might be to introduce a new actor (maybe `filteringTester`?) that expects to continually narrow the scope of which elements should be interacted with:

```
[[[[filteringTester descendant:[viewTester usingClass:UITableViewCell.class]] descendant:[viewTester usingLabel:@"Help"]] tap];
```

This could be further improved upon to streamline it further. I don't have cycles to push in that direction at the moment, but would love to see the framework move in that direction. If you're interested, I'd love to chat more. If not, you can definitely achieve your goals, but the code won't be quite as clean.

Hope this helps!
