### ISSUE TITLE
Unexpected behavior if KIF action fails within an XCTAssert

### ISSUE THREAD

**Issue by LMojica** [kif-framework/KIF#1013]
In some of my tests, I have statements similar to the following code:

`XCTAssert(mainPO.getListItems() == 1, "Should be one item.")`

The function `mainPO.getListItems()` calls `-waitForTappableViewWithAccessibilityLabel` in `KIFUITestActor`. 

If the `-waitForTappableViewWithAccessibilityLabel` fails to find the view, it will post a failure message to the logs, but instead of the test stopping, it continues running. Then the XCTAssert will post a failure to the logs by re-throwing the KIF failure, but the test still continues running. Finally, the test fails for some other reason because the test is not in an expected state.

This leads to 3 failure message in a single test, and it throws off my CI server because it causes it to report that the test failed 3 times, instead of once.

Here are some sample logs:

```
MainPO.swift:14: error: -[IntegrationTests.ListItemsTests testListItem] : The step timed out after 45.00 seconds: Failed to find accessibility element with the label "list-item"

ListItemsTests.swift:87: error: -[IntegrationTests.ListItemsTests testListItems] : 
XCTAssertTrue failed: throwing "The step timed out after 45.00 seconds: Failed to find accessibility element with the label "list-item"" - Should be one item.

MainPO.swift:19: error: -[IntegrationTests.ListItemsTests testListItem] : The step timed out after 45.00 seconds: Failed to find accessibility element with the label "Back"
```

As you can see, the first failure is caused by a KIF timeout while waiting for a view, the second failure is caused by the XCTAssert by throwing the same error as the KIF timeout, and the third failure is caused by a KIF action that is further along in the test. I have verified that `continueAfterFailure` is set to `false`.

**Comment by justinseanmartin** [comment]
IIUC, `MainPO` is a library of helper methods that you're calling out to from your tests? How is that set up? Is it an extension on `KIFTestCase` or is it a standalone class? It seems like the failure handling for that class is what is causing your issue. Do you see it hitting `KIFTestCase failWithException:stopTest:` on the first failure?

If I put an `XCTFail(@"Fail!");` in the middle of a KIF test, it does abort the test immediately.

We have a small "Robot" base class that we subclas for all of our helper abstractions for different screens and UI flows. It holds a reference to the test case and implements KIFTestActorDelegate and delegates any failures back to the `KIFTestCase` instance for the test being run. This has been fine for us.

**Comment by LMojica** [comment]
`MainPO` is a library of helper methods and is very similar to how you describe your "Robot" base class. It holds a reference to my base test class, `BaseTest`, and `BaseTest` is what subclasses `KIFTestCase`. But it does not implement `KIFTestActorDelegate`. Is that something that is necessary? All other failures, whether they are XCTAssert failures or KIF timeout failures, work correctly when not used together. This unexpected behavior only surfaces if a KIF method has an error while inside an XCTAssert method.

**Comment by justinseanmartin** [comment]
I wouldn't be surprised if `XCTAssert` was catching exceptions, even for non-`Throws` asserts, which would cause the behavior you're seeing. If you do:

```
let itemCount = mainPO.getListItems()
XCTAssert(itemCount == 1, "Should be one item.")
```

It only generates one failure?

**Comment by justinseanmartin** [comment]
Also, regarding the implementing of `KIFTestActorDelegate`, it seems fine the way you have it too. Our way allows directly using `tester` and `viewTester` the same way as you'd use them from your tests.

**Comment by LMojica** [comment]
Yes, I can confirm that if I use the following code, I get only 1 error:
```
let itemCount = mainPO.getListItems()
XCTAssert(itemCount == 1, "Should be one item.")
```
If I make `mainPO.getListItems()` fail, it has 1 error. If I make the XCTAssert statement fail, it has one error.

Looking at the source code for XCTAssert shows that it does in fact catch the failure and writes its own failure. https://github.com/apple/swift-corelibs-xctest/blob/master/Sources/XCTest/Public/XCTAssert.swift.

I guess at this point all we can do is make sure to use them separately?

**Comment by justinseanmartin** [comment]
Yep, seems like it unfortunately. If you come up with a clever solution, please feel free to post back.
