### ISSUE TITLE
Unable to distinguish Next button from Next keyboard button

### ISSUE THREAD

**Issue by colinator** [kif-framework/KIF#1015]
Is there a way to waitForView... such that I can distinguish between the keyboard next button and a button on the screen with label 'Next'? Keyboard buttons have accessory traits 'Button + PlaysSound + KeyboardKey', while a regular button will have just 'Button'.

If not, maybe I'll contribute some way...

**Comment by justinseanmartin** [comment]
I'd generally recommend using the newer `viewTester` syntax where possible. It has a less verbose and more flexible API to work with. In that, you can use (ObjC):

```
[[[viewTester usingLabel:@"Next"] usingTraits:(UIAccessibilityTraitButton | UIAccessibilityTraitKeyboardKey)] tap];
```

Otherwise, I think the API that you're looking for is `waitForViewWithAccessibilityLabel:traits:`:
https://github.com/kif-framework/KIF/blob/master/Classes/KIFUITestActor.m#L73

**Comment by colinator** [comment]
Neither of those do what I want. On screen there exists a UIButton with 'Next', and the keyboard 'Next' button. How can I get the UIButton? If I pass UIAccessibilityTraitButton to traits, it will still find the keyboard button first.

**Comment by justinseanmartin** [comment]
Ah, I see the issue, sorry for the misunderstanding at first. You need a way to either find an exact match on the traits, or you need to add a negated trait specifically for matching on the non-keyboard button.

Today with the `viewTester` syntax, you could do it with `usingPredicate:[NSPredicate predicateWithBlock:^{}]` and add your own check for the object's traits, the object's class type, or whatever else you want.

It'd also be reasonable to add a variant of `usingTraits:` of either `usingExactTraits:` or `usingExcludedTraits:` (or something along those lines) to KIFUIViewTestActor. Would be happy to review a PR if you wanted to introduce that. Then all actions are available for free in the syntax for matched elements (unlike with the `KIFUITestActor`).

**Comment by justinseanmartin** [comment]
Does that meet your needs? If you're interested in adding `usingExactTraits:` or `usingExactTraits:`, we can keep this issue open to track that.

**Comment by colinator** [comment]
Ah, yes: I'm able to write:

`let a = mytester.usingLabel("Next").usingPredicate(NSPredicate(format: "accessibilityTraits == %i", UIAccessibilityTraitButton | UIAccessibilityTraitNotEnabled))`

...and that finds my button instead of the keyboard key.

thanks!
