### ISSUE TITLE
Unable to distinguish Next button from Next keyboard button

### ISSUE THREAD

**Issue by colinator** [kif-framework/KIF#1016]
Is there a way to waitForView... such that I can distinguish between the keyboard next button and a button on the screen with label 'Next'? Keyboard buttons have accessory traits 'Button + PlaysSound + KeyboardKey', while a regular button will have just 'Button'.

NOTE: I've re-created this issue because neither of the current ways of getting to elements solves this problem. For instance, calling `waitForViewWithAccessibilityLabel:traits:` does NOT work, because the Next keyboard button has the same accessibility label as the Next button on the screen, and it has a superset of the traits. The keyboard button has traits of `Button + PlaysSound + KeyboardKey`, while the regular button has `Button`, and code like this:

`BOOL traitsMatch = ((element.accessibilityTraits) & traits) == traits;`

will find the keyboard button first.

Obviously lots of ways to solve this. I'd suggest the ability to pass in a predicate, so the client has full control over that logic. I'm happy to contribute...

**Comment by justinseanmartin** [comment]
Sorry, I misunderstood the issue the first time. I supplied an answer in #1015, lets keep the conversation in the one issue. I'll re-open that one.
