### ISSUE TITLE
Taking Screenshots

### ISSUE THREAD

**Issue by brupm** [kif-framework/KIF#1019]
Would I be able to write a test that takes a screenshot of the app while it's running?

**Comment by mikelupo** [comment]
Yes.



-----Original Message-----

**Comment by mikelupo** [comment]
@brupm 
Sounds like you're considering using KIF. I hope it meets your needs.
I will go ahead and close this. If this does not answer your question, feel free to reopen.

Mike

**Comment by justinseanmartin** [comment]
FYI - You can also combine it with a framework like Facebook's snapshot tests to assert that visuals on the screen look like you'd expect:

https://github.com/facebookarchive/ios-snapshot-test-case

We did some changes locally for our workflows and don't currently combine the two frameworks, but we've talked about doing that.
