### ISSUE TITLE
How to take screenshot when test case failed?

### ISSUE THREAD

**Issue by jack3010** [kif-framework/KIF#1021]
Which way to take a screenshot when test case failed?

**Comment by justinseanmartin** [comment]
Take a look at the code here:
https://github.com/kif-framework/KIF/blob/master/Additions/UIApplication-KIFAdditions.m#L141

You need to set the `KIF_SCREENSHOTS` environment variable (can be done in Xcode's scheme editor) to the path where you want the failure images to be placed.
