### ISSUE TITLE
No viable overloaded '=' error in results.cpp page?

### ISSUE THREAD

**Issue by faisalazeez** [kif-framework/KIF#1026]
I am unable to build the project as it shows, No viable overloaded '=' error in results.cpp page. Need help to solve the issue.

Thanks in advance.

**Comment by mikelupo** [comment]
I don’t recall ever having seen this error. 
My first guess is that you added KIF to a UI test project instead of a UNIT test project. 

If that’s not the issue please comb over the readme on github to see if you missed any details.

**Comment by justinseanmartin** [comment]
@faisalazeez - How are you integrating KIF into your project? 

If you just clone the KIF repo, there are some samples showing how to manually integrate the KIF project:
https://github.com/kif-framework/KIF/tree/master/Documentation/Examples

If you use CocoaPods to integrate it into your unit test target (as @mikelupo pointed out), it should "just work".

**Comment by faisalazeez** [comment]
@justinseanmartin I updated my cocoa pods and Now it's working.
