### ISSUE TITLE
Module KIF not found

### ISSUE THREAD

**Issue by sayrong** [kif-framework/KIF#1027]
Hi! 
Can't figure out how to launch Calculator example. 
Show error: KIF module not found 
<img width="1087" alt="2017-12-06 13 07 33" src="https://user-images.githubusercontent.com/10937851/33656250-84d40c82-da86-11e7-84a5-60a7722158ba.png">
Kif added into a workspace 
<img width="1086" alt="2017-12-06 13 09 16" src="https://user-images.githubusercontent.com/10937851/33656416-056c0638-da87-11e7-9966-83bd3abe468a.png">
Testing target is created. 
Added libKIF.a 
<img width="1127" alt="2017-12-06 13 12 49" src="https://user-images.githubusercontent.com/10937851/33656531-5d943970-da87-11e7-9a38-d1099ccedb9f.png">
And added -ObjC flag in the "Other Linker Flags"
<img width="1102" alt="2017-12-06 13 15 33" src="https://user-images.githubusercontent.com/10937851/33656601-928c12e2-da87-11e7-8cdf-ef13a3646e29.png">

**Comment by mikelupo** [comment]
I think I just use “kif.h”

**Comment by mikelupo** [comment]
actually, I just got on the train and am able to open up my laptop. I integrate KIF the way you have, and I use: 
```
#import "KIF/KIF.h"
```

**Comment by sayrong** [comment]
Thank you! 
Now other errors came. 
<img width="1091" alt="2017-12-06 14 43 27" src="https://user-images.githubusercontent.com/10937851/33660182-041f2618-da94-11e7-9555-d84941da2c86.png">
The second error I solved by import "KIFTypist.h" to KIF.h
With .animationSpeed don't know what to do.

**Comment by mikelupo** [comment]
@sayrong looks like this import is missing? 
#import "UIApplication-KIFAdditions.h"
All I'm doing is searching the code base for where these things are defined and then making an educated "guess".  You could do the same.

**Comment by sayrong** [comment]
Great. Thank you for help! 
<img width="1177" alt="2017-12-06 15 11 56" src="https://user-images.githubusercontent.com/10937851/33661225-fb845916-da97-11e7-95ee-a89793fcc2cb.png">

**Comment by mikelupo** [comment]
You are welcome. I Hope you find that KIF is useful for your testing endeavors.
