### ISSUE TITLE
Test fails for every single scenario?

### ISSUE THREAD

**Issue by faisalazeez** [kif-framework/KIF#1030]
Test Fails with message: 
Assertion Failure: UIApplication-KIFAdditions.m:119: failed: caught "NSInvalidArgumentException", "*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil"

1. Did added Kif using cocoa pods, pod 'kif'
2. created uitest targets
3. created simple ui with accessilbility labels
4. created  test cases
         // #import "SignUpTests.h"

       @implementation SignUpTests

      -(void)testLoginEmptyUserName
      {
           [tester clearTextFromViewWithAccessibilityLabel:@"UserName"];
           [tester tapViewWithAccessibilityLabel:@"Login"];
           [tester waitForTappableViewWithAccessibilityLabel:@"Username cannot be empty"];
           [tester tapViewWithAccessibilityLabel:@"Ok"];
      }

Finally every single test cases are failing, what am i doing wrong here??? Need advice, thanks.

**Comment by justinseanmartin** [comment]
Please take note of the bold `IMPORTANT!` block at the top of the [README.md](https://github.com/kif-framework/KIF/blob/master/README.md):

```
IMPORTANT! Even though KIF is used to test your UI, you need to add it to your Unit Test target, not your UI Test target. The magic of KIF is that it allows you to drive your UI from your unit tests and reap all the advantages of testing in-process.
```

**Comment by faisalazeez** [comment]
@justinseanmartin  thanks. My mistake.
