### ISSUE TITLE
“UIAExceptionBadPoint”, “tap point is not within the bounds of the screen”

### ISSUE THREAD

**Issue by Srividya86** [kif-framework/KIF#1038]
While using `acknowledgeSystemAlert()` to allow system alerts getting an error 

```UIAExceptionBadPoint”, “tap point is not within the bounds of the screen” ```

But when i try to click on `Don'tAllow` which is working as expected 

MacOS - 10.12.6
xcode - 9.0
simulator - 10.0

**Comment by mikelupo** [comment]
Can you put together a small project that exhibits the problem?

**Comment by Srividya86** [comment]
Here is sample project for failure alert https://github.com/Srividya86/KIFFailureSystemAlertDemo

**Comment by justinseanmartin** [comment]
Could you try on Xcode 9.2? Is it specific to iOS 10 simulators? 

Similar to my comment in #979, I generally recommend trying to avoid using anything that relies on `UIAutomationHelper`, as it is a black box supplied by Apple that can't be debugged.

**Comment by justinseanmartin** [comment]
I have confirmed that `acknowledgeSystemAlert` works fine on Xcode 9.2 with iOS 11.2 by running `[SystemAlertTests testAuthorizingLocationServicesAndNotificationsScheduling]` with a simulator in a clean state. Please reactivate if you have more information.
