### ISSUE TITLE
How do I tap on a label within another label

### ISSUE THREAD

**Issue by ristkof** [kif-framework/KIF#1042]
Is there a way to do:

viewTester().usingLabel("label1").usingLabel("label2").tap()

so that KIF makes sure that label2 is nested within label1 before it does a match to call tap()  ?

I need this situation because some of my labels have the same accessibility labels and I want to tap on the right one, not on the first one that is found in the view hierarchy. I can not seem to find anything in the documentation or in the headers, but maybe I'm overlooking something obvious.

**Comment by justinseanmartin** [comment]
It is possible, but there isn't a super convenient way to do it.

For now, the way to manage to do this is to build your own custom predicate for the element that you want to match. For example, you could do:

```
    [[[viewTester usingLabel:@"label2"] usingPredicate:[NSPredicate predicateWithBlock:^BOOL(UIView *view, NSDictionary<NSString *, id> *bindings) {
        return ([view _ancestorMatching:^BOOL(UIView *descendant) {
            return [descendant.accessibilityLabel isEqualToString:@"label1"];
        }] != nil);
    }]] tap];
```

Where _ancestorMatching looks like:
```
@implementation UIView (KIFExtensions)
- (UIView *)_ancestorMatching:(BOOL (^)(UIView *))block;
{
    NSParameterAssert(block);
    UIView *view = self.superview;
    while (view) {
        if (block(view)) {
            return view;
        }
        view = [view superview];
    }
    return nil;
}
@end
```

We don't need this all too often ourselves, so haven't spent much effort on trying to come up with a convenient/consistent syntax for exposing this functionality. If you have suggestions, would definitely be interested in a proposal.

Another approach that likely would be more accessibility friendly would be to expose the context of the container element as part of the accessibility for the element that has interaction enabled. For example, if you have a bunch of rows with a button with text "Details" (example), you might want the button's `accessibilityHint` or `accessibilityValue` to have context about what the Details button is for.
