### ISSUE TITLE
Swipe down 10 times (Pull to refresh)

### ISSUE THREAD

**Issue by vishnu1989** [kif-framework/KIF#1049]
I want to Pull to refresh 10 times

below code working for single time
tester().pullToRefreshView(withAccessibilityLabel: Home_Screen.PullToRefresh, pullDownDuration: KIFPullToRefreshTiming.inAboutOneSecond)

**Comment by justinseanmartin** [comment]
Wrap it in a for loop and potentially put a waitForTimeInterval in between? 

This is not a framework issue though. For general programming advice about how to use KIF, please ask on StackOverflow.
