### ISSUE TITLE
viewTester().usingLabel does not work in Simulator iOS 11.2

### ISSUE THREAD

**Issue by ristkof** [kif-framework/KIF#1050]
See attached project.

To reproduce: build and test on iOS Simulator 11.2 in Xcode 9.2. The test will fail.

Do the same on iOS Simulator 11.1 in Xcode 9.2 and the test works.

This is a really simple UIButton, nothing particular to it, just a basic sample project from the Xcode templates, add a UIButton and that's it.
[kiftest.zip](https://github.com/kif-framework/KIF/files/1696828/kiftest.zip)

**Comment by justinseanmartin** [comment]
Your tests don't subclass from `KIFTestCase` or you need to at least call `KIFEnableAccessibility();` yourself. 

Interestingly, the tests pass just fine on an "iPhone 8s Plus" with iOS 11.2, but fails on an iPhone SE and iPhone X. I'd guess there was probably an Apple bug where they were turning on the Accessibility framework always, even when not explicitly requested.

I'm going to put a fix where trying to get a tester/viewTester before the Accessibility framework has been loaded will crash in a helpful way.

**Comment by ristkof** [comment]
That works for me! Thanks.
