### ISSUE TITLE
KIF fails to build in Release configuration

### ISSUE THREAD

**Issue by wedkarz** [kif-framework/KIF#1055]
KIF fails to build in Release configuration in version 3.7.0 (which prevents from using it via Carthage).
The problem is caused by _unused variable_ error and _treat warnings as errors_ setting combined with _enable_ns_assertions_ set to NO in Release scheme.
The only use for specific variables is cut from Release configuration.

I have prepared fix in #1054. Could you please consider it to release ASAP so that Carthage is enabled again with all the changes that appeared in v3.7.0?

UPDATE:
Could you consider running tests/integrations on Release configuration?

**Comment by Prince2k3** [comment]
Yes! Builds are breaking

**Comment by justinseanmartin** [comment]
Will get it merged ASAP. Sorry about that!
________________________________

**Comment by Prince2k3** [comment]
A new release would be better I think. Not sure if Carthage would pull just from master with releases already set.

**Comment by wedkarz** [comment]
@Prince2k3 If there is no change in framework version and you have specified a semantic version in Cartfile, then `carthage update` will not work. If you have pinned KIF to master in Cartfile, then it will work without version changes. To make it work for everyone new version is required.

Also, repeating my last question. Would it be possible to change the configuration that the KIF CI is using from _Debug_ to _Release_?

**Comment by justinseanmartin** [comment]
@wedkarz - I don't think we'd want to run the tests on the Release configuration. At least at first glance, it seems weird that you'd want to consume a Release version of KIF to run within your tests, seems like it might make debugging harder if it was running with any sort of clang optimizations enabled. We could definitely add a task to the CI script to ensure that we can build / archive KIF for Carthage though.

Is the issue that you want to root out that the debug & release configurations are enforcing different build settings for warnings/errors? If we had them being consistently enforced across the configurations, would that resolve your concern?

**Comment by wedkarz** [comment]
@justinseanmartin Right. I went too far. 
It should be enough to add tasks to CI that are assembling potential deliverables (like framework in Release configuration).

Diverging configurations only when it is necessary for sure helps to keep everything in the healthy state. However, configurations are to help with differences :)

**Comment by Prince2k3** [comment]
@wedkarz So what do I need to configure in order to use the latest release? As I see it right now setting the version fixed to 3.6.0 is what I had to do in order to fix the issue. I don't know what exactly changed. I guess what would be the resolution going forward. I'm not a CI expert at all. All I can do is relay the message to DevOps on what to do to fix the issue.

**Comment by justinseanmartin** [comment]
I just tagged a 3.7.1 version, please give that a shot. Sorry for the delay.

**Comment by mikelupo** [comment]
Don’t include KIF in the release build?
Why would anyone do that??
