### ISSUE TITLE
使用KIF如何在测试类中，接收到项目中app启动时的发出的通知？或者更详细的如下

### ISSUE THREAD

**Issue by UniqueSilence** [kif-framework/KIF#1071]
我想在Test中，使用 (NSNotification *)waitForNotificationName:(NSString *)name object:(id)object whileExecutingBlock:(void(^)(void))block来接收 Project中didFinishLaunchingWithOptions方法内部，在确保我的数据下载完毕的情况下发出的通知，然后在test中，接收到通知后，可以进行数据展示完整的UI测试，各位有什么高见嘛？

**Comment by justinseanmartin** [comment]
Translation -
Subject: How does the use of KIF in the test class receive a notification from the app when the app starts? Or more detailed as follows

Body: 
I want to use the (NSNotification *) waitForNotificationName:(NSString *)name object:(id)object whileExecutingBlock:(void(^)(void))block to receive the internal of the didFinishLaunchingWithOptions method in Project, to ensure that my data is downloaded. After the completion of the notification in the case, and then in the test, after receiving the notification, you can display the data to complete the UI test, what good are you?

**Comment by justinseanmartin** [comment]
The problem with `waitForNotificationName:object:whileExecutingBlock:` is that you need to ensure that the test code executes before the notification that you want to observe. Unfortunately, app launch notification happens before the test will start executing, so you won't ever get that notification. This won't work.

You shouldn't need to deal with that though, KIF will by default poll for up to 10 seconds (customizable with `usingTimeout:`) for an element to become visible. Just look for an element to be present on the screen that would indicate to a user that the data has been loaded. 

If there is no way in the UI to tell that fresh data has been loaded, consider this potentially a usability issue for users of your app. Alternatively, you could expose an API on your app delegate or a static BOOL potentially that indicates to the tests that app initialization has been completed.
