### ISSUE TITLE
现在支持真机了吗？

### ISSUE THREAD

**Issue by Guolanlan** [kif-framework/KIF#1074]
我今天试的还不支持真机……

**Comment by mikelupo** [comment]
Translation:
What I tried today does not support real machine...

Looks like it works on simulator but I’m on the real device

**Comment by justinseanmartin** [comment]
Subject is "Do you support the real machine now?"

Answer: Should be possible to run tests on real devices and not just the simulator. However, I haven't attempted running tests on physical hardware in a long time, as it hasn't been necessary for our testing.

**Comment by shuai265** [comment]
Now KIF is support run tests on real devices.

**Comment by mikelupo** [comment]
I have tests that use KIF. They run on real devices only. Never the simulator. It’s never “not” worked for me. The only difference between sim and real is that on real (non-jail broken) devices we cannot interact with system prompts. We avoid them.
