### ISSUE TITLE
IOHIDEvent parameter meaning

### ISSUE THREAD

**Issue by JunyiXie** [kif-framework/KIF#1075]
IOHIDEventRef kif_IOHIDEventWithTouches(NSArray *touches) {
...
IOHIDEventCreateDigitizerFingerEventWithQuality(kCFAllocatorDefault, // allocator
                                                timeStamp, // timestamp
                                                (UInt32)[touches indexOfObject:touch] + 1, //index
                                                2, // identity
                                                eventMask, // eventMask
                                                (IOHIDFloat)touchLocation.x, // x
                                                (IOHIDFloat)touchLocation.y, // y
                                                0.0, // z
                                                touch._pressure, // tipPressure
                                                0, // twist
                                                5.0, // minor radius
                                                5.0, // major radius
                                                1.0, // quality
                                                1.0, // density
                                                1.0, // irregularity
                                                (IOHIDFloat)isTouching, // range
                                                (IOHIDFloat)isTouching, // touch
                                                0); // options
...
}

These parameters effects on UIEvent?
thanks

**Comment by justinseanmartin** [comment]
This is reverse engineered from running class-dump on `IOKit`. I think the comments that are there is about as much information as we have, and could change in the future.
