### ISSUE TITLE
How to use cocoapods to manage the KIF testcase

### ISSUE THREAD

**Issue by Chenneyfang** [kif-framework/KIF#1079]
I am a QA, i wan't to test the app ,but i don’t like to submit my testcases together with the developer‘s。At first, i think the cocoa pods can do it. But i don't know how to config it. Who can help me?

**Comment by mikelupo** [comment]
I am confused by your question. Are you wanting to submit tests to KIF framework to support a contribution to KIF? Or are you asking about how to submit tests you have written for your own personal or company app?

**Comment by Chenneyfang** [comment]
I am asking about how to submit my testcases to pods,and all the testcases  i have written for my  company app.

**Comment by justinseanmartin** [comment]
CocoaPods supports defining a `test_spec` in your podspec:
https://guides.cocoapods.org/syntax/podspec.html#test_spec

You could add a dependency on KIF from that `test_spec` syntax. They mostly just supports unit test scenarios today though. CocoaPods doesn't support being able to set your application as the test's application host. If you had a UI Library that you wanted to test, you could do this.

In general, I'd recommend keeping your test sources and app sources together. That way, when the app behavior changes, it is easy to find and fix the related tests. Also, it gives more capability for developers to run the tests as well without additional setup.

I'm going to close the issue, as this isn't really a problem or feature request for the KIF framework.

**Comment by justinseanmartin** [comment]
Also, this might get more ideas from stackoverflow.

**Comment by mikelupo** [comment]
I’d like to add that this would be a better question for Stackoverflow as it’s more related to use with cocoapods
