### ISSUE TITLE
UIAccessibilityElement accessibilityElement:view:withLabel:value:traits:tappable:error:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by brainsz** [kif-framework/KIF#1082]
UIAccessibilityElement accessibilityElement:view:withLabel:value:traits:tappable:error:]: unrecognized selector sent to class,why?

**Comment by mikelupo** [comment]
It’s always helpful if you can write/provide a small sample project (including instructions) that can help reproduce. We can’t begin to speculate otherwise.

**Comment by justinseanmartin** [comment]
Going to close this until we get more detailed information.
