### ISSUE TITLE
dylib #12 could not be loaded while using Xcode10 

### ISSUE THREAD

**Issue by LWX124** [kif-framework/KIF#1084]
dyld: lazy symbol binding failed: can't resolve symbol _XCStringFromRect in /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib/../../Library/Frameworks/XCTest.framework/XCTest because dependent dylib #12 could not be loaded

> 
![dylib_cant_be_loaded](https://user-images.githubusercontent.com/12760649/44249075-da4e0700-a220-11e8-9b04-8650ca0217e7.png)

**Comment by justinseanmartin** [comment]
Thanks for reporting this. I'm going to tag this as an Xcode 10 issue (looks like you're running the beta from the path in the terminal).

If you wanted to put up a PR for now with changing this to `#if defined(__IPHONE_11_0) && !defined(__IPHONE_12_0)` for now with a comment referring to this issue number, that would be great.

**Comment by AhmedEid** [comment]
Hi, I am still seeing this issue, using the latest commit of KIF (not latest version, but latest commit, that includes this PR) 
We are running KIF tests on iPhone 8 iOS 11.2 Simulator. 

<img width="1099" alt="screen shot 2018-08-31 at 9 56 57 am" src="https://user-images.githubusercontent.com/972257/44916621-39714880-ad04-11e8-862d-52ae622508f9.png">


When I deleted the entire block of code in that method (- (void)writeScreenshotForException:(NSException *)exception;)  then re-ran, it failed with the same error, but in a different place 

<img width="1120" alt="screen shot 2018-08-31 at 10 00 43 am" src="https://user-images.githubusercontent.com/972257/44916863-c0bebc00-ad04-11e8-9a1e-94e82bd79c38.png">

**Comment by justinseanmartin** [comment]
I assume you're running with Xcode 10 Beta 6? 

In the first screenshot, it appears my fix to add `!defined(__IPHONE_12_0)` didn't work. If you check `Availability.h` from your Xcode's quick find (CMD+SHIFT+O), does it contain this define? If you search the build logs after performing a clean build with Xcode 10, does it show that it is compiling with `XCTestCase-KIFAdditions.m`?

In the second screenshot, the exception breakpoint looks like it is in a completely different method than where you removed the `#if defined` check. I assume it just didn't recompile KIF for some reason. I'd try to clean and build again.

**Comment by abarisain** [comment]
Haven't had the chance to test it yet, but Apple told me that it should be resolved in Xcode 10.1 beta in the radar I filed

**Comment by yonaskolb** [comment]
Xcode 10.1 beta 3 works with KIF 3.7.4 👍

**Comment by justinseanmartin** [comment]
Thanks for confirming @yonaskolb!

**Comment by justinseanmartin** [comment]
Xcode 10.1 just dropped, so please try updating to the latest Xcode and report back any issues you encounter. Thanks!
