### ISSUE TITLE
Please update "Use With Swift" section

### ISSUE THREAD

**Issue by datinc** [kif-framework/KIF#1085]
I was intermittently struggling with getting UIAlertController buttons to be pressed. Tests would randomly fail when I tried to tap the button. I know in the readme you specifically call out that you need to call `KIFEnableAccessibility()` if you are using XCTestCase directly... however in the readme section [Use With Swift](https://github.com/kif-framework/KIF/blob/master/README.md#use-with-swift) you provide code which I happily copied and pasted. You would have saved me more time than I would like to admit if a code snippet was added to ensure that `KIFEnableAccessibility()` was called. I ended up using [XCTestObservationCenter](https://developer.apple.com/documentation/xctest/xctestobservationcenter) and setting NSPrincipalClass to `TestBundleName.ObserverClassName`. Worked like a charm.

**Comment by justinseanmartin** [comment]
Please take a look at the proposed solution and let me know what you think.
