### ISSUE TITLE
Can't run tests after upgrading the KIF version

### ISSUE THREAD

**Issue by mohammdsss1** [kif-framework/KIF#1096]
So I used to have KIF inside my Swift project. It was on 3.5.1. 
Yesterday I tried to run the tests but Xcode refused due to some errors, and asked me to to upgrade the library. 
So I updated it to 3.7.4 and suddenly this error starts to appear:

<img width="601" alt="screen shot 2019-01-31 at 11 47 16" src="https://user-images.githubusercontent.com/7831855/52045915-2cc07d00-254e-11e9-80cf-df3d7cb439a2.png">

I am integrating KIF through CocoaPods, here is my pod file:
```
target :KIFProjectTests do
    shared_pods
    pod 'KIF', :configurations => ['Debug']
end
```

I have also the bridging header that import KIF inside the Swift project.
<img width="316" alt="screen shot 2019-01-31 at 11 51 00" src="https://user-images.githubusercontent.com/7831855/52046093-92146e00-254e-11e9-80e9-7a8416f0d3d6.png">

What I am missing?

**Comment by AnasAlmomany** [comment]
+1 
Same Here using Xcode Version 10.0 (10A255).

**Comment by justinseanmartin** [comment]
It seems like it is probably a project integration issue not an issue with the KIF framework itself. It is possible that your header search paths for the target are incorrectly configured? I'm going to mark the issue closed until there is something pointing at a KIF framework issue.

The warning you were getting in Xcode was not referring to bumping the KIF library sources itself, it probably was referring to upgrading the project settings. I believe that is taken care of automatically by bumping the version of CocoaPods that you're using.

If you can create a small sample project that reproduces the issue, I'd be willing to take a look at that to see if I can help diagnose the error.

You could also try enabling `modular_headers: true` on the CocoaPods dependency line, which would mean that you don't need the bridging header. Instead you can use proper `import KIF` in Swift and `@import KIF;` in ObjC.
