### ISSUE TITLE
How do I test sliding from one view to another？

### ISSUE THREAD

**Issue by semnyqu** [kif-framework/KIF#1114]
I wanted to test a custom gesture view to unlock, but I couldn't find anything in KIF that would allow me to slide from view to another without letting go；

**Comment by semnyqu** [comment]
![image](https://user-images.githubusercontent.com/14885293/61361493-27b07980-a8b3-11e9-8332-be1b38d74b56.png)

**Comment by semnyqu** [comment]
![image](https://user-images.githubusercontent.com/14885293/61361594-4b73bf80-a8b3-11e9-945d-0e40961a03a4.png)

**Comment by semnyqu** [comment]
![image](https://user-images.githubusercontent.com/14885293/61365348-259de900-a8ba-11e9-8299-41abc4eb794d.png)
Why not open this method?

**Comment by justinseanmartin** [comment]
What do you mean by `open this method`?

I think you could do what you suggested if the parent view were the accessibility element. KIF generally expects to be acting on a specific UI element that is matched on. Introducing an API that requires matching more than one UI element on the screen would be very different than existing actions, so would require a bit of thinking to decide the best way to expose it.

I think it might work if you used `waitForView` to match the element and then called this method and used relative coordinates from the view you matched.

**Comment by semnyqu** [comment]
> What do you mean by `open this method`?
> 
> I think you could do what you suggested if the parent view were the accessibility element. KIF generally expects to be acting on a specific UI element that is matched on. Introducing an API that requires matching more than one UI element on the screen would be very different than existing actions, so would require a bit of thinking to decide the best way to expose it.
> 
> I think it might work if you used `waitForView` to match the element and then called this method and used relative coordinates from the view you matched.

Thank you!
