### ISSUE TITLE
UIAutomationHelper.acknowledgeSystemAlertWithIndex Does Not Work In Xcode 11.1

### ISSUE THREAD

**Issue by patmalt** [kif-framework/KIF#1125]
`KIFUITestActor`'s `- (BOOL)acknowledgeSystemAlertWithIndex:(NSUInteger)index;`  no longer works when running on Xcode 11.1 and an iOS 13.1 simulator.

From my initial debugging, the alert `isKindOfClass` `nilElementClass` and it is never valid or visible.

**Comment by patmalt** [comment]
For context: https://github.com/kif-framework/KIF/blob/8a53f3672eb376e44412d2574df25803d1156a52/Classes/UIAutomationHelper.m#L132

**Comment by ksuther** [comment]
PR with a fix is in #1126.
