### ISSUE TITLE
在子线程中使用了UIkit会崩溃，能不能关掉这个检测？

### ISSUE THREAD

**Issue by whihail** [kif-framework/KIF#1131]

**Comment by justinseanmartin** [comment]
Google Translation: "Using UIkit in a child thread will crash, can you turn off this detection?"

Is this specifically a KIF question? Do you have a callstack you can share where KIF is using UIKit on a background thread? If it is a question of the functionality in general, I'd recommend going to StackOverflow for more information. I'm going to resolve this for now, but feel free to reopen the issue with more specific details and a stack trace if this is an issue with KIF.
