### ISSUE TITLE
Is it possible to simulate a shake gesture with KIF?

### ISSUE THREAD

**Issue by ristkof** [kif-framework/KIF#1133]
I can't seem to find any documentation about such a feature... am I missing something?

**Comment by justinseanmartin** [comment]
KIF doesn't currently support this, but it seems reasonably straightforward to add simulating this to the `KIFSystemActor`. You could fetch the first responder and send it a `motionBegan:UIEventSubtypeMotionShake withEvent:event`, spin the runloop for some short time, followed by a `motionEnded:UIEventSubtypeMotionShake withEvent:event`. I'd be supportive of adding this functionality if you wanted to contribute a patch that contained this.
