### ISSUE TITLE
In iPhone 11 Simulator, iOS 13.2.2 , NavigationBarBackItem has a new class '_UIModernBarButton'.

### ISSUE THREAD

**Issue by edisongz** [kif-framework/KIF#1134]
_UIModernBarButton's  userInteractionEnabled property has a default value NO, this can be fixed by append a class type for `- (void)isNavigationItemView;`

**Comment by justinseanmartin** [comment]
Cool, thanks for reporting. Would you mind submitting a patch with the fix, as you're currently set up to test and ensure that it is working as expected. Thanks!

**Comment by erudel** [comment]
I put up a PR to fix this issue: https://github.com/kif-framework/KIF/pull/1158

I verified some of the failing unit tests are now passing on Xcode 11 / iOS 13.4
