### ISSUE TITLE
waitForView(withAccessibilityLabel) is not working with unicode

### ISSUE THREAD

**Issue by PowerPaloma** [kif-framework/KIF#1148]
In my .strings file i have a string with a unicode for non-breaking hyphen( \U2011) but i can't find this label using `waitForView(withAccessibilityLabel)`. There is some method similar for unicode ? Or this method don't suppot unicode yet?

**Comment by justinseanmartin** [comment]
It should match based on the contents of whatever the accessibility APIs are returning for the full UIView hierarchy (starting from the application's `windows` array as the roots). I'm not sure if Apple does something special when exposing that UIKit field information via the accessibility APIs, but we essentially just test `isEqualToString:`. I'd recommend taking a look at the `+[UIView printViewHierarchy]` output and making sure that the element that you're looking for is represented in the tree. 

You can set the `KIF_PRINTVIEWTREEONFAILURE` environment variable to `YES` to have KIF always dump the view hierarchy when test failures are encountered. Another useful environment flag is `KIF_SCREENSHOTS` to have snapshot images be generated on test failure.
