### ISSUE TITLE
Crash in `_setIsFirstTouchForView:` on iOS 14

### ISSUE THREAD

**Issue by changeyourdestiny** [kif-framework/KIF#1152]
Hi, I found iOS14 devices will crash due to:
`@implementation UITouch (TIAs)
- (id)initAtPoint:(CGPoint)point inWindow:(UIWindow *)window
{
  ....
   [self _setIsFirstTouchForView:YES]; //will crash
  //  [self respondsToSelector:@selector(_setIsFirstTouchForView:)] will return NO on iOS14
  ....
}`

**Comment by changeyourdestiny** [comment]
[self setIsTap:YES];// crash too
 [self respondsToSelector:@selector(setIsTap:)] will return NO on iOS14 too

**Comment by steipete** [comment]
Hi folks 👋 I have a working hack over here, I'm sure you can adapt this for KIF as well: https://github.com/google/EarlGrey/issues/1357
