### ISSUE TITLE
[Question] iOS 14 support

### ISSUE THREAD

**Issue by pimms** [kif-framework/KIF#1169]
Hi!

What is the plan/roadmap for iOS 14 support?

Under Xcode12b5 all interactions fail with _"`-[UITouch _setIsFirstTouchForView:]: unrecognized selector sent to instance 0x...`"_.

Thanks 🙂

**Comment by knellr** [comment]
Looks like the issue has been fixed, so we just need a release, I guess that will come with the GM? -> https://github.com/kif-framework/KIF/pull/1153

**Comment by dostrander** [comment]
Yep what @knellr said is correct. We will hopefully be releasing again shortly. Closing, please reopen if you dont think this has been answered
