### ISSUE TITLE
Update KIF version

### ISSUE THREAD

**Issue by billburgess** [kif-framework/KIF#1171]
There have been important PRs that are affecting how KIF works on Xcode 12/iOS 14 that have been approved and merged into master but no new releases since March. A new bug fix update or something would make these PR changes available and really help out those trying to get ready for iOS 14.

**Comment by mpujol** [comment]
+1. I've gotten to the point where the tests run normally for iOS 12 & 13 but 14 doesn't trigger the individual tests to start.

**Comment by dostrander** [comment]
Sorry for the delay in getting an update out. Was trying to fix our CI before we did that. I will make sure to get this done this week

**Comment by dostrander** [comment]
@mpujol and @billburgess 3.7.10 was released this morning.

**Comment by mpujol** [comment]
@dostrander Thank you so much!!! 😄
