### ISSUE TITLE
KIF included as Carthage Linked Library Failed

### ISSUE THREAD

**Issue by vsanchez2187** [kif-framework/KIF#1188]
Hello everyone : 

I have an issue integrated the KIF using Carthage  , once i add it to my Cartfile as : 

**github "kif-framework/KIF" "v3.7.11"**

And executed **carthage update --platform iOS** 

I try to execute one example test in my code and it lunch this error on the console : 

**(dlopen_preflight(/Users/vsanchez/Library/Developer/Xcode/DerivedData/IPSCore-clrdhaauweqzzobfdfqevuufkbuc/Build/Products/Debug-iphonesimulator/IPSCustom.app/PlugIns/IPSCustomTests.xctest/IPSCustomTests): Library not loaded: @rpath/KIF.framework/KIF**

After check the path of were the KIF was compiled , with the rest of my libraries , was OK
The only way to fix this was included the KIF.framework compiled library as an Embed library on my principal target .

Does anyone has faced the same issue ??

**Comment by Sc4pego4t** [comment]
Seems problem is here:
Implicit conversion loses integer precision: 'UIDeviceOrientation' (aka 'enum UIDeviceOrientation') to 'int'
KIF/Classes/KIFSystemTestActor.m

**Comment by vsanchez2187** [comment]
@Sc4pego4t  thanks it works using Xcode 11.7
