### ISSUE TITLE
Selecting date picker value when picker timezone is not local does not give the expected time

### ISSUE THREAD

**Issue by danielbarela** [kif-framework/KIF#1214]
We have a UIDatePicker which has the timeZone set to ```TimeZone(secondsFromGMT: 0)``` We then test this by calling ```tester().selectDatePickerValue(["Nov 2", "7", "00", "AM"], with: .forwardFromCurrentValue);``` which ultimately should set the date to November 2 7:00:00 +0000, however it is being set to November 2 14:00:00 +0000 because my timezone is 7 hours behind GMT.

If I modify the KFUITestActor class in the ```- (void)selectDatePickerValue:(NSArray *)datePickerColumnValues fromPicker:(UIDatePicker *)datePicker withSearchOrder:(KIFPickerSearchOrder)searchOrder``` method to set the dateComponents timeZone to datePicker.timeZone, it works as expected.  Would you like me to issue a pull request for this?

**Comment by dostrander** [comment]
@danielbarela if you could that would be great. If not i'll try to get to it in the next few weeks
