### ISSUE TITLE
[Question] Can I did test for check communication between instances?

### ISSUE THREAD

**Issue by bimawa** [kif-framework/KIF#1224]
I have Chat application and wanna cover communication between two or more instances. How can I do it with KIF?

**Comment by justinseanmartin** [comment]
If I understand correctly, you'd like to verify the communication between 2 different instances of the app running, is that right? You'd need a higher level framework that sits outside of the app process and some way to communicate between test runners. Then KIF could pick up instructions from an external communication channel and run those actions. That said, this isn't a feature that KIF directly enables itself.

My recommendation would generally be to implement a mock network layer within your app, and primarily run your functional tests against that. You can create mock network responses with a record/playback framework, or hand create your own logic to handle the requests and responses. It is far simpler to manage. Removing the variability of network requests from your tests will also likely lead to a significantly faster and more reliable test suite.

**Comment by bimawa** [comment]
Yes, you understood me correct! Thanks for answer!
