### ISSUE TITLE
[Question] Get full list of KIF test cases and include/exclude rules?

### ISSUE THREAD

**Issue by daniel-beard** [kif-framework/KIF#1229]
Hi, I'm using KIF for some tests in a monorepo where some modules use bare XCTest and some are using KIF.
These test suites have grown pretty huge, so for the bare XCTest modules, I've started using `xcodebuild`'s ability to only run an opt-in list of tests which gives me the ability to dynamically split our test suites across N build machines at build time.

I would like to use a similar approach for the KIF tests, but so far haven't been able to figure out a way to do this. Ideally, it would be something like:

```
- Introspect KIFs registered test cases at runtime (before running anything)
- Use custom split algorithm
- Set tests to run as an include list
- Run tests
```

Can anyone point me in the right direction here? I don't want to have to rewrite all these tests.

**Comment by daniel-beard** [comment]
After looking further, it appears we are using KIF+Quick. Maybe this question is more appropriate on the Quick repo.

**Comment by justinseanmartin** [comment]
KIF tests are still XCTests, so I'm unclear what the discrepancy preventing your existing tooling from working with those would be.

We open sourced https://github.com/square/xcknife, which can be used to enumerate tests and output that information. It also has a naive mode for doing it based off of `nm` (which can miss out on dynamic tests, but is way faster). It then balances the work across machines using historical timing data.

I don't think this is a question for KIF specifically though, as I don't think it is related to the library itself. For that reason, I'm going to close out the issue, but I'm happy to give more info in this thread if you'd like.
