### ISSUE TITLE
[UITouch setIsTap:]: unrecognized selector sent to instance on iOS 15

### ISSUE THREAD

**Issue by emanueluayza** [kif-framework/KIF#1233]
Hi there!

I was testing iOS 15 with Xcode 13.0 beta 4 and I saw multiple tests failures with this error:

`-[UITouch setIsTap:]: unrecognized selector sent to instance 0x7fce650c59a0 (NSInvalidArgumentException)`

<img width="622" alt="Screen Shot 2021-07-28 at 19 38 32" src="https://user-images.githubusercontent.com/9702833/127406160-0b9ae39a-e9d6-4192-bce0-0946aa86d403.png">

This happens when I call `clearTextFromAndThenEnterText`, `tapViewWithAccessibilityLabel` or `dragFromPoint`.

I played around a little bit with your code and I saw the error is under UITouch+KIFAdditions file, line 71:

`[self setIsTap:YES]; `

If I remove that line, the tests start working as they do on iOS 14. Could that change be included in a PR to avoid this issue on iOS 15?

**Comment by dostrander** [comment]
@emanueluayza Thanks for pointing this out and taking care of this, it was just merged

**Comment by PawelMichalak-TomTom** [comment]
Hi. Is there a plan to release this fix in new Cocoapods? I can't make a build with Xcode13 without it and iOS15 is just around the corner. 
Thx.

**Comment by dostrander** [comment]
Sorry about that. I will create a release today

**Comment by PawelMichalak-TomTom** [comment]
@dostrander Wow, that would be awesome. Thanks!

**Comment by dostrander** [comment]
Just published

**Comment by PawelMichalak-TomTom** [comment]
Excelent! I've already integrated and got it working with build. Thanks again @dostrander for a quick fix!
