### ISSUE TITLE
 It may be blocked by other views

### ISSUE THREAD

**Issue by nkusongzhichao** [kif-framework/KIF#1238]
When I use tapIfExistAccessibilityLabel, sometimes it may pop a view,  so I cant hit this button, and give this error ："xxxx is not tappable. It may be blocked by other views."  How can I solve this problem？

**Comment by dostrander** [comment]
Sorry i don't follow completely. Are you saying that if you hit `tap` it will do the tap then pop a view, which then will then cause an error saying it's untappable? 

Maybe an example project or code of what is happening would help illustrate what the problem is if that's possible

**Comment by dostrander** [comment]
@nkusongzhichao Any updates on this?
