### ISSUE TITLE
Xcode 13 - waitForView returns nil

### ISSUE THREAD

**Issue by alekkania** [kif-framework/KIF#1239]
I faced with issue in Xcode 13 that `waitForView` method returns nil for view with accessibilityIdentifier as well as accessbilityLabel. 
It is strange because sometimes it works if tests are started as whole class instead of single one. 

It mostly happen on UITable/CollectionView.

Anyone faced with this issue as well?

**Comment by dostrander** [comment]
@alekkania have you or anyone else seen this on CI or is this mostly only local?

**Comment by alekkania** [comment]
@dostrander Yes it happen on CI as well.

**Comment by dostrander** [comment]
Got it, let me look into this a bit

**Comment by dostrander** [comment]
@alekkania is this just return nil or is it also giving you an error in the test when calling `waitForView`?

Also if you have a repro project and/or code that'd be super helpful

**Comment by alekkania** [comment]
@dostrander It seems that default timeout is not enough. I've forked KIF repo and change waitForView timeout to 200 seconds. It solved the issue with single tests but run in group still fails - stuck on waiting for view and fail in the end.

**Comment by dostrander** [comment]
@alekkania  Would you be able to create a test to try to repro this in the KIF project and send over the branch? I am having trouble reproing it on my machine using beta 5

**Comment by dostrander** [comment]
@alekkania is it always tableviews or collection views? Does it sometimes happen on other views as well or is it pretty particular to those?

**Comment by alekkania** [comment]
@dostrander It works for us as well. Thank you!

**Comment by dostrander** [comment]
Fixed in https://github.com/kif-framework/KIF/pull/1241

**Comment by dostrander** [comment]
This has been released with 3.8.4
