### ISSUE TITLE
KIF types each character twice

### ISSUE THREAD

**Issue by pomozoff** [kif-framework/KIF#1254]
I use this method:
```objc
- (void)enterTextIntoCurrentFirstResponder:(NSString *)text
```

as following:
```swift
tester().enterText(intoCurrentFirstResponder: "41")
```

However, I see each character typed twice:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/839094/149127933-b58e3ab6-86fb-4ce3-8e0d-2d58df67d512.png">

It looks like the next code enters a character twice:
```objc
+ (BOOL)enterCharacter:(NSString *)characterString;
{
    if ([characterString isEqualToString:@"\b"]) {
        [[UIKeyboardImpl sharedInstance] deleteFromInput];
    } else {
        [[UIKeyboardImpl sharedInstance] addInputString:characterString]; // The char is entered 1st time
    }
    
    [[[UIKeyboardImpl sharedInstance] taskQueue] waitUntilAllTasksAreFinished]; // The char is entered 2nd time
    CFRunLoopRunInMode(kCFRunLoopDefaultMode, keystrokeDelay, false);
    return YES;
}
```

Is there any workaround to fix this issue?

**Comment by justinseanmartin** [comment]
We don't observe this behavior in our app or the integration tests in this repo. I'd recommend setting some breakpoints where the controls are updating their text and see if they're doing something unexpected. If you can narrow down the cause or provide a repro, we could help with more guidance. Without that information, there isn't much to go on here. You should be able to see from KIF's side that we only send each character as input to UIKeyboard a single time.
