### ISSUE TITLE
KIF-based UI tests crashes in Xcode 13.4

### ISSUE THREAD

**Issue by danielsaidi** [kif-framework/KIF#1263]
When running KIF-based UI tests in Xcode 13.4, KIF crashes with this error log:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/429927/172574128-dac7ca1f-eb8d-4ed5-bff8-39dd6e495701.png">

Setting up an `All Runtime Issues` breakpoint, we get this:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/429927/172574571-d382397e-8e3b-4209-bdfd-8f119c51b012.png">

This printout looks either promising or worrying:

```
2022-06-08 10:51:17.266222+0200 UITestHost[98549:949047] [general] NSPredicate: NSFunctionExpression with selector 'accessibilityIdentifier' is forbidden.
```

Any ideas what is causing this crash?

**Comment by danielsaidi** [comment]
When using `master`, we can confirm that this indeed fixes the problem:

https://github.com/kif-framework/KIF/pull/1261

A new patch release with this fix would be amazing.

**Comment by dostrander** [comment]
Yep should be fixed with this issue as well: https://github.com/kif-framework/KIF/issues/1260
