### ISSUE TITLE
Question: Does KIF require a mac?

### ISSUE THREAD

**Issue by meidlinga** [kif-framework/KIF#1264]
We are looking for a solution for automated UI Tests not requiring a mac. Would it be possible to use KIF to automate tap events without having a mac during test time. We are able to build apps.

I could not find this information in the documentation.

**Comment by dostrander** [comment]
KIF only works for Apple products, which require a mac or apple product to run. Is that what you are talking about or is there something else you are thinking?

**Comment by meidlinga** [comment]
Yes, this was my intention.
Since - if I unterstood the system correctly - KIF is compiled into the dev build of the actual app, I was hoping it could be triggered on the device, without having an external apple product connected during test/runtime

**Comment by dostrander** [comment]
That should work then, sorry it wasn't clear if you were talking about another machine type. It should work both on iPhone and iPad for sure

**Comment by meidlinga** [comment]
Thanks for the clarification. Sounds promising!

**Comment by justinseanmartin** [comment]
To clarify, KIF is compiled and linked into the test target and not the app being tested. There is no Apple supported way to run XCTest bundles on device without Xcode (which requires a mac). You could potentially build and link your tests, KIF and XCTest into your app, but you'd probably have to write your own test runner to find `XCTestCase` subclasses and call `invokeTest` on them sometime after app launch. This is outside the scope of KIF itself.
