### ISSUE TITLE
iOS 17 - Entering text using a KIFUITestActor into a text field is broken

### ISSUE THREAD

**Issue by adamsousa** [kif-framework/KIF#1285]
Tried out the new Xcode 15 Beta along with iOS 17 and noticing an issue with KIFUITestActor in our UI tests entering text into text fields. Seems to affect iOS 17 only. 

Saw this when using `testActor.clearText` and `testActor.enterText`

Usually the text entry cursor does select the text field, but nothing is typed and it times out.

**Comment by dostrander** [comment]
@adamsousa Oof okay, maybe `UIKeyboardImpl` has changed in iOS 17 and someone will have to take a look. Thanks for flagging

**Comment by adamsousa** [comment]
This issue does appear to be solved in the final release of Xcode 15, closing issue
