### ISSUE TITLE
[Requirement] Privacy manifest for new sensitive APIs

### ISSUE THREAD

**Issue by nabs-m** [kif-framework/KIF#1290]
Apple recently announced privacy manifests, along with a list of [sensitive APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) that require developers to provide reasons for them. Apple says devs have until spring 2024 to implement this.

I believe KIF uses both [systemUptime](https://developer.apple.com/documentation/foundation/nsprocessinfo/1414553-systemuptime?language=objc) and `mach_absolute_time()` from the [System boot time APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394) list.

Are you planning to include a privacy manifest describing this usage in a future release? This will be needed by every app consuming this library to satisfy the requirement by Apple.

**Comment by justinseanmartin** [comment]
KIF generally shouldn't be getting linked into shipping apps. It also uses private system APIs and has [in the past](https://github.com/joemasilotti/KIF/blob/b2a279133dabbdd77dbb72a7295cb277c2eeeb90/Classes/UIAutomationHelper.m#L63) relied on using `dlopen` to load some system frameworks. In general, for any apps that link and ship KIF as part of their release build, my recommendation would be to configure it as a debug config only dependency. I'm definitely open to feedback if there are reasons folks might be shipping KIF with their apps though, which would necessitate doing this work.

**Comment by nabs-m** [comment]
This makes sense given that this is a testing framework and doesn't need to be reference in release builds 👍 Will close this issue.
