### ISSUE TITLE
Black screenshots on test failures on ios 17.

### ISSUE THREAD

**Issue by Srijan1998** [kif-framework/KIF#1293]
We are seeing black screenshots on test failures when tests are run on ios 17 on the latest version 3.8.9. I can see the issue was already fixed sometime back with the commit 62fcb3847bf74bb3d6898dc3bfbe06adbf13ebb0. Is there a plan to release a new version soon?

**Comment by justinseanmartin** [comment]
Can you point at the master SHA and make sure it fixes the issue for you? If it does, I can cut a bugfix release, sure.

**Comment by Srijan1998** [comment]
This is the commit 62fcb3847bf74bb3d6898dc3bfbe06adbf13ebb0. Yes it does fix our issue I made the change in my local pod and checked.

**Comment by justinseanmartin** [comment]
I've bumped the podspec to 3.9.0, pushed a v3.9.0 tag, and created a release for it. I think this should be sufficient if you're consuming this via SPM. If you're consuming via CocoaPods, I'm still working on publishing that, as I'm having some issues registering a new CocoaPods trunk session on my new laptop.

**Comment by Srijan1998** [comment]
Hey I see there is a mismatch between the podspec pushed and the version tagged!

**Comment by justinseanmartin** [comment]
Fixed that. I was able to get a CocoaPods trunk session validated this morning, so I just published `v3.9.0`. Hope this helps.
