### ISSUE TITLE
unable to tap or find views when using MFMailComposeViewController

### ISSUE THREAD

**Issue by davidsmilebox** [kif-framework/KIF#157]
there is a portion of our app which we want to test that launch's apples email controller MFMailComposeViewController (standard interface that manages the editing and sending an email message). However after the app presents this controller modally, any further steps we do fail because they appear to be unable to find a label (trying to tap cancel, send, "to:" field, etc ). We also tried using a screen location but the controller does not seem to respond to this either.

Do you have any suggestions for addressing this case? Do you expect the framework to be able to support this case?

**Comment by tempire** [comment]
Use the accessibility inspector, you'll see that the Cancel button has a "Cancel" label, the Subject line has a "Subject:" label, etc.
