### ISSUE TITLE
Send App to Background

### ISSUE THREAD

**Issue by trandoanhung1991** [kif-framework/KIF#183]
Hi, currently does KIF support sending app to background yet?

It seems Apple has included some hidden API for sending the app to the background and back, as it is possible with UIAutomation. However, so far I've not seen any indication of being able to do this anywhere else.

A critical part of our app has to do with the ability to gracefully transition between background/foreground states. Not being able to test for this just makes me worried, especially as more features are added to the app.

**Comment by pres** [comment]
If the App you want to test supports an URL-Scheme you can suspend and relaunch it with:

`[[UIApplication sharedApplication] suspend];`
`[tester waitForTimeInterval:1];`
`[[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"url-scheme://open"]];`
