### ISSUE TITLE
Possible to load GPX file programmatically to simulate location from kif step?

### ISSUE THREAD

**Issue by foxyblocks** [kif-framework/KIF#208]
Does anyone know if it would be possible programmatically load a GPX file to simulate CoreLocation from a kif step. This would be helpful for setting up location based tests.

**Comment by maciekish** [comment]
@puls Actually this isn't covered by Xcode. You can chose a default GPX file for *running* the app. But if you chose `Test` instead the `Options` tab disappears (which is where you enable location simulation).
