### ISSUE TITLE
Keyboard-related tests can fail when Simulator is using "Simulate Hardware Keyboard" option

### ISSUE THREAD

**Issue by phatmann** [kif-framework/KIF#291]
If you have selected the "Simulate Hardware Keyboard" option in the Simulator, then any tests that require typing will fail because the on-screen keyboard will not appear. There are two possible fixes for this:
1. Force this option off before running the simulator. Not sure if this is possible.
2. Detect that on-screen keyboard is not showing, and use setText to enter characters. Would be good to log a warning message also.

**Comment by ohenak** [comment]
I would still want to explore the option 1 @phatmann mentioned. My team is running into an issue that search is triggered by the 'Done' button, in other words, if the keyboard is hidden, the search test on our app will always fail. I think similar scenario may be very often.

(Although I don't think it is a good modern UI experience...anyway)

**Comment by phatmann** [comment]
@ohenak I would be glad to look at any pull request you make to fix this issue.

**Comment by amol-c** [comment]
:+1: @ohenak .. Same issue here.

**Comment by justinseanmartin** [comment]
The feature idea for forcing the keyboard off is now tracked as #1078
