### ISSUE TITLE
enterText:intoViewWithAccessibilityLabel: enters incorrect case character?

### ISSUE THREAD

**Issue by rdougan** [kif-framework/KIF#323]
When running `enterText:intoViewWithAccessibilityLabel:`, the case of the entered string is sometimes incorrect.

The error I get is:

```
/.../KIFUITestActor+LoginAdditions.m:27: error: -[LoginTest testIncorrectPIN4LengthShouldShowError] : The step timed out after 1.00 seconds: Failed to get text "LnZTwhpB9d" in field; instead, it was "LnZtwhpB9d"
```

I've noticed this problem a few times locally, but after setting up xcodebuild to run the tests on a TeamCity server, this happens almost every time.

Perhaps a timing problem; not hitting the shift key before entering the character? 

Is there a way to slow down character input?

Thanks!!

**Comment by moger777** [comment]
I've recently had the issue where the capitalization auto correct breaks this method.
