### ISSUE TITLE
Dismiss Alertview That is Not Part of the Key Window iOS7

### ISSUE THREAD

**Issue by johnryan** [kif-framework/KIF#345]
My application requires contact access, so I would like to dismiss the alert view that shows when you request contact permission. I have tried finding the view in the window and tapping the screen at the correct point but neither seem to dismiss the alert. I'm not sure if apple provides a way of dismissing this type of system alert.

**Comment by Benuuu** [comment]
I stumbled across this and the plist workaround posted above didn't work for me.  Instead I used the changes introduced in https://github.com/kif-framework/KIF/pull/510

`- (void)acknowledgeSystemAlert;`

**Comment by johnryan** [comment]
Interesting, thanks for the heads up @Benuuu
