### ISSUE TITLE
swipe on UISwitch does not toggle it (ios 7.0 and 7.1)

### ISSUE THREAD

**Issue by MarvinMueller** [kif-framework/KIF#352]
Since ios 7.0 swipe via swipeViewWithAccesibilityLabel on UISwitches is not working correctly. 

Swiping to the right leads sometimes to the same as swiping to the left or nothing. At this moment you cannot toggle the state of a UISwitch with swiping on it. This was working in older ios versions.

This method is still working using on other component (like UIButton) and gesture recognizer but not for UISwitch. 

Regards,
Marvin Mueller

**Comment by mokagio** [comment]
@MarvinMueller this is an old issue, but anyway you can toggle switches using `[tester setOn:switchIsOn forSwitchWithAccessibilityLabel:label];`
