### ISSUE TITLE
XCTestCase-KIFAdditions.h file not found

### ISSUE THREAD

**Issue by valeriomazzeo** [kif-framework/KIF#359]
Looks like that file doesn't get copied into the header folder together with the others file.

../Build/Products/Debug-iphonesimulator/include/KIF/KIFTestCase.h:17:9: 'XCTestCase-KIFAdditions.h' file not found

**Comment by APonomarev2301** [comment]
Hi, I have a problem with integration a KIF into my project. I install that by cocoapods, but have error (#import "XCTestCase-KIFAdditions.h" file not found) in "KIFTestCase.h" file. I using XCode 6.3.2. Is any one can help me?

**Comment by phatmann** [comment]
@APonomarev2301 The comments in this thread are not helpful?
