### ISSUE TITLE
KIF breaks app with failure on beforeAll

### ISSUE THREAD

**Issue by flavianmissi** [kif-framework/KIF#361]
I'm not sure if this behavior is expected, it would be great if anyone could clarify.

I have two test cases which inherit from `KIFTestCase` and I'm using XCTest.
Both my test cases expect the login screen of my application and they both try to skip the login.

I know it's incorrect because just one of them is going to have the login page on screen, the problem is that when the second test case runs my app crashes with a SIGABRT.

I checked the code and the problem is in this line https://github.com/kif-framework/KIF/blob/master/Additions/XCTestCase-KIFAdditions.m#L23

I think it should stop only the current test, not kill the app without any message. Am I right?

Thanks.

**Comment by gudatcomputers** [comment]
I would recommend that the test fail.  The current implementation presents issues when using KIF with a continuous integration build.  If the beforeall fails, the exit code should be non-zero to indicate a failure with the tests.  With the current implementation, the exit code is still 0 in the event of a beforeall failure, and a failing test will be identified as successful ("Executed 0 tests with 1 failure" == exit code of 0, which is not good).

**Comment by XianPalin** [comment]
I would recommend that the test fail. The current implementation presents issues when using KIF with a continuous integration build. If the beforeall fails, the exit code should be non-zero to indicate a failure with the tests. With the current implementation, the exit code is still 0 in the event of a beforeall failure, and a failing test will be identified as successful ("Executed 0 tests with 1 failure" == exit code of 0, which is not good).

**Comment by phatmann** [comment]
@XianPalin if you can figure out a way to preserve the current behavior yet return a non-zero exit code, let me know.
