### ISSUE TITLE
Unable to tap UICollectionView item

### ISSUE THREAD

**Issue by grosch** [kif-framework/KIF#382]
I'm using KIF 3.0.3 and trying to test a UICollectionView.  I used this test method:

```
- (void)testFoo {
    UICollectionView *cv = (UICollectionView *) [tester waitForViewWithAccessibilityLabel:@"MonthCollectionView"];
    NSIndexPath *indexPath = [NSIndexPath indexPathForItem:23 inSection:0];

    NSLog(@"\nCollection View: %@\nDelegate: %@", cv, cv.delegate);

    [cv.delegate collectionView:cv didSelectItemAtIndexPath:indexPath];
    NSLog(@"Tapped the item");

    [tester tapItemAtIndexPath:indexPath inCollectionViewWithAccessibilityIdentifier:@"MonthCollectionView"];
}
```

When the test runs I see the first NSLog print out a UICollectionView object and the expected delegate class.  That means I'm definitely finding the accessibility label.

Then the last line runs where I try to use the tester method to tap the index path.  After 10 seconds I get an exception:

error: -[UITests testFoo] : The step timed out after 10.00 seconds: Could not find view matching: accessibilityIdentifier == "MonthCollectionView"

**Comment by Morkrom** [comment]
Hah... can't believe I had to come here to catch that.
