### ISSUE TITLE
Use in OS X

### ISSUE THREAD

**Issue by arbarlow** [kif-framework/KIF#397]
I'm sure someone has probably brought this up before but has there been any thought of effort into allowing this to work with OS X?

I'd be happy to help with any work required..

**Comment by vasarhelyia** [comment]
+1

**Comment by aboyd** [comment]
+1 I would be happy to help with this. Anyone have any ideas where to start? I have used Frank before, but haven't done any development for it.

**Comment by billburgess** [comment]
+1
