### ISSUE TITLE
On Test Failure, an exception is thrown which doesn't get caught

### ISSUE THREAD

**Issue by couchdeveloper** [kif-framework/KIF#401]
It appears to me KIF behaves quite strange when a test fails:

I installed KIF via CocoaPods:

```
target 'Acceptance Tests', :exclusive => true do
    pod 'KIF', '~> 3.0'
end
```

which built smoothly.

My first attempt to use KIF is in this test:

```
- (void)testOneRegulationShouldBeSelected
{
    UITableView* tableView = (UITableView *)[tester waitForViewWithAccessibilityLabel:@"Regulation List"];

//    [tester tapRowInTableViewWithAccessibilityLabel:@"Regulation List"
//                                        atIndexPath:[NSIndexPath indexPathForRow:0 inSection:0]];

    [tester waitForViewWithAccessibilityLabel:@"Checkmark" traits:UIAccessibilityTraitSelected];    
}
```

Since there was no row selected in the table view, the test should fail. I would expect a brief failure description printed to the console and some visual representation in Xcode's test navigator. That's not the case, though:

Indeed, it fails after a timeout expired, but with throwing an exception which prints the call stack to the console:

> Acceptance Tests/StartupTests.m:37: error: -[StartupTests testOneRegulationShouldBeSelected] : The step timed out after 10.00 seconds: Failed to find accessibility element with the label "Checkmark"
> <unknown>:0: error: -[StartupTests testOneRegulationShouldBeSelected] : The step timed out after 10.00 seconds: Failed to find accessibility element with the label "Checkmark"
> (
>     0   CoreFoundation                      0x019661e4 **exceptionPreprocess + 180
>     1   libobjc.A.dylib                     0x016e58e5 objc_exception_throw + 44
>     2   CoreFoundation                      0x019f5fe1 -[NSException raise] + 17
>     3   Acceptance Tests                    0x08bcc4ff -[XCTestCase(KIFAdditions) failWithException:stopTest:] + 479
>     4   Acceptance Tests                    0x08bb32fa -[KIFTestCase failWithException:stopTest:] + 506
>     5   Acceptance Tests                    0x08bb262b -[KIFTestActor failWithError:stopTest:] + 299
>     6   Acceptance Tests                    0x08bb2046 -[KIFTestActor runBlock:complete:timeout:] + 758
>     7   Acceptance Tests                    0x08bb21a2 -[KIFTestActor runBlock:complete:] + 194
>     8   Acceptance Tests                    0x08bb22fc -[KIFTestActor runBlock:] + 108
>     9   Acceptance Tests                    0x08bb5d16 -[KIFUITestActor waitForAccessibilityElement:view:withLabel:value:traits:tappable:] + 374
>     10  Acceptance Tests                    0x08bb5b0d -[KIFUITestActor waitForViewWithAccessibilityLabel:value:traits:tappable:] + 253
>     11  Acceptance Tests                    0x08bb5619 -[KIFUITestActor waitForViewWithAccessibilityLabel:traits:] + 137
>     12  Acceptance Tests                    0x08bafe0d -[StartupTests testOneRegulationShouldBeSelected] + 685
>     13  CoreFoundation                      0x0195a91d __invoking_** + 29
>     14  CoreFoundation                      0x0195a82a -[NSInvocation invoke] + 362
>     15  XCTest                              0x20103c6c -[XCTestCase invokeTest] + 221
>     16  XCTest                              0x20103d7b -[XCTestCase performTest:] + 111
>     17  XCTest                              0x20104c48 -[XCTest run] + 82
>     18  XCTest                              0x201033e8 -[XCTestSuite performTest:] + 139
>     19  XCTest                              0x20104c48 -[XCTest run] + 82
>     20  XCTest                              0x201033e8 -[XCTestSuite performTest:] + 139
>     21  XCTest                              0x20104c48 -[XCTest run] + 82
>     22  XCTest                              0x201033e8 -[XCTestSuite performTest:] + 139
>     23  XCTest                              0x20104c48 -[XCTest run] + 82
>     24  XCTest                              0x201066ba +[XCTestProbe runTests:] + 183
>     25  Foundation                          0x0131b5ec **NSFireDelayedPerform + 372
>     26  CoreFoundation                      0x01924ac6 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 22
>     27  CoreFoundation                      0x019244ad __CFRunLoopDoTimer + 1181
>     28  CoreFoundation                      0x0190c538 __CFRunLoopRun + 1816
>     29  CoreFoundation                      0x0190b9d3 CFRunLoopRunSpecific + 467
>     30  CoreFoundation                      0x0190b7eb CFRunLoopRunInMode + 123
>     31  GraphicsServices                    0x039465ee GSEventRunModal + 192
>     32  GraphicsServices                    0x0394642b GSEventRun + 104
>     33  UIKit                               0x003a5f9b UIApplicationMain + 1225
>     34  Lexica                              0x0001584d main + 157
>     35  libdyld.dylib                       0x02102701 start + 1
> )

The XCTest case manages to proceed somehow, and logs this to the console:

> Test Case '-[StartupTests testOneRegulationShouldBeSelected]' failed (139.273 seconds).
> Test Suite 'StartupTests' finished at 2014-05-26 12:54:31 +0000.
> Executed 1 test, with 2 failures (2 unexpected) in 139.273 (139.323) seconds
> Test Suite 'Acceptance Tests.xctest' finished at 2014-05-26 12:54:31 +0000.
> Executed 1 test, with 2 failures (2 unexpected) in 139.273 (139.323) seconds
> Test Suite 'All tests' finished at 2014-05-26 12:54:31 +0000.
> Executed 1 test, with 2 failures (2 unexpected) in 139.273 (139.324) seconds

Xcode's test navigator shows _two_ failing tests: 

> file:///Users/me/Projects/MyProject/Acceptance%20Tests/StartupTests.m: test failure: -[StartupTests testOneRegulationShouldBeSelected] failed: The step timed out after 10.00 seconds: Failed to find accessibility element with the label "Checkmark"

and this one too:

>  <unknown>
> file:///%3Cunknown%3E: test failure: -[StartupTests testOneRegulationShouldBeSelected] failed: The step timed out after 10.00 seconds: Failed to find accessibility element with the label "Checkmark"

Furthermore, while the test waits for the view to appear, a lot of memory gets allocated (several MBytes). I didn't investigate where this comes from, and whether this is a autorelease pool issue or a leak.

I also get this strange error message in the console when KIF starts up:

> Cannot find executable for CFBundle 0xa86c520 </Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/System/Library/AccessibilityBundles/CertUIFramework.axbundle> (not loaded)

None of the suggested workarounds did actually work.

It seems to me, I'm doing something fundamentally wrong ;)

**Comment by onekiloparsec** [comment]
Is this issue closed? I am still observing in a non-deterministic way the message "The step timed out after 10.00 seconds: Failed to find accessibility element with the label ..." with Xcode 6.4, KIF 3.2.(1-3)

**Comment by phatmann** [comment]
@onekiloparsec Are you seeing the whole ugly call stack too?

**Comment by iMaximus** [comment]
We have this problem to. (xcode 7.1 KIF 3.3).  If test failed, messages appear in the log twice

/Volumes/jenkins_ssd/workspace/...:694: error: -[test class and test case  name] : The step timed out after 20.00 seconds: View is not tappable
/Volumes/jenkins_ssd/workspace/...:694: error: -[ttest class and test case  name] : The step timed out after 20.00 seconds: View is not tappable
/Volumes/jenkins_ssd/workspace/...m:715: error: -[test class and test case  name] : Failure in child step: The step timed out after 20.00 seconds: View is not tappable
Test Case '-[test class and test case  name]' failed (68.548 seconds)

**Comment by phatmann** [comment]
@iMaximus: does this only happen in Jenkins?

**Comment by iMaximus** [comment]
not, if i run by terminal xcodebuild, failure message twice to.
Problem in line [tester failWithException:exception stopTest:NO];  
If I comment out this line, all statistics shown correctly.
> @catch (NSException *exception)
   {
        [tester backToLogin];
        [tester failWithException:exception stopTest:NO];
   }

**Comment by phatmann** [comment]
Why are you calling `failWithException`?

**Comment by dolphinSuPixnet** [comment]
I have same issue in Jenkins. I also found one thing. I can't launch Accessibility Inspector in iPhone Simulator in the mac mini that running Jenkins. 
[Video record](https://www.youtube.com/watch?v=J997yGwrmZM)

**Comment by mikelupo** [comment]
@dolphinSuPixnet In regards to your post regarding the Accessibility Inspector. 
1) You may need to reset the simulator. With the simulator running, go to the menu at the top of your Mac's screen. Choose the following menu pick. ```Simulator > Reset content and settings```
2) When I have weird simulator behavior I will often go into the disk utility and repair my disk permissions. Strange idea I know, but usually one or the other or the combination usually fixes my simulator.
in OSX < 10.11 you can just do it from Disk Utility. Beginning with El Capitan (OSX 10.11) you must do it on the command line. http://osxdaily.com/2015/11/04/verify-repair-permissions-mac-os-x/

On the off chance that someone lands on this post via search and is having the problem on the actual phone (as I have had as well) 
I just used the toggle from within Itunes. http://www.tekrevue.com/tip/enable-ios-accessibility-options-itunes/
Hope this helps

**Comment by dolphinSuPixnet** [comment]
Thank you, @mikelupo , I tried them. Both are not working. T_T

**Comment by hamaianhnhi** [comment]
Hello guys, any updates on this? I"m still seeing the whole ugly fail log.

**Comment by phatmann** [comment]
@hamaianhnhi Sorry, no updates. Feel free to solve this one for us 😜
