### ISSUE TITLE
KIF with SpriteKit

### ISSUE THREAD

**Issue by dbirchfield** [kif-framework/KIF#411]
It looks like it is possible to add accessibility labels to nodes in SpriteKit. However, is there a means to reference these with KIF? In my initial testing, it doesn't appear that tapViewWithAccessibilityLabel can access SKSpriteNodes in my scene.

**Comment by hiiwave** [comment]
Hello @phatmann,

Based on [this anwser](https://stackoverflow.com/questions/34293575/is-it-possible-to-use-xcode-ui-testing-on-an-app-using-spritekit/42676977#42676977) on Stackoverflow, it seems that this issue is possible! Do you have any plan to integrate this? 😄

**Comment by justinseanmartin** [comment]
@hiiwave - Couple of questions:

* Do you have a sample project where this is not working for investigation? 
* If you run `po [UIView printViewHierarchy]` in the LLDB console, does it not contain the sprite elements as accessibility elements?
* Can your app generally be navigated with VoiceOver enabled and the elements you're looking for be identified by the labels that you're using in the tests?

**Comment by hiiwave** [comment]
Hi, I've confirmed this trick works by creating an [example project](https://github.com/hiiwave/SpritekitUITestingExample)! This example app shows how to navigate SpriteKit scenes by KIF.

There is a small issue that `[UIView printViewHierarchy]` does not contain the sprite elements as accessibility elements in my example app, but the ui test still works.

While this trick works, I wonder do you have any plan to make it easier for programmers to use KIF under SpriteKit framework? I believe with some design the integration between KIF and SpriteKit could be more natural and better 😄

**Comment by justinseanmartin** [comment]
I don't think it would be an appropriate addition for the KIF framework itself. KIF is written to work via the accessibility framework, but it is outside of the framework's responsibility to have your app expose itself to accessibility. 

I think the solution you have for specific elements to expose themselves via accessibility as buttons technically works. I'd be curious how that would work for a sight impaired user. You could try it with VoiceOver.
