### ISSUE TITLE
"Scroll the view (and superviews) to be visible if necessary" scrolls an unnecessary scrollview

### ISSUE THREAD

**Issue by CsabaSzabo** [kif-framework/KIF#491]
Hi,

I have a scrollview which contains many other views. I want to tap on a view on this scrollview which is totally visible, but in the [UIAccessibilityElement-KIFAdditions.m](https://github.com/kif-framework/KIF/blob/master/Additions/UIAccessibilityElement-KIFAdditions.m) from line 121 it scrolls the superview:

```
// Scroll the view (and superviews) to be visible if necessary
UIView *superview = (UIScrollView *)view;
while (superview) {
    // Fix for iOS7 table view cells containing scroll views
    if ([superview.superview isKindOfClass:[UITableViewCell class]]) {
        break;
    }

    if ([superview isKindOfClass:[UIScrollView class]]) {
        UIScrollView *scrollView = (UIScrollView *)superview;

        if ((UIAccessibilityElement *)view == element) {
            [scrollView scrollViewToVisible:view animated:YES];
        } else {
            CGRect elementFrame = [view.window convertRect:element.accessibilityFrame toView:scrollView];
            [scrollView scrollRectToVisible:elementFrame animated:YES];
        }

        // Give the scroll view a small amount of time to perform the scroll.
        CFRunLoopRunInMode(kCFRunLoopDefaultMode, 0.3, false);
    }

    superview = superview.superview;
}
```

**My problem:** I just want to tap on an element on this scrollview, but the KIF scrolls the superview scrollview, which cause UI issue in the app during UI testing. Why is this necessary?

**Workaround**: I've just uncommented the superview scrolling to the actual view, which is working, but I know that it removes a good functionality. Would it be possible to scroll the superview only if the actual view is not visible?

```
// Scroll the view (and superviews) to be visible if necessary
UIView *superview = (UIScrollView *)view;
while (superview) {
    // Fix for iOS7 table view cells containing scroll views
    if ([superview.superview isKindOfClass:[UITableViewCell class]]) {
        break;
    }

    if ([superview isKindOfClass:[UIScrollView class]]) {
        UIScrollView *scrollView = (UIScrollView *)superview;

        if ((UIAccessibilityElement *)view == element) {
            // WORKAROUND: Uncomment to not scroll the superview
            //[scrollView scrollViewToVisible:view animated:YES];
        } else {
            CGRect elementFrame = [view.window convertRect:element.accessibilityFrame toView:scrollView];
            [scrollView scrollRectToVisible:elementFrame animated:YES];
        }

        // Give the scroll view a small amount of time to perform the scroll.
        CFRunLoopRunInMode(kCFRunLoopDefaultMode, 0.3, false);
    }

    superview = superview.superview;
}
```

Thanks,
Csaba

**Comment by justinseanmartin** [comment]
I actually attempted to do the solution proposed in the original in this commit with `if (!view.isVisibleInWindowFrame)`:
https://github.com/kif-framework/KIF/commit/d006865ef81b09e246a8dfe69254ea8235695084#diff-566e05ba4bd3dbb38b960804e911a25a

However, it appears to have caused problems which required another approach on fixing this. See #1064 for more details. I'm going to close this issue for now and we can track issues with the existing implementation in #1067.
