### ISSUE TITLE
 KIF can’t click the butons of UIAlertView

### ISSUE THREAD

**Issue by voronesh** [kif-framework/KIF#498]
I use KIF in our project for automated test,and it can be run without any problem when I use the IOS 7 simulator, but now I need to test my project in IOS8 environment ,I notice that KIF can’t click the button of UIAlertView, and the test process will be stuck.

( [tester tapViewWithAccessibilityLabel:@"OK"]; The Step timed out after 10.00 seconds Failed to find accessiblility element with the label "OK") 

could you please give me some advice about this issue.

**Comment by jmig** [comment]
You definitely want to have a look at https://github.com/kif-framework/KIF/pull/510

`[tester acknowledgeSystemAlert];`

**Comment by phatmann** [comment]
Closing due to lack of response.
