### ISSUE TITLE
Unable to present UIActivityViewController view using KIF

### ISSUE THREAD

**Issue by SpringAutumn** [kif-framework/KIF#503]
Cause a EXC_BAD_ACCESS error.

**Comment by ohwutup** [comment]
any update on this? having the same `EXC_BAD_ACCESS` error as @SpringAutumn.

**Comment by ohwutup** [comment]
this line crashes on device: https://github.com/kif-framework/KIF/blob/a57ee3519585c94cc97bfdd9446e9eee84835a3c/Test%20Host/TestSuiteViewController.m#L44

**Comment by phatmann** [comment]
Dup of #574.
