### ISSUE TITLE
Testing URLs and push notifications

### ISSUE THREAD

**Issue by psugihara** [kif-framework/KIF#505]
Hi, I was wondering if you had a recommendation for testing the deep linking and push notifs?

In particular, I want to integration test

`- (void)application:(UIApplication*)application didReceiveRemoteNotification:(NSDictionary*)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))handler`

and 

`- (BOOL)application:(UIApplication*)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation`

**Comment by albertbori** [comment]
I'm interested in this as well. Although, I've found a workaround in the meantime, and that is to extract the functionality of those method handlers to an accessible location to the KIF test cases.

**Comment by phatmann** [comment]
@psugihara, what do you want to test?

**Comment by dylangattey** [comment]
Any updates on this? Can you test PN with KIF?

**Comment by phatmann** [comment]
No updates. The best approach is still probably to simulate a notification or deep link.
