### ISSUE TITLE
Acknowledging system alerts issues

### ISSUE THREAD

**Issue by joemasilotti** [kif-framework/KIF#512]
Some minor things that still could be improved upon PR #510:
- [ ] Running `-linkAutomationFramework` via `KIFTestActor`'s `-runBlock:complete:timeout:`
- [x] Not failing if the alert never shows up - PR #513 
- [ ] Waiting for the alert to dismiss via `KIFTestActor`'s `-runBlock:complete:timeout:`
- [x] Do not start automation server when running on the device.

**Comment by zaxy78** [comment]
is this open for a reason :) ?

**Comment by phatmann** [comment]
@zaxy78 The first item on the todo list ("Running...") is not done. At least it is not checked off...

@joemasilotti Should we close this ticket and make a new one for the open todo?
