### ISSUE TITLE
Memory issues when using KIF

### ISSUE THREAD

**Issue by ivan-golub** [kif-framework/KIF#515]
Looks like KIF doesnt release memory. App that Im developing use max 70-80 MB, but when Im running automated tests with KIF, memory usage is more than 300MB, which is causing app to crash in tests. I can attach only screens from profiler, because app info is confidential. From screens you can see that most of memory problems are caused by KIF methods. Is there a way to fix this?
![screen shot 2014-12-04 at 13 50 23](https://cloud.githubusercontent.com/assets/1858309/5297927/7fb0458e-7bbd-11e4-9c02-c6260f4bb486.png)
![screen shot 2014-12-04 at 13 50 51](https://cloud.githubusercontent.com/assets/1858309/5297931/91ad291e-7bbd-11e4-8107-f488cde4e6dc.png)
![screen shot 2014-12-04 at 13 46 44](https://cloud.githubusercontent.com/assets/1858309/5297882/f15a9348-7bbc-11e4-8429-4e470d0557cd.png)
![screen shot 2014-12-04 at 13 48 23](https://cloud.githubusercontent.com/assets/1858309/5297903/2834d3c4-7bbd-11e4-9243-2a8697739175.png)
![screen shot 2014-12-04 at 13 49 56](https://cloud.githubusercontent.com/assets/1858309/5297915/4d2a3e12-7bbd-11e4-9f12-09dd7e8212ae.png)
![screen shot 2014-12-04 at 13 45 28](https://cloud.githubusercontent.com/assets/1858309/5297858/a5e34fcc-7bbc-11e4-9a71-5fce16173dac.png)

**Comment by benasher44** [comment]
We're now having a similar issue where certain view controllers leak when created in the test environment, but I've confirmed that they don't leak when running the app normally. It appears that the associated memory sticks around for the duration of the test case, but the memory does get cleared when a new test case starts (i.e. memory sticks around across test methods). I've tried commenting out all kinds of swizzling and XCTestCase method overriding that KIF does with no clear indication of a culprit. I will admit that I have not confirmed yet that this is just XCTest itself.

In attempting to get memory in our tests under control, I did find/fix #760, but this didn't seem to have any affect on the overall issue (was hoping that these objects leaking might be holding on to views/vcs and therefore leaking those objects as well).

Has there been any more progress/findings on this front?

**Comment by phatmann** [comment]
No recent progress on the memory issues, sorry.

**Comment by benasher44** [comment]
@phatmann these issues have been fixed for me in Xcode 7.3. @ivangolub can you confirm this as well?

**Comment by phatmann** [comment]
Sounds amazing! Would love to get this one behind us.

**Comment by AncAinu** [comment]
On my side I got memory leak (and retain cycle) subsequent to the use of try/catch by trying to find some views.
It for instance, created a retain cycle on some `UIAlertController`.

**Comment by ivan-golub** [comment]
This issue is super old, Im not experiencing such problems anymore, so I think its fair to close this general ticket and track separate/concrete leaks issues if needed. Thx to all!
