### ISSUE TITLE
Linking UI Automation framework fails on device running iOS 8

### ISSUE THREAD

**Issue by TBonnin** [kif-framework/KIF#518]
Linking the [UI Automation private framework](https://github.com/kif-framework/KIF/blob/master/Classes/UIAutomationHelper.m#L53) fails on iOS 8 when run on a physical device. 
The following exception happens when [trying to access the target](https://github.com/kif-framework/KIF/blob/master/Classes/UIAutomationHelper.m#L60) :
`UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.`

Enabling UI Automation in the device settings ('Settings > Developer > Enable UI Automation') does NOT fix the issue. 
Tested on iPhone 6 with iOS 8.1 and iPod with iOS 8.0

I tested on an iPad with iOS 7.1 and it works without any issue. This seems to be a bug in iOS 8. Can anyone confirm? /cc @joemasilotti

**Comment by phatmann** [comment]
I am reopening this because @mikelupo is still seeing this issue.@mikelupo please add any details that will help us to reproduce this. Thanks.

**Comment by mikelupo** [comment]
TO REPRODUCE
note:  The bug does not occur on the simulator.

1) Clone:  git@github.com:mikelupo/KIF.git
2) Change to branch: reproduce_518
3) Load the KIF.xcodeproj into XCode 6.4
4) Connect up your iOS device. (This was reproduced on a REAL iPhone 5s.).
5) In XCode test navigator, select the BackgroundTests suite of tests and run them.
6) The Test Host app will load on the device under test and the test will begin.
7) The test will not deactivate the app, whilst in the console log the message can be seen (hundreds of times): **"Test Host[1179:178394] UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings."**

**Comment by tonylab** [comment]
Good afternoon all having the same issue here, UI animation set enabled on device iPhone 5 running on 9.93 OS.

Cucumber build works on simulator but connecting to the device it loads half way then repeats the same thing without actually, automating the next step....

Any answers

-bash: instrument: command not found
Tony-Momohs-MacBook-Pro:TMSample tony.momoh$ RESET_BETWEEN_SCENARIOS=1 DEVICE_ENDPOINT=http://10.0.71.71 DEVICE_TARGET=57981b2a4b7366ee107182bbd8723d058647065b BUNDLE_ID=com.sample.TestmunkDemo-copy APP_BUNDLE_PATH="/Library/Developer/Xcode/DerivedData/Products/Debug-iphoneos/TestmunkDemo-tm.app" bundler exec cucumber -v
Code:
  * features/support/env.rb
  * features/support/01_launch.rb
  * features/support/02_pre_stop_hooks.rb
  * features/step_definitions/calabash_steps.rb
  * features/step_definitions/my_first_steps.rb
  * features/step_definitions/testmunk/alert.rb
  * features/step_definitions/testmunk/api_count_items.rb
  * features/step_definitions/testmunk/date_picker_mars.rb
  * features/step_definitions/testmunk/first_screen.rb
  * features/step_definitions/testmunk/keyboard.rb
  * features/step_definitions/testmunk/location.rb
  * features/step_definitions/testmunk/long_press_ios6_iphone.base64
  * features/step_definitions/testmunk/playback.rb
  * features/step_definitions/testmunk/scroll_to_x.rb
  * features/step_definitions/testmunk/search.rb
  * features/step_definitions/testmunk/switch.rb
  * features/step_definitions/testmunk/tableview.rb
  * features/step_definitions/testmunk/wait_helpers_internal.rb
  * features/step_definitions/testmunk/webview.rb

Features:
  * features/my_first.feature

Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

WARN: 
Calabash::Cucumber::Launcher #calabash_no_launch? and support for the NO_LAUNCH
environment variable has been removed from Calabash.  This always returns
true.  Please remove this method call from your hooks.

  Scenario: Login                                        # features/my_first.feature:6
  Calabash::Cucumber::LaunchError: 
  
  "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
  
  Logfile: /Users/tony.momoh/.run-loop/results/2016-07-28_16-24-45/run_loop.out
  
          2016-07-28 16:24:48.042 instruments[12931:161018] WebKit Threading Violation - initial use of WebKit from a secondary thread.
  Instruments Trace Error : Target failed to run: Connection to the device lost while launching target.
  
  
           (Calabash::Cucumber::LaunchError)
  ./features/support/01_launch.rb:29:in `Before'
    Given I am on the Welcome Screen                     # features/step_definitions/my_first_steps.rb:1
    Then I touch the "Email" input field                 # calabash-cucumber-0.19.2/features/step_definitions/calabash_steps.rb:42
    Then I use the keyboard and type "test@testname.com" # features/step_definitions/testmunk/keyboard.rb:1
    Then I touch the "Password" input field              # calabash-cucumber-0.19.2/features/step_definitions/calabash_steps.rb:42
    Then I use the keyboard and type "testmunk"          # features/step_definitions/testmunk/keyboard.rb:1
    Then I touch "SIGN IN"                               # calabash-cucumber-0.19.2/features/step_definitions/calabash_steps.rb:14
    Then I wait                                          # calabash-cucumber-0.19.2/features/step_definitions/calabash_steps.rb:190
    Then I should see "Hello world"                      # calabash-cucumber-0.19.2/features/step_definitions/calabash_steps.rb:313
Retrying.. HTTPClient::ConnectTimeoutError: (execution expired)

**Comment by phatmann** [comment]
Are your test cases subclasses of KIFTestCase?
