### ISSUE TITLE
Google group moderation

### ISSUE THREAD

**Issue by joemasilotti** [kif-framework/KIF#521]
I have submitted a few posts to the [Google Group](https://groups.google.com/forum/#!forum/kif-framework) over the past couple of weeks and nothing has been approved. Who is in charge of moderating this group?

**Comment by joemasilotti** [comment]
@bnickel and @phatmann any updates on this? I have some answers pending I would like to post to the group.

**Comment by phatmann** [comment]
@puls Can you give me moderator access to the KIF Google Group?

**Comment by puls** [comment]
@phatmann I can't, as I don't have access anymore either.

**Comment by phatmann** [comment]
@puls So I need to get this from @bnickel?

**Comment by puls** [comment]
@phatmann Potentially @efirestone could help too.

**Comment by bnickel** [comment]
@phatmann Just added you as a manager.

**Comment by phatmann** [comment]
@bnickel Thanks!
