### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by bitcrumb** [kif-framework/KIF#536]
Hi, I constantly run into the following error when trying to run my unit tests after having added KIF to an existing project using CocoaPods:

```
ld: warning: directory not found for option '-L/Users/Lode/Development/iOS/Projects/persgroep-demorgen-ios/Pods/build/Debug-iphoneos'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_KIFTestCase", referenced from:
      _OBJC_CLASS_$_PGDMUserInterfaceTests in PGDMUserInterfaceTests.o
  "_OBJC_METACLASS_$_KIFTestCase", referenced from:
      _OBJC_METACLASS_$_PGDMUserInterfaceTests in PGDMUserInterfaceTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The only thing I changed in the Podfile was adding this (as specified by the instructions):

```
target :DeMorgenTests, :exclusive => true do
  pod 'KIF', '~> 3.0', :configurations => ['Debug']
end
```

Anyone experiencing the same problems? Any additional information I should provide to help resolve this issue? I'm only doing an `#import <KIF/KIF.h>` in the `PGDMUserInterfaceTests.m` file & haven't written any KIF-specific code yet. Also note that the app builds successfully. I only see the error when running the test using ⌘U.

**Comment by psomaiya17** [comment]
This issue still persist with KIF 3.1.2. Please reopen and solve this. It would be a great help.

**Comment by phatmann** [comment]
@psomaiya17, I cannot reproduce the issue, so I cannot fix it. If you can give me the steps to reproduce it, then I can reopen the issue and try to fix it.

**Comment by IamVicky** [comment]
@phatmann I am facing the same issue. To reproduce the issue please use the following versions. 
Xcode - Version 7.2 (7C68)
Cocoa pods - 0.39.0
KIF version - KIF (3.4.1).
I followed the steps given in this link - [https://github.com/kif-framework/KIF]
If you could not reproduce it. Suggest the required version of cocoa pods and KIF. And steps to install the specific KIF version.
