### ISSUE TITLE
UISegmentedControl support

### ISSUE THREAD

**Issue by danielgomezrico** [kif-framework/KIF#539]
Actually there's no way to set accessibility labels for those controls so there's no way to test them with kif
or I am wrong?

**Comment by zixzelz** [comment]
You can use controls title to search segment or set the accessibilityLabel manually to search UISegmentedControl.

**Comment by phatmann** [comment]
Closing issue since @zixzelz provided a solution. If you still have problems, please re-open this.

**Comment by danielgomezrico** [comment]
I set the accessibilityLabel to the UISegmentedControl but it appears to have a nil value always.
