### ISSUE TITLE
Best framework to report KIF Test cases failures and Success Test cases

### ISSUE THREAD

**Issue by mrbmrb1122** [kif-framework/KIF#540]
Hi, 
We have developed number of KIF Test cases, I'm looking for best framework to report number of test cases which are failed and success after the execution of Test suite. Till now i'm running in XCode only. 
is there any link to follow the framework setup and Jenkins& KIF integration setup and all ? 

Thanks.

**Comment by mrbmrb1122** [comment]
is there any way we can setup Jenkins and Daily builds and reporting ? Do we have any links ??

**Comment by danielgomezrico** [comment]
Maybe those answers can be helpful to you.

https://github.com/kif-framework/KIF/issues/545

**Comment by jhersh** [comment]
We format our build output with `xcpretty`, which supports outputting test results in a number of formats including junit. We point Jenkins at our junit.xml test output and it builds a pretty neat historical trend of passing and failing tests, by name and by pass/fail count.
