### ISSUE TITLE
Iterating over UICollectionView cells is causing memory peak

### ISSUE THREAD

**Issue by TBonnin** [kif-framework/KIF#541]
[Iterating over UICollectionView cells](https://github.com/kif-framework/KIF/blob/master/Additions/UIView-KIFAdditions.m#L246) creates a UICollectionViewCell object for each iteration. (Cells are not dequeued :( )

If the UICollectionView contains a lot of cells (of cells are memory-heavy) the accumulation of those cells  until the end of the current event-loop iteration can result in a big memory overhead (and/or sometimes a crash)

Adding a autoreleasepool to force releasing the cell could help mitigate the issue.
https://gist.github.com/anonymous/f8ea36a6bba4ed2e82b4

 What do you think?

**Comment by TBonnin** [comment]
I created a PR @phatmann if you feel like it is a good idea. https://github.com/kif-framework/KIF/pull/543 :)

**Comment by phatmann** [comment]
Fixed in #543
