### ISSUE TITLE
Version 3.1.1 isn't pushed to cocoapods

### ISSUE THREAD

**Issue by SergioEstevao** [kif-framework/KIF#542]
The tag exists and the podspec was updated on the repo, but one of the owners of the repo needs to push it to cocoapods using the pod trunk command.

**Comment by phatmann** [comment]
I pushed it before, so I am not sure what happened.

I just pushed it again, but the CocoaPods site still says KIF is at 3.1.0. I will check it again in a while, and if it is still at 3.1.0 I will dig in to find out what is going on.

**Comment by phatmann** [comment]
The [CocoaPod spec link](https://raw.githubusercontent.com/CocoaPods/Specs/3e5421972b9f1f6a84c895e183444e2128e5bf97/Specs/KIF/3.1.1/KIF.podspec.json) shows KIF as version 3.1.1 so hopefully the site will be updated soon.

**Comment by phatmann** [comment]
Version was updated to 3.1.1.
