### ISSUE TITLE
Actual running test print format

### ISSUE THREAD

**Issue by caipivara** [kif-framework/KIF#545]
Is there any way to change the terminal output format for each test output?

Actual output:

`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' started.`
`all the output...`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' failed (20.189 seconds).`

But if you run multiple tests looks like this:

`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' started.`
`all the output...`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' failed (20.189 seconds).`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' started.`
`all the output...`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' failed (20.189 seconds).`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' started.`
`all the output...`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' failed (20.189 seconds).`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' started.`
`all the output...`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' failed (20.189 seconds).`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' started.`
`all the output...`
`Test Case '-[UITests.SearchTests testEmptyResultsShowErrorView]' failed (20.189 seconds).`

I want something bigger... like:

`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Success`

and with multiple tests:

`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Success`
`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Success`
`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Success`
`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Failure`
`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Success`
`********* STARTED: testOpenWindow ******`
`there was an error bla bla`
`all the output for the test...`
`---------- ENDED: testClosingWindow --------> Success`

it's easy to see the output for each test and see the app messages for each one.
The actual output make it difficult if you run multiple tests and then check what happened with some failure ones...

So can I set a format for that or maybe be changed for future versions to a more readable one?

**Comment by justinseanmartin** [comment]
We run our results through xcpretty (https://github.com/supermarin/xcpretty) for better log output format. We use 'tee' to keep the original logs output intact, because some useful console logs are filtered to keep the results concise.

**Comment by danielgomezrico** [comment]
Opa thanks

**Comment by danielgomezrico** [comment]
And is there any way to make it print every step? 
To see the full flow of each test?

**Comment by justinseanmartin** [comment]
Hey, just rediscovered this thread two years later... Sorry! Just for the sake of wrapping this up, `xcpretty` allows you to write your own output formatter, so you can output each test log however you'd like.

For the question about `tee`, see more information here:
http://man7.org/linux/man-pages/man1/tee.1.html
