### ISSUE TITLE
How to programmatically tap the "Cancel" button of a UISearchBar?

### ISSUE THREAD

**Issue by dlo** [kif-framework/KIF#548]
Hi all. First of all, thanks for your hard work on KIF. This library has been a godsend. :P 

I'm trying to programmatically tap the "Cancel" button of a UISearchBar. I've tried cycling through its subviews to no avail, and hardcoding a point to tap just seems wrong. Is there a suggested / correct way to do this? Thanks!

**Comment by danielgomezrico** [comment]
If you tap view with accessibility label "Cancel" it works?

**Comment by dlo** [comment]
Unfortunately, that does not work.

![image](https://cloud.githubusercontent.com/assets/38447/5941620/cf1c2364-a6d7-11e4-9c8a-dd808a287730.png)

**Comment by danielgomezrico** [comment]
1. what are you doing to see the error like XCTest? 
I get the KIF errors (like that) only in terminal...

hmm

**Comment by dlo** [comment]
I get them in the terminal too, but figured it'd be easier to understand what I'm seeing with this output.

**Comment by danielgomezrico** [comment]
but I don't get the errors in xcode, just in terminal, how can I enable that?

**Comment by dlo** [comment]
Not totally sure what your setup is...for me they show up automatically.

**Comment by danielgomezrico** [comment]
I'm using swift so maybe is because of that:

`extension XCTestCase {
	
	var tester: KIFUITestActor { return tester() }
	
	func tester(_ file : String = __FILE__, _ line : Int = __LINE__) -> KIFUITestActor {
		return KIFUITestActor(inFile: file, atLine: line, delegate: self)
	}
	
	func system(_ file : String = __FILE__, _ line : Int = __LINE__) -> KIFSystemTestActor {
		return KIFSystemTestActor(inFile: file, atLine: line, delegate: self)
	}
	
}`

**Comment by phatmann** [comment]
Can you turn on the Accessibility Inspector in the simulator and see what the Cancel button's label is?

**Comment by caipivara** [comment]
Sorry, I lost code access to that repo, but thanks for answering back then. :)
