### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by blackbumer** [kif-framework/KIF#552]
Is there any way to build KIF using carthage?

**Comment by phatmann** [comment]
Have you tried it out? I am new to Carthage, and I cannot find any definitive document that spells out what projects need to do to be Carthage compliant. Perhaps they need a dynamic framework target?

**Comment by phatmann** [comment]
Well, I did find some [documentation for project owners](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework). I need to create a dynamic framework target, add the appropriate files and test it all out. I will get this done sometime next week.

But if someone else wants to do it first, please feel free!

**Comment by Goles** [comment]
I'm interested in this one too :+1:

**Comment by phatmann** [comment]
I am not-so-secretly hoping that someone actively using Carthage will submit a pull request. I took a quick stab at this but ran into problems, so I put it aside for the time being.

**Comment by phatmann** [comment]
Done! See #624.
