### ISSUE TITLE
Add KIFUITestActor-IdentifierTests.m as part of the pod framework

### ISSUE THREAD

**Issue by albertbori** [kif-framework/KIF#558]
Not able to find `waitForViewWithAccessibilityIdentifier:accessibilityIdentifier ` (or similar) in the framework, I searched the internet for it. Lo, and behold, I found it nestled in the same framework, but as a test class: https://github.com/kif-framework/KIF/blob/master/IdentifierTests/KIFUITestActor-IdentifierTests.m

Can this be added to the base cocoapods framework? I'm pretty much going to copy all of this code into my project anyways.

**Comment by pikaboo** [comment]
And as an import to KIF.h
I recently updated my module, and found this class, too bad i had to add it myself to the KIF.h file

**Comment by bnickel** [comment]
I believe you can specify `#import <KIF/KIFUITestActor-IdentifierTests.h>` in a bridging header.

**Comment by albertbori** [comment]
Using `COCOAPODS: 0.36.0.beta.2`: 

    Test-Bridging-Header.h:9:9: 'KIF/KIFUITestActor-IdentifierTests.h' file not found

**Comment by phatmann** [comment]
There is an "IdentifierTest" subspec in CocoaPods that includes this file. The idea is that most people should not be using the `accessibilityIdentifier` as their default testing approach, but it is available for those that need it. See #243 for the relevant discussion.

This might change again if we adopt the approach advocated in #555; i.e. decouple finding the view from the action on the view.
