### ISSUE TITLE
KIF crashes in random tests

### ISSUE THREAD

**Issue by albertbori** [kif-framework/KIF#562]
When running all tests, KIF crashes in a random test. When running them individually, each passes. It crashes on the same test each time, but I can comment out that test and it will just break the same way on a different test.

To bring sanity back into the equation, the crashes share something in common: The code that triggers KIF to crash is when either condition is hit (but not always) in the following block. This block is called in beforeEach():

     
    extension KIFUITestActor {

        func navigateToLoginPage() {   
         
            //if on Intro view, go back one
            if self.tryFindingTappableViewWithAccessibilityLabel("Home", error: nil) {
                self.tapViewWithAccessibilityLabel("Home") //crashes here sometimes
            }
            
            //if on Home, log out
            if self.tryFindingTappableViewWithAccessibilityLabel("Settings", error: nil) {
                self.tapViewWithAccessibilityLabel("Settings") //crashes here sometimes
                self.tapViewWithAccessibilityLabel("Log Out")
            }
            
            self.waitForTappableViewWithAccessibilityLabel("Sign In")
        }
    }

These are the two crash traces that I encounter:

### Crash 1 - EXC_BAD_ACCESS

This first one happens on the [following line](https://github.com/kif-framework/KIF/blob/3a321b1be5e19ce65ea2bb0725c7537fa5b2800d/Additions/UIView-KIFAdditions.m#L394) in `UIView-KIFAdditions.m` in `tapAtPoint:point`:

        [[UIApplication sharedApplication] sendEvent:event];

Stack trace:

	Thread 1Queue : com.apple.main-thread (serial)
	#0	0x000000010300300b in objc_msgSend ()
	#1	0x00000001039848be in -[UIApplication sendAction:to:from:forEvent:] ()
	#2	0x00000001039848be in -[UIApplication sendAction:to:from:forEvent:] ()
	#3	0x0000000103a8b410 in -[UIControl _sendActionsForEvents:withEvent:] ()
	#4	0x0000000103a8a7df in -[UIControl touchesEnded:withEvent:] ()
	#5	0x00000001039ca308 in -[UIWindow _sendTouchesForEvent:] ()
	#6	0x00000001039cac33 in -[UIWindow sendEvent:] ()
	#7	0x00000001039979b1 in -[UIApplication sendEvent:] ()
	#8	0x000000011181b9d4 in -[UIView(KIFAdditions) tapAtPoint:] at /Users/me/dev/myproject/Pods/KIF/Additions/UIView-KIFAdditions.m:397
	#9	0x0000000111807ac4 in __49-[KIFUITestActor tapAccessibilityElement:inView:]_block_invoke at /Users/me/dev/myproject/Pods/KIF/Classes/KIFUITestActor.m:202
	#10	0x0000000111801e4f in -[KIFTestActor tryRunningBlock:complete:timeout:error:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFTestActor.m:89
	#11	0x0000000111802194 in -[KIFTestActor runBlock:complete:timeout:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFTestActor.m:112
	#12	0x00000001118022c5 in -[KIFTestActor runBlock:complete:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFTestActor.m:119
	#13	0x00000001118023f5 in -[KIFTestActor runBlock:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFTestActor.m:129
	#14	0x00000001118073a8 in -[KIFUITestActor tapAccessibilityElement:inView:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFUITestActor.m:186
	#15	0x0000000111807250 in -[KIFUITestActor tapViewWithAccessibilityLabel:value:traits:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFUITestActor.m:180
	#16	0x0000000111807061 in -[KIFUITestActor tapViewWithAccessibilityLabel:] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFUITestActor.m:166
	#17	0x00000001116f7231 in ext.AutomationTests.ObjectiveC.KIFUITestActor.navigateToLoginPage (ObjectiveC.KIFUITestActor)() -> () at /Users/me/dev/myproject/MyProject/AutomationTests/KIFExtensions.swift:27
	#18	0x00000001116f7a82 in @objc ext.AutomationTests.ObjectiveC.KIFUITestActor.navigateToLoginPage (ObjectiveC.KIFUITestActor)() -> () ()
	#19	0x0000000111711578 in AutomationTests.MyTests.afterEach (AutomationTests.MyTests)() -> () at /Users/me/dev/myproject/MyProject/AutomationTests/MyTests.swift:15
	#20	0x00000001117115c2 in @objc AutomationTests.MyTests.afterEach (AutomationTests.MyTests)() -> () ()
	#21	0x00000001118033db in -[KIFTestCase tearDown] at /Users/me/dev/myproject/Pods/KIF/Classes/KIFTestCase.m:131
	#22	0x00000001117c0135 in -[XCTestCase invokeTest] ()
	#23	0x00000001117c02f8 in -[XCTestCase performTest:] ()
	#24	0x00000001117c9bf5 in -[XCTest run] ()
	#25	0x00000001117beffb in -[XCTestSuite performTest:] ()
	#26	0x00000001117c9bf5 in -[XCTest run] ()
	#27	0x00000001117beffb in -[XCTestSuite performTest:] ()
	#28	0x00000001117c9bf5 in -[XCTest run] ()
	#29	0x00000001117beffb in -[XCTestSuite performTest:] ()
	#30	0x00000001117c9bf5 in -[XCTest run] ()
	#31	0x00000001117bc0bc in __25-[XCTestDriver _runSuite]_block_invoke ()
	#32	0x00000001117c6ead in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
	#33	0x00000001117bbff0 in -[XCTestDriver _runSuite] ()
	#34	0x00000001117bca1d in -[XCTestDriver _checkForTestManager] ()
	#35	0x00000001117ccaf0 in +[XCTestProbe runTests:] ()
	#36	0x0000000102ba5d55 in __NSFireDelayedPerform ()
	#37	0x00000001032bbf64 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
	#38	0x00000001032bbb25 in __CFRunLoopDoTimer ()
	#39	0x000000010327ee5d in __CFRunLoopRun ()
	#40	0x000000010327e486 in CFRunLoopRunSpecific ()
	#41	0x000000010607e9f0 in GSEventRunModal ()
	#42	0x0000000103983420 in UIApplicationMain ()
	#43	0x00000001024acfae in top_level_code at /Users/me/dev/myproject/MyProject/AppDelegate.swift:20
	#44	0x00000001024acfea in main ()
	#45	0x0000000109a60145 in start ()

### Crash 2 - NSInvalidArgumentException

This second one happens on the [following line](https://github.com/kif-framework/KIF/blob/73e27dfd0d4554a941294aec8eb091454d792948/Classes/KIFTestActor.m#L90) in `KIFTestActor.m` in `tryRunningBlock:complete:timeout:error`:

    while ((result = executionBlock(&internalError)) == KIFTestStepResultWait && -[startDate timeIntervalSinceNow] < timeout) {
        //crashes right here:
        CFRunLoopRunInMode([[UIApplication sharedApplication] currentRunLoopMode] ?: kCFRunLoopDefaultMode, KIFTestStepDelay, false);
    }

Stack trace:

	2015-02-02 16:14:32.511 MyProject[37586:3565110] -[NSPathStore2 perform:]: unrecognized selector sent to instance 0x7fd985c77270
	<unknown>:0: error: -[AutomationTests.MyTests testMyStuff] : failed: caught "NSInvalidArgumentException", "-[NSPathStore2 perform:]: unrecognized selector sent to instance 0x7fd985c77270"
	(
		0   CoreFoundation                      0x0000000106e9bf35 __exceptionPreprocess + 165
		1   libobjc.A.dylib                     0x0000000106b34bb7 objc_exception_throw + 45
		2   CoreFoundation                      0x0000000106ea304d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
		3   CoreFoundation                      0x0000000106dfb27c ___forwarding___ + 988
		4   CoreFoundation                      0x0000000106dfae18 _CF_forwarding_prep_0 + 120
		5   UIKit                               0x00000001074cc8be -[UIApplication sendAction:to:from:forEvent:] + 75
		6   UIKit                               0x00000001074cc8be -[UIApplication sendAction:to:from:forEvent:] + 75
		7   UIKit                               0x00000001075d3410 -[UIControl _sendActionsForEvents:withEvent:] + 467
		8   UIKit                               0x00000001075d27df -[UIControl touchesEnded:withEvent:] + 522
		9   UIKit                               0x0000000107512308 -[UIWindow _sendTouchesForEvent:] + 735
		10  UIKit                               0x0000000107512c33 -[UIWindow sendEvent:] + 683
		11  UIKit                               0x00000001074df9b1 -[UIApplication sendEvent:] + 246
		12  KIF                                 0x00000001153639a0 -[UIView(KIFAdditions) tapAtPoint:] + 816
		13  KIF                                 0x000000011534fa14 __49-[KIFUITestActor tapAccessibilityElement:inView:]_block_invoke + 1700
		14  KIF                                 0x0000000115349d9f -[KIFTestActor tryRunningBlock:complete:timeout:error:] + 175
		15  KIF                                 0x000000011534a0e4 -[KIFTestActor runBlock:complete:timeout:] + 164
		16  KIF                                 0x000000011534a215 -[KIFTestActor runBlock:complete:] + 165
		17  KIF                                 0x000000011534a345 -[KIFTestActor runBlock:] + 101
		18  KIF                                 0x000000011534f2f8 -[KIFUITestActor tapAccessibilityElement:inView:] + 232
		19  KIF                                 0x000000011534f1a0 -[KIFUITestActor tapViewWithAccessibilityLabel:value:traits:] + 320
		20  KIF                                 0x000000011534efb1 -[KIFUITestActor tapViewWithAccessibilityLabel:] + 97
		21  AutomationTests                     0x000000011523f231 _TFE15AutomationTestsCSo14KIFUITestActor19navigateToLoginPagefS0_FT_T_ + 4033
		22  AutomationTests                     0x000000011523fa82 _TToFE15AutomationTestsCSo14KIFUITestActor19navigateToLoginPagefS0_FT_T_ + 34
		23  AutomationTests                     0x0000000115259578 _TFC15AutomationTests8MyTests9afterEachfS0_FT_T_ + 72
		24  AutomationTests                     0x00000001152595c2 _TToFC15AutomationTests8MyTests9afterEachfS0_FT_T_ + 34
		25  KIF                                 0x000000011534b32b -[KIFTestCase tearDown] + 75
		26  XCTest                              0x0000000115308135 -[XCTestCase invokeTest] + 315
		27  XCTest                              0x00000001153082f8 -[XCTestCase performTest:] + 150
		28  XCTest                              0x0000000115311bf5 -[XCTest run] + 260
		29  XCTest                              0x0000000115306ffb -[XCTestSuite performTest:] + 379
		30  XCTest                              0x0000000115311bf5 -[XCTest run] + 260
		31  XCTest                              0x0000000115306ffb -[XCTestSuite performTest:] + 379
		32  XCTest                              0x0000000115311bf5 -[XCTest run] + 260
		33  XCTest                              0x0000000115306ffb -[XCTestSuite performTest:] + 379
		34  XCTest                              0x0000000115311bf5 -[XCTest run] + 260
		35  XCTest                              0x00000001153040bc __25-[XCTestDriver _runSuite]_block_invoke + 56
		36  XCTest                              0x000000011530eead -[XCTestObservationCenter _observeTestExecutionForBlock:] + 162
		37  XCTest                              0x0000000115303ff0 -[XCTestDriver _runSuite] + 269
		38  XCTest                              0x0000000115304a1d -[XCTestDriver _checkForTestManager] + 234
		39  XCTest                              0x0000000115314af0 +[XCTestProbe runTests:] + 182
		40  Foundation                          0x00000001066edd55 __NSFireDelayedPerform + 387
		41  CoreFoundation                      0x0000000106e03f64 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
		42  CoreFoundation                      0x0000000106e03b25 __CFRunLoopDoTimer + 1045
		43  CoreFoundation                      0x0000000106dc6e5d __CFRunLoopRun + 1901
		44  CoreFoundation                      0x0000000106dc6486 CFRunLoopRunSpecific + 470
		45  GraphicsServices                    0x0000000109bc69f0 GSEventRunModal + 161
		46  UIKit                               0x00000001074cb420 UIApplicationMain + 1282
		47  MyProject                            0x0000000105ff4fae top_level_code + 78
		48  MyProject                            0x0000000105ff4fea main + 42
		49  libdyld.dylib                       0x000000010d5a8145 start + 1
	)

---

These two crashes alternate base on whether I've done a clean before testing or not...

I've tried to recreate this in a sample project, but have been unable to. Unfortunately, I can't share the offending project due to NDA.

**Comment by albertbori** [comment]
After wracking my brains, I was able to reproduce it manually, and it ended up being an error in my code that was accessing something that was already deallocated.

So I guess the bug is that KIF needs to not mask real issues, if at all possible.

**Comment by haprock** [comment]
Since I upgraded to Xcode 6.3 & Swift 1.2,I have the same crash (EXC_BAD_ACCESS).
This exception is thrown in the method tapAtPoint: in the file UIVIew+KIFAdditions.m (line [[UIApplication sharedApplication] sendEvent:event]).
I can't reproduce it manually. Does anyone have the same issue ?

**Comment by sebbean** [comment]
I'm experiencing same issue in XCode 6.3 + Swift 1.2

```
class LoginTests: KIFTestCase {
    override func beforeEach() {
        
    }
    override func beforeAll() {
        
    }
    
    func testLogin() {
        tester().tapItemAtIndexPath(NSIndexPath(forItem: 0, inSection: 0), inCollectionViewWithAccessibilityIdentifier: "restaurants")
    }
}
````

Same error as above

**Comment by danielgomezrico** [comment]
Same for me

**Comment by phatmann** [comment]
Dup of #574
