### ISSUE TITLE
Best way to maintain Automation code than the Dev team GIT repo.

### ISSUE THREAD

**Issue by mrbmrb1122** [kif-framework/KIF#566]
Hi, 
In KIF we are creating Test Target on Top of Developers Target and we are using developers workspace. 
How to segregate/maintain 2 different code bases (Developers code and Test Automation code) as developers don't want to maintain Test cases code on their GIT repo.  My questions is how to maintain 2 different code bases and also if we want to run test cases in Jenkins once again we have to merge the 2 code basis on daily basis with Developers changes with minimum manual work efforts.  Like By using git submodules or so.  
Since long time i'm using same GIt repo as developers are using but they are asking me to maintain my Automation code base in different git repo.  

I'm wondering is there any way we can maintain automation code in different GIT and is there any way we can pull the developers code on daily bases with out daily manual efforts.

Thanks.

**Comment by bnickel** [comment]
I believe all that is needed for the tests to run is for A) the app to be compiled and B) the testing target's Test Host and bundle loader to point to the path of the binary in the .app.  I may be wrong.

If that's the case, you should be able to create your own workspace with the app project imported.  Your test host would probably be the same as if it were before: `$(BUILT_PRODUCTS_DIR)/My App.app/My App`.  In your scheme you would need to disable parallel builds and add the app target before your test target in the build order.

Also purely theoretical (and it may be more complex for device testing) but if you are doing true black box UI testing you could take just the compiled .app from Jenkins and use that as the specify that as your bundle loader / test host without.

**Comment by mrbmrb1122** [comment]
Do we have any link or any document on how to setup KIF on top of .app file with out using source code? do we have any link or document to follow? Can you please help me, how to setup KIF on top of .app file. 

Thanks
