### ISSUE TITLE
Custom UITableViewCell values empty

### ISSUE THREAD

**Issue by danielgomezrico** [kif-framework/KIF#569]
Hi,

I want to check if my tableview cells (that are `CustomCell`) `valueLabel` text is the same as value,
but when it exec `cellForRowAtIndexPath` it don't run my `UIViewController`overrite method so the cell is not filled up with my data... and when it try to do the `==` each field of my `CustomCell` is nil.

Is this a bug or I have to do this with other code?

```
let value = "Test Value"
let aspectsTable = waitForTappableViewWithAccessibilityLabel(label) as UITableView
		
let cell = aspectsTable.cellForRowAtIndexPath(NSIndexPath(forItem: item, inSection: 0)) as CustomCell
XCTAssert(cell.valueLabel.text == value, "Found: \(cell.valueLabel.text) and need:  \(value)")
```

**Comment by phatmann** [comment]
Two problem::

1. Accessing the table via an `accessibilityLabel` is not recommended.
1. Your cell might be offscreen and therefore be nil.

Use`waitForCellAtIndexPath:inTableViewWithAccessibilityIdentifier:` instead.

**Comment by danielgomezrico** [comment]
And why is not recommended?

Opa Thanks

**Comment by phatmann** [comment]
Using accessibility labels for scroll views like UITableView is not recommended, since they hide access to the accessibility labels of their subviews. I have added issue #592 to document this.
