### ISSUE TITLE
KIF tries to tap views from dismissed window

### ISSUE THREAD

**Issue by john-langley** [kif-framework/KIF#572]
Hi - love KIF ...

When we log in / out of our app, we present a new window containing our login view controller.  One test class logs in and out rapidly using accounts with different account statuses ... KIF seems to retain the first window presented and continues to attempt to tap / interact with subviews of that window ... rather than the new window presented onscreen.

Is this expected behavior?

**Comment by justinseanmartin** [comment]
Are you interacting with app methods directly anywhere in your tests or is all interaction through the KIF APIs? We had something similar when we were signing out programmatically, because we weren't wrapping it in an @autoreleasepool block.

**Comment by phatmann** [comment]
Looking through the KIF code, I don't see any UIWindows being cached. Take a look at `accessibilityElementWithLabel` from UIApplication-KIFAdditions.m to see what I mean

Can you trace through your code to see what is going on in your situation?

**Comment by john-langley** [comment]
I haven't solved my issue yet, but I made a separate project to test transitioning between windows with KIF and there was no problem ... pretty sure this is just something on my side.

Sorry for the confusion, thanks for looking into it.

**Comment by phatmann** [comment]
Thanks for testing this out!
