### ISSUE TITLE
Incompatible with Xcode 6.3 / iOS 8.3 (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by siemensikkema** [kif-framework/KIF#574]
The existing test suite breaks under Xcode 6.3. There is an EXC_BAD_ACCESS at line 394 in UIView-KIFAdditions.m as a result of calling ```tapViewWithAccessibilityLabel:```. It seems something changed under the hood related to UITouch.
See also #562, specifically https://github.com/kif-framework/KIF/issues/562#issuecomment-74267256

**Comment by gurgeous** [comment]
+1

**Comment by a-dogan** [comment]
Seeing this as well, same version of Xcode. In my case using [tester waitForViewWithAccessibilityLabel:@"Cancel"]; works, but when I try to tap it I get the same exception as you.

**Comment by Twyly** [comment]
+1

**Comment by codeman9** [comment]
+1

**Comment by triage** [comment]
+1

**Comment by TBonnin** [comment]
To give a little bit more details. I just poked around a few minutes and this is what I can report:
`[UIView TapAtPoint:]` indeed crashes at line https://github.com/kif-framework/KIF/blob/a98d41/Additions/UIView-KIFAdditions.m#L402 with following error `(EXC_BAD_ACCESS, code=1, address=0x20)`

I suspect the UIEvent internals to have changed so the UIEvent object constructed by the `[UIView eventWithTouches:]` method https://github.com/kif-framework/KIF/blob/a98d41/Additions/UIView-KIFAdditions.m#L756 via calls to private API is probably incorrect.

**Comment by rvangraan** [comment]
We get the same crash too. Any suggestions on how to fix it?

**Comment by phatmann** [comment]
I have not tested with the 6.3 beta yet. Has anyone dumped the private headers for clues as to what has changed?

**Comment by TBonnin** [comment]
Hi,
I have a tentative fix for this issue. See https://github.com/kif-framework/KIF/pull/582
I have tested on iOS 7.1, 8.1 and 8.3 but I had not a lot of devices handy. I would appreciate a lot if anybody could test my patch on more devices/OS.

Thank you

**Comment by Tulkas** [comment]
I have the same issue, but I get the error in the line 180 of KIFUITestActor.

**Comment by phatmann** [comment]
Fixed by #582

**Comment by luoxubin** [comment]
Hi  @phatmann ，Is there an other way to fake a touch event without rely on IOKit， just like the way as before #582， not use pure C private APIs. Because my app need to submit to AppStore, and need to simulate touch event in some scene. I have ask many friends and still have not work it out. Can you help me?
Many thanks.

**Comment by luoxubin** [comment]
My Email is：394934942@qq.com

**Comment by luoxubin** [comment]
I didn't know how to pass  the apple API scanning with using a pure C private API.   If use Obj-c private  API , we can use runtime features to combine the method name  dynamically and the performSelector or  NSInvocation it.

**Comment by phatmann** [comment]
@luoxubin This is not the right forum for this discussion. I recommend trying stackoverflow.
