### ISSUE TITLE
KIFTester starts, but non of tests cases are picked by All tests suite

### ISSUE THREAD

**Issue by razgon** [kif-framework/KIF#578]
KIF version 3.1.2, iOS 8.1.3, iPhone 5.

I've a bunch of test cases that stopped to work for some reasons on a real device.
I'm wondering what is the problem here?

2015-02-18 18:27:54.838 Application[309:22929] KIFTester loaded
......
After 30s no testing has occurred. Process arguments and environment:
(
    "/var/mobile/Containers/Bundle/Application/AAC9D8D8-B7A4-419F-B5FA-395066CC9653/Application.app/Application",
    "--use-testmanagerd",
    "7467320C-8753-4D4A-A914-C596D4E6C243",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES,
    "-XCTest",
    All,
    "/Users/igolovenko/Library/Developer/Xcode/DerivedData/Application-cafxiqfcbbczvkezpwscftqdsllz/Build/Products/Debug-iphoneos/ApplicationTests.xctest"
) {
......
}
.....
Test Suite 'All tests' started at 2015-02-19 02:28:00 +0000
Test Suite 'All tests' passed at 2015-02-19 02:28:00 +0000.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds

Project settings seems to be fine. Any clue?

**Comment by razgon** [comment]
Tests became broken after huge merge from parallel branch.

**Comment by TBonnin** [comment]
Hi @razgon,
What merge/branch are you talking about? Thank you

**Comment by razgon** [comment]
Hi @TBonnin , 
There was a code merge from development to master branch. Project files look fine and no changes were made to test source code and KIF source code. Right now I'm comparing working commit with merge that broke it.

**Comment by razgon** [comment]
If I will add new test bundle with KIF in my project, it will also not pick default test case.

**Comment by TBonnin** [comment]
@razgon can you give a link to the merge (or even better to a specific commit). It is quite hard to help you without details.

**Comment by razgon** [comment]
@TBonnin thanks, but unfortunately this is private repository. 
BTW, I did rebuild whole project/workspace from a scratch, but it didn't help.

**Comment by razgon** [comment]
This was funny) After code review we found that application was cleaning Application/tmp folder. We added exclude for XCTest related files, so now everything works as expected.
