### ISSUE TITLE
tapItemAtIndexPath:inCollectionViewWithAccessibilityLabel:

### ISSUE THREAD

**Issue by SebastianMecklenburg** [kif-framework/KIF#580]
Hello all,

There is the method tapItemAtIndexPath:inCollectionViewWithAccessibilityIdentifier: in KIFUITestActor but no method to access the view with its label, so I wrote one, it's very simple and works fine. Then I noticed that the method tapRowInTableViewWithAccessibilityLabel:atIndexPath: is deprecated and now I wonder if there is anything wrong with using accessibility labels for this sort of views. 

Thanks and regards,
Sebastian Mecklenburg

P.S.: 
The method I wrote
```
- (void)tapItemAtIndexPath:(NSIndexPath *)indexPath inCollectionViewWithAccessibilityLabel:(NSString *)label
{
    UICollectionView *collectionView = (UICollectionView*)[self waitForViewWithAccessibilityLabel:label];
    [self tapItemAtIndexPath:indexPath inCollectionView:collectionView];
}
```

**Comment by phatmann** [comment]
Using accessibility labels for scroll views like UITableView is not recommended, since they hide access to the accessibility labels of their subviews. This is the only time that you really need to use `accessibilityIdentifier` and this is why KIF recommends this approach.

**Comment by SebastianMecklenburg** [comment]
Ah, thank you very much. I only accessed their subviews by index, that's probably why I didn't run into problems.
Maybe adding that very message of yours as a comment to the ...```accessibilityIdentifier``` methods would be a good idea as I found it a bit confusing why the identifier suddenly showed up instead of the label. Or did I miss something in the docs?

**Comment by phatmann** [comment]
We should document this. Added #592 to cover this.
