### ISSUE TITLE
waitForCellAtIndexPath:inCollectionView

### ISSUE THREAD

**Issue by SebastianMecklenburg** [kif-framework/KIF#583]
Hello there,

I noticed that the method waitForCellAtIndexPath:inCollectionView in KIFUITestActor sometimes erroneously fails. I added [the solution added by hfossli here](http://stackoverflow.com/questions/21469459/cellforitematindexpath-returns-nil-after-force-scrolling-to-make-it-visible) and added a waitForAnimationsToFinish call now it works. I appended the full method below. 
I have a huge collection view with a lot of stuff loaded from an online source so this problem will probably occur quite rarely.

Regards,
Sebastian Mecklenburg

```
- (UICollectionViewCell *)waitForCellAtIndexPath:(NSIndexPath *)indexPath inCollectionView:(UICollectionView *)collectionView
{
    if (![collectionView isKindOfClass:[UICollectionView class]]) {
        [self failWithError:[NSError KIFErrorWithFormat:@"View is not a collection view"] stopTest:YES];
    }
    
    NSInteger section = indexPath.section;
    NSInteger item    = indexPath.item;
    
    // If section < 0, search from the end of the table.
    if (section < 0) {
        section += collectionView.numberOfSections;
    }
    
    // If item < 0, search from the end of the section.
    if (item < 0) {
        item += [collectionView numberOfItemsInSection:section];
    }

    indexPath = [NSIndexPath indexPathForItem:item inSection:section];

    [self runBlock:^KIFTestStepResult(NSError **error) {

        KIFTestWaitCondition(indexPath.section < collectionView.numberOfSections, error, @"Section %ld is not found in collection view", (long)indexPath.section);

        KIFTestWaitCondition(indexPath.row < [collectionView numberOfItemsInSection:indexPath.section], error, @"Item %ld is not found in section %ld of collection view", (long)indexPath.row, (long)indexPath.section);

        return KIFTestStepResultSuccess;
    }];

    [collectionView scrollToItemAtIndexPath:indexPath
                           atScrollPosition:UICollectionViewScrollPositionCenteredHorizontally | UICollectionViewScrollPositionCenteredVertically
                                   animated:YES];
    [self waitForAnimationsToFinish];
    [self waitForTimeInterval:0.5];
    UICollectionViewCell *cell = [collectionView cellForItemAtIndexPath:indexPath];
    
    if(cell == nil) {
        [collectionView layoutIfNeeded];
        [self waitForTimeInterval:0.5];
        cell = [collectionView cellForItemAtIndexPath:indexPath];
    }
    
    if(cell == nil) {
        [collectionView reloadData];
        [collectionView layoutIfNeeded];
        [self waitForTimeInterval:0.5];
        cell = [collectionView cellForItemAtIndexPath:indexPath];
    }

    if (!cell) {
        [self failWithError:[NSError KIFErrorWithFormat: @"Collection view cell at index path %@ not found", indexPath] stopTest:YES];
    }

    return cell;
}
```

**Comment by SebastianMecklenburg** [comment]
Sorry, still doesn't work sometimes so my solution is obviously not correct. I will try to figure out what my problem is here and try again.

**Comment by phatmann** [comment]
@SebastianMecklenburg, I am glad you found a solution to this issue. 

I am comfortable with the call to `layoutIfNeeded`, but the call to `reloadData` seems pretty heavy-handed. In your own experience, is the call to `reloadData` ever needed? If not, let's not even put it in there.

Any chance you could put together a pull request?

**Comment by SebastianMecklenburg** [comment]
Hello, the problem is that the error occurred quite randomly, sometimes the ```[self waitForAnimationsToFinish];``` made it go away, sometimes the ```layoutIfNeeded``` and/or ```reloadData``` was needed too. Since the ```reloadData``` is called only as a last resort if everything else fails it was OK for me. I have to implement a few more tests that use this method anyway I will try to find out what is actually really needed. Maybe some of the ```waitForTimeInterval``` calls are uneccessary too.
