### ISSUE TITLE
KIF_SCREENSHOTS not working

### ISSUE THREAD

**Issue by fyruicao** [kif-framework/KIF#584]
I set the env in the command line:

```
mkdir Screenshots
export KIF_SCREENSHOTS=`pwd`/Screenshots
```
And then run test with xodebuild, but the result is:
`Screenshot path not defined. Please set KIF_SCREENSHOTS environment variable.`
Is the env belong to the simulator?
My KIF version is 3.1.2
Xcode version is 6.1

**Comment by TBonnin** [comment]
Weird. It doesn't seem like you are doing anything wrong.
Can you run `printenv` before xcodebuild and check KIF_SCREENSHOTS is part of the env vars?

**Comment by fyruicao** [comment]
I print the env and i find that KIF_SCREENSHOTS is in the env;
And i also print (key,value) in `NSDictionary *environment = [[NSProcessInfo processInfo] environment];`
The result is like this:
```
key:SIMULATOR_RUNTIME_VERSION,value:8.1
key:SIMULATOR_MAINSCREEN_WIDTH,value:640
```
`KIF_SCREENSHOTS` is not included;
It seems like the env is belong to the simulator

**Comment by TBonnin** [comment]
From the [apple doc](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSProcessInfo_Class/index.html#//apple_ref/occ/instp/NSProcessInfo/environment)
`[[NSProcessInfo processInfo] environment]: The variable names (keys) and their values in the environment from which the process was launched.`
As long as the simulator was launched in the same environment you did the export `KIF_SCREENSHOTS` I don't understand why it is not found.

Can yo copy-paste your full xcodebuild script? @fyruicao

**Comment by fyruicao** [comment]
@TBonnin My script is:
`xcodebuild -workspace ***.xcworkspace -scheme *** -destination 'platform=iOS Simulator,name=iPhone 5' -derivedDataPath ./Build clean test`

**Comment by TBonnin** [comment]
I am gonna be honest. I have no idea what is wrong in your setup.

**Comment by phatmann** [comment]
Open the Scheme you are using. Go to Run. Go to Arguments. In Environment Variables, add KIF_SCREENSHOTS. Let me know if that works for you.

**Comment by fyruicao** [comment]
@phatmann it works for me~
