### ISSUE TITLE
Static analysis error: NSMutableArray' method 'addObject' cannot be nil

### ISSUE THREAD

**Issue by BergQuester** [kif-framework/KIF#585]
KIF/Classes/KIFUITestActor.m:498:13: warning: Argument to 'NSMutableArray' method 'addObject:' cannot be nil
            [dataToSelect addObject: rowTitle];
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

**Comment by 0xced** [comment]
Should be solved by #563.

**Comment by phatmann** [comment]
#563 is merged. If this issue persists please re-open it.
