### ISSUE TITLE
waitForCellAtIndexPath is always returning the second row

### ISSUE THREAD

**Issue by ararog** [kif-framework/KIF#595]
Hi,

Today I noticed waitForCellAtIndexPath is always returning the second row for a testcase like below:

```
    [tester tapViewWithAccessibilityLabel:nil traits:UIAccessibilityTraitSearchField];
    [tester waitForFirstResponderWithAccessibilityLabel:nil traits:UIAccessibilityTraitSearchField];
    [tester enterTextIntoCurrentFirstResponder:@"micro"];
    [tester waitForViewWithAccessibilityLabel:nil value:@"micro" traits:UIAccessibilityTraitSearchField];

    [tester waitForCellAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0] inTableViewWithAccessibilityIdentifier:@"TableView Companies"];

    [tester tapRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0] inTableViewWithAccessibilityIdentifier:@"TableView Companies"];
```

Any ideas about a possible workaround?

**Comment by phatmann** [comment]
What is special about your code that trips up `waitForCellAtIndexPath`? Can you walk through the code to see what is going wrong?

**Comment by ararog** [comment]
There's nothing special in my code that would cause this issue, in fact this is happening in all TableViews that I'm testing on the app, as workaround I'm always trying to make sure there's a second cell available to be checked/tapped.

As you can see this testcase will trigger some search with UISearchViewController and then I'm checking if there's any search results available, I'm not doing anything like remove cells or deleting data from my UI code that you cause this issue, the issue is just happening.

**Comment by phatmann** [comment]
The unit tests for KIF show `waitForCellAtIndexPath` to be working as advertised, so there must be *something* about your situation that is different than the unit tests. If you can find out what that is, I would be much obliged. Ideally we would then add a failing unit test to KIF and fix the issue.
