### ISSUE TITLE
No screenshot saved upon a failing test when using KIF with Specta

### ISSUE THREAD

**Issue by tutipeti** [kif-framework/KIF#598]
Hey,

as Jenkins is giving me more and more headache I wanted to use your wonderful feature of saving screenshots for failed tests to know what state was the app then. Sadly this didn't work, no matter where was I setting the KIF_SCREENSHOTS variable.

I was able to pinpoint the issue to the fact that I'm using Specta here, as Specta is extending XCTestCase for the test files. Because of this no screenshot taking code is executed, as `- (void)failWithException:(NSException *)exception stopTest:(BOOL)stop;` is called in `XCTestCase-KIFAdditions` instead of `KIFTestCase`.

As far as I can tell @minhtule had the same issue in pull #436 - but that pull has been closed and I believe that the last comment has nothing to do with this issue.

Should I have missed something please tell me what else do I need to do to get screenshots taken while using Specta.

Thanks in advance,
Peter

**Comment by phatmann** [comment]
If I understand the situation correctly, there are only two ways to fix this:

1. Change Specta so it does not break KIF
2. Call the screenshot code from `XCTestCase-KIFAdditions` and `SenTestCase-KIFAdditions`

Option 2 seems fine to me. Can anyone see any issues with it? It might result in a little code duplication, but I could live with this, since OCUnit is deprecated.

**Comment by tutipeti** [comment]
If you are only awaiting my feedback here then I'm fine with Option 2 ;)

**Comment by phatmann** [comment]
I will make the fix described in option 2

**Comment by vase4kin** [comment]
Hello, guys! Any news?

**Comment by phatmann** [comment]
No news yet. I have not made the fix described above. It should be simple but I have been too busy to work on it. If you want to submit a pull request with the fix, please go right ahead and I will merge it ASAP.

**Comment by vase4kin** [comment]
@phatmann i created pull request #695. Could you please review?
