### ISSUE TITLE
Swiping and UIPageViewController

### ISSUE THREAD

**Issue by SebastianMecklenburg** [kif-framework/KIF#601]
Swiping through views that belong to a UIPageViewController doesn't seem to work properly. Sometimes it goes correctly to the next or previous page (depending on the swipe direction), but often it jumps over a page or stays on the same page.

I think the problem lies in ```viewContainingAccessibilityElement:tappable:error:``` in the UIAccessibilityElement-KIFAdditions category. It calls ```[UIScrollView scrollViewToVisible]```but since the UIPageViewController stacks three view controllers (it pre-renders the previous and next page) the ```viewContainingAccessibilityElement``` method seems to get hold of the wrong one and scrolls that to be visible. I'm not completely sure if this is the problem though, maybe I can find some time to dig into this a bit further the next days...

**Comment by edalford11** [comment]
[tester swipeViewWithAccessibilityLabel:@"0 Streams Table View" inDirection:KIFSwipeDirectionLeft]; works for me. Assuming you've given your first page controller table view that same label. However one thing that isn't working for me is [tester waitForViewWithAccessibilityLabel:@"1 Streams Table View"]; I've confirmed that the table view has the correct accessibility label but when it comes into the view KIF can't seem to find it.

**Comment by edalford11** [comment]
I take that back. KIF isn't recognizing the new page because it's not even making the swipe correctly. Looks like it's attempting to swipe but it ends up staying on the same page. Exactly what SebastianMecklenburg said. Bug?

**Comment by phatmann** [comment]
@SebastianMecklenburg, thanks for finding this issue and identifying the root cause. If you find a fix, please submit a pull request.

**Comment by rodrigotakase** [comment]
@SebastianMecklenburg I'm having the same problem with swipe and UIViewPageController, did you solve that?

**Comment by SebastianMecklenburg** [comment]
@rodrigotakase No, sorry, I resorted to testing only the currently visible page.

**Comment by To1ne** [comment]
I have implemented a swipe for pages myself (not the most beautiful code, but it works):
```objc
- (void)swipePageViewWithAccessibilityLabel:(NSString *)label inDirection:(KIFSwipeDirection)direction
{
  UIView *viewToSwipe = nil;
  UIAccessibilityElement *element = nil;

  [self waitForAccessibilityElement:&element view:&viewToSwipe withLabel:label value:nil traits:UIAccessibilityTraitNone tappable:YES];

  // Within this method, all geometry is done in the coordinate system of the view to swipe.
  CGRect elementFrame = [viewToSwipe.windowOrIdentityWindow convertRect:element.accessibilityFrame toView:viewToSwipe];
  CGRect swipeRect = CGRectInset(elementFrame, CGRectGetWidth(elementFrame) * 0.05, CGRectGetHeight(elementFrame) / 2);
  CGPoint leftPoint = CGPointMake(swipeRect.origin.x, swipeRect.origin.y);
  CGPoint rightPoint = leftPoint;
  rightPoint.x += CGRectGetWidth(swipeRect);

  switch (direction) {
    case KIFSwipeDirectionRight:
      [viewToSwipe dragFromPoint:leftPoint toPoint:rightPoint steps:2];
      break;
    case KIFSwipeDirectionLeft:
      [viewToSwipe dragFromPoint:rightPoint toPoint:leftPoint steps:2];
      break;
    default:
      ;
  }
}

**Comment by phatmann** [comment]
Looks like fine code to me! Would be great if you could file a PR with it.

**Comment by To1ne** [comment]
Owkey. I'll try to find a window of time to properly file a PR. (I want to do some refining of the code and also when looking at the test running is kinda quirky)

**Comment by sirnacnud** [comment]
I'm interested in this functionality as well.

**Comment by mikelupo** [comment]
Let's be careful not to break scrolling in Collection Views with this.

**Comment by ohadnav** [comment]
Any solution to UIPageViewController?

**Comment by PeqNP** [comment]
For whatever reason the change made to `UIScreen.main.majorSwipeDisplacement` is still not enough (at times) to scroll to the next page in the context of a `UIPageViewController`.

Is it possible to allow the value `0.625` to be changed at test time and then reset after a test?
```
KIF.displacementPercent = 0.8
```
OR a new `swipeView` method call that allows you to define that value:
```
KIFUITestActor().swipeView(withAccessbilityIdentifier: "my-id", in: .left, for: 0.8)
```
OR as an `enum` which defines the type of swipe.
```
enum KIFSwipeDisplacementAmount: CGFloat {
    case full = 0.8
    case `default` = 0.625
}

let direction: KIFSwipeDirection = .left
let displacementAmount: SwipeDisplacementAmount = .full
KIFUITestActor().swipeView(withAccessbilityIdentifier: "my-id", in: direction, for: displacementAmount)
```
