### ISSUE TITLE
Static universal KIF library complains about arm64

### ISSUE THREAD

**Issue by rajsaby** [kif-framework/KIF#602]
I use libKIF.a (universal version created by lipo) in my project. With latest build of KIF, I am getting following errors. I have build KIF with armv7 and arm64. Not sure what's the issue.

![screen shot 2015-03-18 at 1 47 27 pm](https://cloud.githubusercontent.com/assets/5034790/6719044/52228672-cd75-11e4-91e7-86684018c249.png)

**Comment by rajsaby** [comment]
will it happen because I didn't include IOKit.framework to my target's build phase?

**Comment by TBonnin** [comment]
That's exactly it @rajsaby

**Comment by rajsaby** [comment]
Thanks @TBonnin .
I have hard time adding IOKit.framework in my project. I can see framework exists at right path (Macintosh HD ▸ Applications ▸ Xcode ▸ Contents ▸ Developer ▸ Platforms ▸ iPhoneOS.platform ▸ Developer ▸ SDKs ▸ iPhoneOS.sdk ▸ System ▸ Library ▸ Frameworks), but m not able to select from Build Phases setting. Could you please guide me for how to do that?

**Comment by TBonnin** [comment]
There are 3 way to do so :) :
1. Go to build phase setting 'Link
2. Just drag and drop IOKit.framework in your project Framework group.
3. You can also do "Add Files to", navigate to the frameworks path and select IOKit.framework

**Comment by phatmann** [comment]
@rajsaby were you able to solve your issue?

**Comment by rajsaby** [comment]
I was able to include IOKit.framework but now m seeing different issues. But that seems to be my project related issues, so m going to close this issue. Thanks for your help!

**Comment by pikaboo** [comment]
what issues did you see ?

**Comment by applequist** [comment]
Hi, I'm having the same issue: couldn't find IOKit.framework so I added it manually but I now have hundreds of errors that seem related to the x86_84 architecture. 

I've looked for architecture related settings in my build and I seem to be building for arm7 and arm64... so no x86_64 no ?

Any help appreciated.

Brieuc

**Comment by TBonnin** [comment]
@applequist 
Go to your target build setting and remove "$(DEVELOPER_DIR)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" from the Framework search path setting that Xcode automatically added when manually imported IOKit.framework

**Comment by applequist** [comment]
Thank you @TBonnin !!

**Comment by robdashnash** [comment]
Thank you @TBonnin !!

**Comment by anandjp** [comment]
this helped... thanks @TBonnin !!
