### ISSUE TITLE
static KIF library not working on simulator.

### ISSUE THREAD

**Issue by rajsaby** [kif-framework/KIF#604]
So I am creating static library for KIF project (libKIF.a) using iOS simulator.
If I do "lipo -info libKIF.a" it gives i386 x86_64, which I assume are correct architectures for simulator.
I am trying to use the same libKIF.a in my main project but it fails complaining about undefined symbols for x86_64 arch.
Note - I built the KIF static library for iOS device, used it in my project and it works fine. It's the simulator one which has problems. Any ideas?

**Comment by TBonnin** [comment]
What kind of errors do you get?

**Comment by rajsaby** [comment]
I am getting undefined symbols for x86_64 for various libKIF.a modules.

**Comment by rajsaby** [comment]
Got it working now :)
I was building from command prompt and had some problem in script there. Sorry for false alarm.

**Comment by pikaboo** [comment]
how did you fix the problem ?
