### ISSUE TITLE
Move print hierarchy code into a different file

### ISSUE THREAD

**Issue by phatmann** [kif-framework/KIF#610]
See #607. I like having this feature, but the code probably should not be in UIView+Additions. Something like `Debugging` or `Utilities` seems more appropriate.

**Comment by GraemeEArthur** [comment]
Hi, considering working on this issue but wanted to check something: when you say `Debugging` or `Utilities` seems more appropriate, are you meaning a separate class or another category on `UIView`? I would probably have gone for the former myself, but I'm happy to do it either way depending on your preference.

**Comment by phatmann** [comment]
Either way is fine by me. Thanks for offering to work on this!

Tony
