### ISSUE TITLE
No support for Swiping on a view based on AccessibilityIdentifier (instead of label)

### ISSUE THREAD

**Issue by psethi** [kif-framework/KIF#618]
Theres a method "swipeViewWithAccessibilityLabel" however there's no method "swipeViewWithAccessibilityIdentifier". We use identifiers for testing purposes so that it doesn't interfere with voice over. Could you please add that?

**Comment by ninjazoete** [comment]
I think its an issue with KIF as a whole. I still don't really understand why they chose to operate on labels when identifiers are available. Labels are as you pointed out for a customer to hear and to help him, ids are for programmers to have some model layer which they can work on. The first thing when we started playing with KIF, my colleague just changed the implementation to always base it on IDs. Would be a nice feature from if we could have an option for actor to use IDs or Labels. 

Cheers

**Comment by TBonnin** [comment]
This discussion in #243 might give you some context about why accessibilityLabel is most of the time preferable to accessibilitlyIdentifier.

**Comment by ninjazoete** [comment]
Thanks, I am in AccessibilityIdentifier camp and still think they are confusing functional testing term though this discussion is interesting.

**Comment by phatmann** [comment]
Fixed by #614
