### ISSUE TITLE
Erroneous Predicate in KIFUIActor-ConditionalTests.m

### ISSUE THREAD

**Issue by kashzonal** [kif-framework/KIF#620]
Predicate located on line 63 of .m file

The predicate is making an assignment('=') instead of an equality check('==').  
The following predicate seem work well without failing:

[NSPredicate predicateWithFormat:@"accessibilityIdentifier == %@ || accessibilityLabel == %@", identifier,identifier]

**Comment by phatmann** [comment]
The `=` operator is a synonym for `==` in a predicate string. 

You can use `tryFindingViewWithAccessibilityIdentifier` to find a view by its identifier.
