### ISSUE TITLE
Possible leak of IOHIDEvents when profiling tests

### ISSUE THREAD

**Issue by czechboy0** [kif-framework/KIF#631]
I have been seeing a high memory footprint of our KIF-drivven tests, sometimes leading to a crash halfway through. When I got to profiling the tests, I saw that there are leaks present, which definitely contributes to the overall high memory footprint. See Instruments screenshot, can you let me know if that's fixable in KIF? Thanks.

![kif_leaks](https://cloud.githubusercontent.com/assets/2182121/7252553/19f3f3b6-e82e-11e4-9ca4-b62878241ce2.png)

**Comment by TBonnin** [comment]
:( I will have a look into this asap. Thanks for reporting @czechboy0

**Comment by TBonnin** [comment]
Just pushed a PR that would fix the memory leak issue. https://github.com/kif-framework/KIF/pull/632

@czechboy0 Can you double check it resolves the problem you have been seeing? Thank you for your help

**Comment by phatmann** [comment]
I am closing this now that the fix is in via #632.

@czechboy0 please reopen if you still see the leak even after pulling the fix.

**Comment by czechboy0** [comment]
Yeah that fixed it, thanks!
