### ISSUE TITLE
clearTextFromAndThenEnterText not working with iOS 8.3 and latest KIF

### ISSUE THREAD

**Issue by MatthewvanBoheemen** [kif-framework/KIF#649]
I've recently upgraded to iOS 8.3 and the latest version of KIF. I now get failures in my tests when using the clearTextFromAndThenEnterText method. 
The errors I get are:
- The step timed out after 1.00 seconds: Failed to get Text "" in field; instead; it was "(null)"
- The step timed out after 1.00 seconds: Failed to get Text "One" in field; instead; it was "TestOne"

It seems like there are issues around the text field interaction, possibly with the handling of an empty string and with clearing existing values.

Are other people encountering this problem? Any suggestions on how to workaround this?

Thanks

**Comment by simonlinj** [comment]
Having no problem on an iPhone 6+ with 8.3 and latest version of KIF. with that method(clearTextFromAndThenEnterText)
Are you using a property o ivar in your class for input source? note that those variables are not persisted between each test iteration.

but you can use a static pointer instead. 

```
static NSString *_str;
```

**Comment by jedidja** [comment]
I'm having no problems `clearTextFromAndThenEnterText` on an iPhone 4S with 8.3 and the latest version of KIF.

**Comment by kmilitagaitan** [comment]
I'm having  problems with `clearTextFromAndThenEnterText ` on an Iphone 6 ios 8.3,  and the latest version of KIF

**Comment by phatmann** [comment]
@kmilitagaitan Can you figure out what is going wrong?

**Comment by bithavoc** [comment]
:+1:

**Comment by ptammaro** [comment]
I had the same problem on an iPhone 6 and iOS 8.3. My KIF pod was on version 3.1. I updated it to 3.2.3 and it fixed the problem.

**Comment by phatmann** [comment]
Is anyone seeing this issue with a version of KIF below 3.2.3?

**Comment by ziadtamim** [comment]
@phatmann I am still having the same issue using v3.4.2.

**Comment by phatmann** [comment]
@ziadtamim: thanks for the update. Can you figure out specifically what is going wrong?

**Comment by amarantedaniel** [comment]
Have this issue been fixed? I see it's very old, but I'm having it with KIF 3.5.2 and ios 10.3

**Comment by mikelupo** [comment]
We stopped using accessibiityLabel and started using Identifiers over a year ago. It may be because of that we've not encountered this issue?.?.? 
Anyway, it may be a potential workaround for you.

[tester enterText: [self.userName uppercaseString] intoViewWithAccessibilityIdentifier:@"login.emailTF"];
