### ISSUE TITLE
Carthage: Reason: The run destination iPad 2 is not valid for Running the scheme 'KIFFramework'.

### ISSUE THREAD

**Issue by safetyscissors** [kif-framework/KIF#650]
Hi,

I recently tried to install KIF using Carthage and got the following error.

I'm currently using:

Xcode 6.3.1
Build version 6D1002

*** Fetching OHHTTPStubs
*** Fetching KIF
*** Fetching specta
*** Checking out KIF at "v3.2.2"
*** Checking out OHHTTPStubs at "4.0.1"
*** Checking out specta at "v1.0.0"
*** xcodebuild output can be found in /var/folders/rr/z_x95s291hq84njdww4flnq80000gp/T/carthage-xcodebuild.qAcfdL.log
*** Building scheme "KIFFramework" in KIF.xcodeproj
xcodebuild: error: Failed to build project KIF with scheme KIFFramework.
	Reason: The run destination iPad 2 is not valid for Running the scheme 'KIFFramework'.

Looking at the log I have this:

Build settings from command line:
    SDKROOT = iphonesimulator8.3

**Comment by jberkel** [comment]
encountered the same problem, the issue might be that the test host target is included in the framework target (it's probably not needed there). for some reason xcode sometimes picks the first installed simulator which happens to be 'ipad 2'.

**Comment by phatmann** [comment]
@jberkel Glad you have an idea here. Are you going to submit a pull request with your fix in it? Or do you need to test it more?

**Comment by jberkel** [comment]
need to test a bit more but will submit PR once i can confirm it

**Comment by simX** [comment]
I can confirm that deleting the "Test Host" reference in the KIFFramework scheme fixes this problem.

**Comment by phatmann** [comment]
Fixed by #652
