### ISSUE TITLE
Should `swipeRowAtIndexPath` swipe far enough to reveal 'delete'?

### ISSUE THREAD

**Issue by jedidja** [kif-framework/KIF#658]
I have a cell in a `UITableView` that returns `YES` to `canEditRowAtIndexPath`. Manually swiping in the simulator works and shows a Delete button.

Calling `[tester swipeRowAtIndexPath: inTableView: inDirection:KIFSwipeDirectionLeft]` appears to only "tap" the cell. I can't see any visible sign of swiping or the text moving at all. I can verify that KIF can identify the cell, as the `[tester waitForViewWithAccessibilityLabel]` step passes (and the appropriate cell does scroll into view).

**Comment by jedidja** [comment]
Oh. There is `swipeRowAtIndexPath`. Oops!

**Comment by phatmann** [comment]
I just verified that the `testSwipingRows` test in the Table View tests (from the KIF unit tests) passes:

    UITableView *tableView;
    [tester waitForAccessibilityElement:NULL view:&tableView withIdentifier:@"TableView Tests Table" tappable:NO];
    [tester swipeRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0] inTableView:tableView inDirection:KIFSwipeDirectionLeft];
    [tester tapViewWithAccessibilityLabel:@"Delete"];

So there must be something different about your situation. Which version of iOS are you using? Are you using the iPad or iPhone simulator? Is there anything about your UITableView that is not standard?

**Comment by jedidja** [comment]
@phatmann Speaking of the unit tests, I wanted to run them locally but get a lot of errors in Xcode 6 about older testing framework. Are there instructions somewhere about how to run these in Xcode 6? 

- I will dig into if there is anything non-standard about the `UITableView` (I know we are adding the new cells programmatically if that makes a difference.) 
- I am testing this on the iPhone simulator using an iPhone 4s and iOS 8.3. Apologies for forgetting to include basic info in the original question.

**Comment by phatmann** [comment]
The unit tests work fine locally for me in Xcode 6.3. I do get a deprecation warning about using OCUnit but that can be acknowledged and cleared. I do not see any build errors.

**Comment by jedidja** [comment]
@phatmann Ok. Just tried doing a "Clean build folder" and then "Test" and now the tests are running merrily away. I swear it didn't work before! And the swipe to delete test does pass. 

Hmm. I guess there's something wrong/weird with our UI then. I'll keep researching it and if I can figure out why will I will re-open and leave a comment. Thanks for checking in on this.
