### ISSUE TITLE
Inject dependency into viewcontroller?

### ISSUE THREAD

**Issue by drhr** [kif-framework/KIF#660]
I need to inject different dependencies into different tests. For example, my view controller by default inits with a concrete class that calls a remote service. My unit tests are able to inject stub classes that automate those remote services and vary the expected responses. So  a Login service might have an "Accepting" stub that immediately returns a successful login response, and perhaps a "Rejecting" stub to simulate failure.

With KIF, I can't seem to figure out how to get access to the view controllers that are actually launching, and what is actually being inspected by KIF by when I try to access the views by their accessibility labels.

If I try to use `runBlock` to set up a rootViewController on the window, it doesn't seem to work, and the test case carries on using the default  concrete class within my UIViewController that performs remote functions. Obviously I don't want this.  I get the argument that it's not what users are seeing... but ultimately, I need integration tests that work across the boundaries of my application architecture WHILE using stubs (or not using stubs, either way - the framework shouldn't necessarily care, should it?).

Any thoughts on how to achieve this?

**Comment by phatmann** [comment]
Do you need access to the view controllers as the app is launching. If not, can you just walk the view controllers hierarchy in `beforeAll` and install the stub classes?

**Comment by drhr** [comment]
Yeah that seems to make the most sense.  I just wasn't sure if there was an api for it that would be more appropriate. I tried a ViewController extension class from somewhere else on github only to see my storyboard initializing two or three times and was very confused..
