### ISSUE TITLE
Repetitive loading of non-visible cells

### ISSUE THREAD

**Issue by albertbori** [kif-framework/KIF#661]
Something interesting (and new) has started happening in my tests. 

KIF automator spends a lot of time on one of my table views (whose table cells each contain a collection view). So, I added some logs to try and figure out what's taking so long. I added `Loading row [n]...` to each time the `tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath)` method was called. When I checked the log results, I found some interesting things: http://pastebin.com/kQiLw1qd

You'll notice 2 things about this log dump:
1. There are lots of errors regarding flow layout. I assume this to be benign since the not-visible cell that KIF is attempting to grab probably has a frame of 0,0,0,0 and UIKit is complaining about trying to draw the `UICollectionView` with those dimensions.
2. KIF iterated through the non-visible rows **88 times** for a single load of that table...

The latter of the issues is what concerns me. Whatever process is being kicked off to iterate through the rows is getting thrown for a loop.

**Comment by phatmann** [comment]
There have been various bug reports about this kind of looping, but no one has been able to come up with a failing unit test to demonstrate the issue. If you can isolate the failing code I would be *much* obliged!

**Comment by phatmann** [comment]
Possibly related to #464.
