### ISSUE TITLE
Build Fail only for physical device on commit: aa97c5d746

### ISSUE THREAD

**Issue by satchnut** [kif-framework/KIF#662]
After upgrading using pods, I now get...

/Users/awhitt/jolt-ios/Jolt/Pods/Headers/Public/KIF/KIFUITestActor.h:13:9: 'UIView-Debugging.h' file not found

when building to a device (ios 8.3 / 8.4); strangely, building on the simulator (ios 8.3) works just fine. I don't see anything wrong with the imports / compile sources. I'm using Xcode 6.3. I've tried all the obvious things: cleaning, deleting derived data folder, restarting xcode, restarting my mac, whittling my test program down to bare-bones, rebuilding the pods, asking the office xcode guru, etc., etc., etc...

I'm baffled. I doubt this is purely KIF-related, but has anyone seen this?  

(Apologies if my post is sloppy - I'm new here)

**Comment by phatmann** [comment]
`UIView+Debugging.h` was mistakenly in the Project headers section. I moved it to the Public section (4c3ad0a4). Give it another shot.

**Comment by satchnut** [comment]
The error remains. I ran a pod install (I'm using cocoapods ver. 0.37.1),
re-cleaned, restarted, etc., but the Pods project's Build Phases -> Headers
section shows 25 Project files with no Public or Private files. I manually
moved UIView-Debugging.h to Public, but that didn't seem to fix anything.

**Comment by phatmann** [comment]
Well, you are certainly right that my change to the KIF project file would not affect the CocoaPods installation. I just did a pod install and I see that UIView+Debugging is not in Pods/Headers/Public like it should be. I am figuring out why now.

**Comment by phatmann** [comment]
Heh, pretty obvious now: the Podspec specifies that only `-KIFAdditions` files should be public. I will fix that now.

**Comment by phatmann** [comment]
Ironically KIFUITestActor did not depend on `UIView+Debugging.h`, so I also removed the import.

**Comment by phatmann** [comment]
I pushed version 3.2.3 with this fix.

**Comment by satchnut** [comment]
Thanks, phatman!
