### ISSUE TITLE
Add SwipeScreenAtPoint

### ISSUE THREAD

**Issue by anwol004** [kif-framework/KIF#666]
Hello can you add the method swipeScreenAtPoint:(CGPoint)screenPoint inDirection:(KIFSwipeDirection)direction ?

Here is the Code:

- (void)swipeScreenAtPoint:(CGPoint)screenPoint inDirection:(KIFSwipeDirection)direction
{
    const NSUInteger kNumberOfPointsInSwipePath = 20;
    
    [self runBlock:^KIFTestStepResult(NSError **error) {
        
        // Try all the windows until we get one back that actually has something in it at the given point
        UIView *view = nil;
        for (UIWindow *window in [[[UIApplication sharedApplication] windowsWithKeyWindow] reverseObjectEnumerator]) {
            CGPoint windowPoint = [window convertPoint:screenPoint fromView:nil];
            view = [window hitTest:windowPoint withEvent:nil];
            
            // If we hit the window itself, then skip it.
            if (view != window && view != nil) {
                break;
            }
        }
        
        KIFTestWaitCondition(view, error, @"No view was found at the point %@", NSStringFromCGPoint(screenPoint));
        
        KIFDisplacement swipeDisplacement = KIFDisplacementForSwipingInDirection(direction);
        
        // This is mostly redundant of the test in _accessibilityElementWithLabel:
        CGPoint viewPoint = [view convertPoint:screenPoint fromView:nil];
        [view dragFromPoint:viewPoint displacement:swipeDisplacement steps:kNumberOfPointsInSwipePath];
        
        return KIFTestStepResultSuccess;
    }];
}

**Comment by Benuuu** [comment]
@anwol004 why not make a pull request with your change?

**Comment by phatmann** [comment]
@anwol004  I know putting together a pull request seems like a pain, but it really is the right way to go. Give it a try, and I will help you through any pain points. Once you have done one, you will want to do a hundred more. It is very satisfying!

One tip: after you fork KIF, make a new branch for your changes.

**Comment by anwol004** [comment]
Thanks 

https://github.com/kif-framework/KIF/pull/673

**Comment by phatmann** [comment]
Closed because PR #673 was submitted.
