### ISSUE TITLE
DBRestClient delegate never called

### ISSUE THREAD

**Issue by drklaushoffmann** [kif-framework/KIF#667]
I use a view to show the content of my Dropbox account. For that I use the Dropbox SDK, initialize a DBRestClient with a call back delegate. The call back method contains meta data from Dropbox used to show the content.

Everything is fine when running the App in Debug or Release. When I use the KIF framework open the View to show the Dropbox content then the DBRestClient never calls the delegate.

Any idea?

**Comment by phatmann** [comment]
Where do you initialize the rest client with the delegate? Have you checked to see that the delegate is actually set?

**Comment by drklaushoffmann** [comment]
I set the delegate directly after I created the DBRestClient. The stage is the code worked when I run the App with out the KIF Framework. A similar issue I'm facing is that the Animation delegate (DidStopSelector) from UIView is never called when I use KIF (see below). I don't know if the two issues somehow related. 

        [UIView beginAnimations:@"FadeIn" context:nil];
        [UIView setAnimationDelegate:self];
        [UIView setAnimationDidStopSelector:@selector(presentAnimationDidStop:finished:context:)];
        [UIView setAnimationDuration:FADE_DURATION];        
        [UIView commitAnimations];

**Comment by phatmann** [comment]
Sorry to let this sit so long. Did you ever resolve it? I admit I have no ideas about how KIF could stop normal code flow from working, since it cranks the run loop like a normal app.
