### ISSUE TITLE
Add longPressPoint:(CGPoint)startPoint AndDragToPoint:(CGPoint)endPoint

### ISSUE THREAD

**Issue by parsatorb** [kif-framework/KIF#672]
I want to test pressing and hold at a point, and then dragging without letting go onto another point. So far there doesn't seem to be a way to do this using KIF

**Comment by mikelupo** [comment]
Inspired by code up at: http://www.raywenderlich.com/6567/uigesturerecognizer-tutorial-in-ios-5-pinches-pans-and-more

I have a crude version of what you're asking in my own fork. I intend for it to get submitted via a pull request, but not till we smooth out the issue with the drag end point. Or in other words, it does drag, but sort of "misses" where to drop. I need help with this from the KIF community. @phatmann???
You can look in DraggingTests.m and see how I'm using it.

Here's the method definition
```
 /*!
 @abstract Performs a long press starting with the points of a particular view (by its label) and ending with the CGPoint passed in.
 @discussion The view or accessibility element with the given label is searched for in the view hierarchy. If the element isn't found or isn't currently tappable, then the step will attempt to wait until it is. Once the view is present and tappable, touch (down) events are simulated in the center of the view or element and then the drag is performed.
 @param label The accessibility label of the element to tap.
 @param toPoint The CGPoint where you want the long press to end.
 @param steps how many steps it takes to complete the drag. More steps = slower drag.
 */
- (void)longPressAndDragViewWithAccessibilityLabel:(NSString *)label toPoint:(CGPoint) toPoint steps:(NSInteger) steps; **
```

**Comment by parsatorb** [comment]
I made a crude solution for my own project (sorry its private, can't share) but it was a 
    -(void)longPressPoint:(CGPoint)startPoint AndDragToPoint:(CGPoint)endPoint;
I had a problem where it would only drag half-way to the destination, so I ended up taking the difference of the points and doubling to create the destination point :S Anyone have a theory as to why it seems to "miss"

**Comment by phatmann** [comment]
@parsatorb, can you take a look at #676 and comment on what we need to do in order to fix it?

**Comment by parsatorb** [comment]
My crude solution (which is almost identical to what you have) was to replace line 501 in UIView-KIFAdditions.m with the following:
        [self dragFromPoint:startPoint toPoint:CGPointMake(2*endPoint.x-startPoint.x, 2*endPoint.y-startPoint.y)];

Not sure if the "only drags halfway" issue was a problem in your implementation as well, but I'll take a look at it over the weekend

**Comment by phatmann** [comment]
@parsatorb Your fix did not work in @mikelupo's code. I will see if I can fix it.

**Comment by mikelupo** [comment]
Thanks for taking the time to look at this.





-----Original Message-----

**Comment by phatmann** [comment]
Closing this and moving discussion to #676
