### ISSUE TITLE
Crash taking screenshot when window exists with window.bounds being all zero...{0,0,0,0}

### ISSUE THREAD

**Issue by mikelupo** [kif-framework/KIF#679]
Sometimes I get black screenshots where I expect to see an image of the app on the device. I actually caught a crash in the debugger on a few occasions (sorry no callstack). Upon inspection, it looks like window.bounds can have no width or height. In this case, KIF crashes. 
If I add the if(window.hidden) { continue } at the top of the it will skip this bogus window and successfully write the screenshot. Is it the better check to see if the window has good dimensions instead of being hidden. @phatmann Can you please comment on this? 

 UIGraphicsBeginImageContextWithOptions([[windows objectAtIndex:0] bounds].size, YES, 0);
    for (UIWindow *window in windows) {
		***if(window.hidden)  //I added this block of code checking for a good window.
		{
			continue;
		}***
        if ([window respondsToSelector:@selector(drawViewHierarchyInRect:afterScreenUpdates:)]) {
			[window drawViewHierarchyInRect: **window.bounds** afterScreenUpdates:YES];
        } else {
            [window.layer renderInContext:UIGraphicsGetCurrentContext()];
        }
    }

**Comment by mikelupo** [comment]
Got a call stack.
#0	0x222711e2 in CFGetTypeID ()
#1	0x25b3ca0c in _UICreateCGImageFromIOSurfaceWithOptionsAndRotation ()
#2	0x25c6078e in -[UIView _drawViewHierarchyInRect:] ()
#3	0x25c60a26 in __53-[UIView drawViewHierarchyInRect:afterScreenUpdates:]_block_invoke ()
#4	0x25c69528 in +[_UIReplicantView _pendingSnapshotOfTarget:snapshotBlock:] ()
#5	0x25c60946 in -[UIView drawViewHierarchyInRect:afterScreenUpdates:] ()
#6	0x00c2475e in -[UIApplication(KIFAdditions) writeScreenshotForLine:inFile:description:error:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Additions/UIApplication-KIFAdditions.m:138
#7	0x00c307ba in -[KIFTestCase writeScreenshotForException:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFTestCase.m:170
#8	0x00c30450 in -[KIFTestCase failWithException:stopTest:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFTestCase.m:150
#9	0x00c2f748 in -[KIFTestActor failWithError:stopTest:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFTestActor.m:180
#10	0x00c2f208 in -[KIFTestActor runBlock:complete:timeout:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFTestActor.m:113
#11	0x00c2f2ba in -[KIFTestActor runBlock:complete:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFTestActor.m:119
#12	0x00c344ee in -[KIFSystemTestActor waitForNotificationName:object:whileExecutingBlock:complete:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFSystemTestActor.m:38
#13	0x00c34218 in -[KIFSystemTestActor waitForNotificationName:object:whileExecutingBlock:] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/Frameworks/KIF/Classes/KIFSystemTestActor.m:24
#14	0x00c05612 in -[ScrubbedUITests test002ATestCase] at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/MyUIAutomationTests/ScrubbedUITests.m:322
#15	0x22370664 in __invoking___ ()
#16	0x2229b48c in -[NSInvocation invoke] ()
#17	0x00c83a4c in -[XCTestCase invokeTest] ()
#18	0x00c83d30 in -[XCTestCase performTest:] ()
#19	0x00c8cf0a in -[XCTest run] ()
#20	0x00c82848 in -[XCTestSuite performTest:] ()
#21	0x00c8cf0a in -[XCTest run] ()
#22	0x00c82848 in -[XCTestSuite performTest:] ()
#23	0x00c8cf0a in -[XCTest run] ()
#24	0x00c82848 in -[XCTestSuite performTest:] ()
#25	0x00c8cf0a in -[XCTest run] ()
#26	0x00c7fa94 in __25-[XCTestDriver _runSuite]_block_invoke ()
#27	0x00c8a55e in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
#28	0x00c7f99e in -[XCTestDriver _runSuite] ()
#29	0x00c80402 in -[XCTestDriver _checkForTestManager] ()
#30	0x00c8fbaa in +[XCTestProbe runTests:] ()
#31	0x2309f36c in __NSFireDelayedPerform ()
#32	0x22331ede in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
#33	0x22331a5a in __CFRunLoopDoTimer ()
#34	0x2232fcaa in __CFRunLoopRun ()
#35	0x2227c200 in CFRunLoopRunSpecific ()
#36	0x2227c012 in CFRunLoopRunInMode ()
#37	0x29b5b200 in GSEventRunModal ()
#38	0x25a20a58 in UIApplicationMain ()
#39	0x00163d36 in main at /Users/menotyou/Documents/git-p4/myGitRepo/Scrubbed Appname/Scrubbed Appname/main.m:16

**Comment by mikelupo** [comment]
https://github.com/kif-framework/KIF/pull/686

**Comment by phatmann** [comment]
Fixed via #686
