### ISSUE TITLE
Testing on Simulator fails with IOKit.framework being ignored for lacking i386 slice

### ISSUE THREAD

**Issue by tGilani** [kif-framework/KIF#681]
I have been testing, successfully, using KIF for my iOS app. However, today when I tried to run tests on simulator, it failed with following error.

![screen shot 2015-06-22 at 3 43 38 pm](https://cloud.githubusercontent.com/assets/1927046/8295038/bb537f22-18f5-11e5-94e6-3a14b84c28e3.png)

It appears the xcode ignore the IOKit file for lacking i386 framework.

I copied the framework from Xcode 6.3.2's frameworks directory.

**Comment by phatmann** [comment]
Please search this repo for issues around IOKit. You will probably find the tips you need to make this work.

**Comment by tGilani** [comment]
Interesting findings, the IOKit.framework must be copied from `iPhoneSimulator` SDK folder inside Xcode instead of 'iphoneos` folder. Copying for `iphoneos` only allows testing on device not on SDK>
