### ISSUE TITLE
Testing paused 

### ISSUE THREAD

**Issue by GusevAndrey** [kif-framework/KIF#682]
Perform configuration according to ReadMe.
Especially "Final Test Target Configurations"-part. Set Bundle Loader to $(BUILT_PRODUCTS_DIR)/MyApplication.app/MyApplication and Test Host to $(BUNDLE_LOADER).

But when I trying to run a test app just starts and nothing else. Xcode says: index testing | paused.
Brake points aren't fires, log is empty.

What am I doing wrong?

Thanks in advance

**Comment by phatmann** [comment]
Can you give us more information? What do you mean by "index testing | paused"?

**Comment by GusevAndrey** [comment]
Sorry for not being specific enough.

I run test, application just starts, then nothing happens and Xcode's top bar says:

*"(2) Testing..."*

And, if click on it, says:

*"Indexing Text | Paused"*

And thats it.

**Comment by phatmann** [comment]
If you set a breakpoint in your tests, is that breakpoint hit?

**Comment by GusevAndrey** [comment]
No.
Not a breakpoint neither an NSLog in all methods. Looks like the tests isn't running at all.

**Comment by phatmann** [comment]
Can you try a traditional non-KIF XCTest unit test and see if that runs?

**Comment by GusevAndrey** [comment]
Yes it runs.

**Comment by GusevAndrey** [comment]
I mean, I have different target with lots of XCTest unit tests and it's running fine.
Different target with KIF tests is not.

**Comment by GusevAndrey** [comment]
Tried to add another XCTest unit test file to KIF tests bundle. 
Tests are not run anyway (not KIF neither XCTest), but "Indexing Text | Paused" is gone and
there error log in occurred in console:

*Error loading /private/var/mobile/Containers/Data/Application/8B7A8A26-77EE-4847-B85F-8EEF0C6D68B2/tmp/Functional Tests.xctest/Functional Tests:*  *dlopen(/private/var/mobile/Containers/Data/Application/8B7A8A26-77EE-4847-B85F-8EEF0C6D68B2/tmp/Functional Tests.xctest/Functional Tests, 262): no suitable image found.*  

*Did find:*
    */private/var/mobile/Containers/Data/Application/8B7A8A26-77EE-4847-B85F-8EEF0C6D68B2/tmp/Functional Tests.xctest/Functional Tests: code signature invalid for '/private/var/mobile/Containers/Data/Application/8B7A8A26-77EE-4847-B85F-8EEF0C6D68B2/tmp/Functional Tests.xctest/Functional Tests'*

*DevToolsBundleInjection: Error loading bundle '/private/var/mobile/Containers/Data/Application/8B7A8A26-77EE-4847-B85F-8EEF0C6D68B2/tmp/Functional Tests.xctest'*

After removing XCTest file and cleaning the project nothing changed (still have logs and tests are not run)

**Comment by huynguyen** [comment]
@GusevAndrey are you testing on a device? Those errors are usually a code signing problem.

**Comment by GusevAndrey** [comment]
Yes! I run tests on device and faced that error. When I tried it on simulator it runs perfect.
That is a progress) Now I have just to figure out what is wrong with code signing...
