### ISSUE TITLE
NSInvalidArgumentException hit in UIView-KIFAdditions.m

### ISSUE THREAD

**Issue by mikelupo** [kif-framework/KIF#683]
failed: caught "NSInvalidArgumentException", "-[NSISRestrictedToNonNegativeVariable setTextDelegate:]: unrecognized selector sent to instance 0x17483cb60"
(
    0   CoreFoundation                      0x00000001856b42f4 <redacted> + 160
    1   libobjc.A.dylib                     0x0000000196cc00e4 objc_exception_throw + 60
    2   CoreFoundation                      0x00000001856bb3a4 <redacted> + 0
    3   CoreFoundation                      0x00000001856b8154 <redacted> + 928
    4   CoreFoundation                      0x00000001855baccc _CF_forwarding_prep_0 + 92
    5   UIKit                               0x0000000183aa93a0 <redacted> + 216
    6   UIKit                               0x0000000183aad3c8 <redacted> + 548
    7   UIKit                               0x0000000183aaeabc <redacted> + 156
    8   GW_AutomationTests          0x0000000100d4e7b0 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 1772
    9   GW_AutomationTests          0x0000000100d4eba8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 2788
    10  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    11  GW_AutomationTests          0x0000000100d4e3b8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 756
    12  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    13  GW_AutomationTests          0x0000000100d4e3b8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 756
    14  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    15  GW_AutomationTests          0x0000000100d4e3b8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 756
    16  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    17  GW_AutomationTests          0x0000000100d4e3b8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 756
    18  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    19  GW_AutomationTests          0x0000000100d4e3b8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 756
    20  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    21  GW_AutomationTests          0x0000000100d4e3b8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 756
    22  GW_AutomationTests          0x0000000100d4e090 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 88
    23  GW_AutomationTests          0x0000000100d4d978 -[UIView(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 244
    24  GW_AutomationTests          0x0000000100d4aa14 -[UIApplication(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 432
    25  GW_AutomationTests          0x0000000100d5ebec __74-[KIFUITestActor waitForAbsenceOfViewWithAccessibilityLabel:value:traits:]_block_invoke + 480
    26  GW_AutomationTests          0x0000000100d56310 -[KIFTestActor tryRunningBlock:complete:timeout:error:] + 180
    27  GW_AutomationTests          0x0000000100d565fc -[KIFTestActor runBlock:complete:timeout:] + 136
    28  GW_AutomationTests          0x0000000100d56724 -[KIFTestActor runBlock:complete:] + 152
    29  GW_AutomationTests          0x0000000100d56820 -[KIFTestActor runBlock:] + 76
    30  GW_AutomationTests          0x0000000100d5e9b0 -[KIFUITestActor waitForAbsenceOfViewWithAccessibilityLabel:value:traits:] + 236
    31  GW_AutomationTests          0x0000000100d5e8a4 -[KIFUITestActor waitForAbsenceOfViewWithAccessibilityLabel:traits:] + 100
    32  GW_AutomationTests          0x0000000100d5e820 -[KIFUITestActor waitForAbsenceOfViewWithAccessibilityLabel:] + 80
    33  GW_AutomationTests          0x0000000100d449fc -[FooViewTests test012VideoGoesFullScreenByLandscape] + 1680
    34  CoreFoundation                      0x00000001856ba100 <redacted> + 144
    35  CoreFoundation                      0x00000001855b62fc <redacted> + 296
    36  XCTest                              0x0000000100db1c90 -[XCTestCase invokeTest] + 328
    37  XCTest                              0x0000000100db1eec -[XCTestCase performTest:] + 204
    38  XCTest                              0x0000000100dbba3c -[XCTest run] + 312
    39  XCTest                              0x0000000100db0a10 -[XCTestSuite performTest:] + 396
    40  XCTest                              0x0000000100dbba3c -[XCTest run] + 312
    41  XCTest                              0x0000000100db0a10 -[XCTestSuite performTest:] + 396
    42  XCTest                              0x0000000100dbba3c -[XCTest run] + 312
    43  XCTest                              0x0000000100db0a10 -[XCTestSuite performTest:] + 39
    44  XCTest                              0x0000000100dbba3c -[XCTest run] + 312
    45  XCTest                              0x0000000100dad5d4 __25-[XCTestDriver _runSuite]_block_invoke + 60
    46  XCTest                              0x0000000100db8bec -[XCTestObservationCenter _observeTestExecutionForBlock:] + 188
    47  XCTest                              0x0000000100dad4f8 -[XCTestDriver _runSuite] + 288
    48  XCTest                              0x0000000100dadfbc -[XCTestDriver _checkForTestManager] + 292
    49  XCTest                              0x0000000100dbedf0 +[XCTestProbe runTests:] + 228
    50  Foundation                          0x00000001865a8180 __NSFireDelayedPerform + 424
    51  CoreFoundation                      0x000000018566c12c <redacted> + 28
    52  CoreFoundation                      0x000000018566bddc <redacted> + 888
    53  CoreFoundation                      0x0000000185669828 <redacted> + 1372
    54  CoreFoundation                      0x00000001855952d4 CFRunLoopRunSpecific + 396
    55  GraphicsServices                    0x000000018ec6b6fc GSEventRunModal + 168
    56  UIKit                               0x000000018a15afac UIApplicationMain + 1488
    57  MyAppUITest                         0x0000000100193208 main + 184
    58  libdyld.dylib                       0x000000019733ea08 <redacted> + 4
)

**Comment by phatmann** [comment]
What led to the exception?
