### ISSUE TITLE
Relaunch / put in a spicific state the application before each test

### ISSUE THREAD

**Issue by GusevAndrey** [kif-framework/KIF#694]
Hi!
As far as I know KIF tests are linked to the running app and stopping the app means stop the tests.
But it isn't good practice to rely on previous tests results, tests should be independent. 
So there's still a need to have a reference point from which to start a next test.

So is there any possibility to "relaunch" application before each test / all tests in class? 
How it's mean to work in general?

Second part of the question: do I exactly need it?)
I mean may be KIF expected to be used in some different way at all?

thx in advance.

**Comment by phatmann** [comment]
The new UI testing kit in Xcode 7 will relaunch the app before each test suite. It does this trick by running the tests in a separate process. Not sure if you can use that feature with KIF or not.

Xcode 6 does not provide this capability. Instead you can provide a helper method in your tests that "resets" the app to its initial launch state.

**Comment by GusevAndrey** [comment]
Thx.

**Comment by fangmobile** [comment]
stumped upon here. Don't KIF use a unit test target? How the new UI test kit in Xcode 7 help this?
Is there any solution comes from KIF?
Everyone using KIF just run all of there tests sequentially? One  test fails the whole thing stop?

**Comment by phatmann** [comment]
KIF runs in a unit test target, not a UI test. If one test fails, the app will likely not be in a testable state at that point, and it makes sense for the tests to stop.

**Comment by antonypoderechin** [comment]
I have some state in application(in-memory flags, different settings, authorization etc) some of tests can change state of application so when i write test i should know which tests were executed previously to know exactly in witch state my app is. To prevent this it is cool to restart app before each test. Can it be done with KIF?
