### ISSUE TITLE
Updating from 3.2.2 to 3.2.3 stops running on CI system

### ISSUE THREAD

**Issue by DanielCreagh** [kif-framework/KIF#696]
On version 3.2.2 we had it building and running the tests on Circle CI.

Due to frequent random failures, I decided to update to latest version of KIF to see if it helps.  It seems it did the opposite and now doesn't run the tests at all.

The project is using Swift with bridging header.  I compared with previous logs and it seems to halt completely and when 3.2.2 outputs this log: -

```
KIFTester loaded
```

the latest version simply hangs before it gets to this. (I run the tests locally with 3.2.3 and it works fine.)

Any idea's?

**Comment by phatmann** [comment]
How did you install KIF in Circle CI?

**Comment by DanielCreagh** [comment]
You don't need to install it in Circle CI.

I pod installed KIF into my project locally (updated the previous pod), ran all the functional tests locally then pushed to the Github repository. Once pushed to Github circle clones the repo and executes a command line command to build and test using xcode on Circles on machine.

**Comment by phatmann** [comment]
Whenever any questions like this have come up, it always seems to be due to a "silent" error that halts the tests but does not display in the console.If you can try and get more debugging output leading up to the halt that might be helpful.
