### ISSUE TITLE
iOS 9: deactivateAppForDuration: fails

### ISSUE THREAD

**Issue by TBonnin** [kif-framework/KIF#703]
When executing `[tester deactivateAppForDuration:N]` the app is properly closed but doesn't reopen.

More info:
`deactivateAppForDuration:N` fails with the following error `kUIAExceptionUnexpected", "-[UIAElementNil _prepareForAction:]: unrecognized selector sent to instance`

I tried to run a simple UIAutomation script with target.deactivateAppForDuration(5); and the same error is thrown. Probably a bug in iOS 9. I have filled a radar, no response from Apple so far.

**Comment by rKrums** [comment]
Yep, just encountered this one too.

Checked it on iOS 8.4.1 - works fine. 
That is something with iOS 9.

**Comment by phatmann** [comment]
@rKrums, thanks for the update. Any ideas for a workaround?
