### ISSUE TITLE
iOS 8: Unable to use choosePhotoInAlbum

### ISSUE THREAD

**Issue by Nomad00** [kif-framework/KIF#705]
Unless I am using it incorrectly, it appears that `choosePhotoInAlbum:atRow:column:` is not working as intended on iOS 8. 

I get "Album picker is not enabled for interaction" because `isUserInteractionActuallyEnabled` returns `false` because `isNavigationItemView` is returning `false`. 

The cause of this appears to be that the `view` that is pulled to work with is a `UITextFieldLabel` (the one containing the name of the album, 'Moments' in my case). As opposed to on iOS 7 (which works), where the `view` in question is a `PUAlbumListTableViewCell` instead.

Thoughts?

**Comment by phatmann** [comment]
I just tried the `testPickingAPhoto` test in the KIF unit test suite and it passed in iOS 8. Any idea why your situation is different?

**Comment by paulz** [comment]
We just had this failure on Jenkins: `Album picker is not enabled for interaction`
even we have entitlements file that enables photos access.
