### ISSUE TITLE
UIAutomation Framework does not work with an actual device

### ISSUE THREAD

**Issue by mikelupo** [kif-framework/KIF#707]
Creating a new defect per @phatmann and mentioning @joemasilotti per his recommendation.
Also this may be historically related to #518 

**The problem:**
When calling any of the UIAutomationHelper class methods the following is seen in the console repeated hundreds of times.
**UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.**

**TO REPRODUCE**
note: The bug does not occur on the simulator.

1) Clone: git@github.com:mikelupo/KIF.git
2) Change to branch: reproduce_518
3) Load the KIF.xcodeproj into XCode 6.4
4) Connect up your iOS device. (This was reproduced on a REAL iPhone 5s.).
5) In XCode test navigator, select the BackgroundTests suite of tests and run them.
6) The Test Host app will load on the device under test and the test will begin.
7) The test will not deactivate the app, whilst in the console log the message can be seen (hundreds of times): "Test Host[1179:178394] UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings."

**Confirming the device settings:**
1) Developer > Enable UI Automation turned ON in the device settings.
2) Running on a Debug build (as opposed to Release).
3) Building using an Apple developer profile (as opposed to a distribution profile). I can step through code in the debugger as well. If it were a distribution build, debugging would not be possible.
4) Scheme is set to run in debug. Profiling is also set to debug (as suggested by this Stackoverflow post)
5) KIF tests are contained in a test target that depends on the app (target) being tested. Both targets are debug.

Curiously...is there anything in the following link that can help us?
https://github.com/TestingWithFrank/PublicAutomation/tree/master/PublicAutomation

**More observations:**
It was noticed that in the UIAutomation.framework binary, there is a check to see if UIAutomation is enabled on the device. I surmise that the method call is returning NO. Permission issue?????

int __UIAutomationEnabled() {
rax = CFPreferencesGetAppBooleanValue(@"UIAutomationEnabled", @"com.apple.UIAutomation", var_9);
if (var_9 == 0x0) {
__UIATargetIsInternal();
CFPreferencesSetAppValue(@"UIAutomationEnabled", *_kCFBooleanTrue, @"com.apple.UIAutomation");
CFPreferencesSynchronize(@"com.apple.UIAutomation", *_kCFPreferencesCurrentUser, *_kCFPreferencesAnyHost);
rax = 0x1;
}
rax = rax & 0xff;
return rax;
}

Also, the following call:
CFPreferencesGetAppBooleanValue(CFSTR("UIAutomationEnabled"), CFSTR("com.apple.UIAutomation"), YES);
returns NO

Can we somehow override this?

**Comment by phatmann** [comment]
@mikelupo Thanks for the detailed status report. Now let's see if @joemasilotti can chime in.

**Comment by joemasilotti** [comment]
I've never had any of the private UIAutomation APIs work on a device. Unfortunately I wouldn't even know where to begin, I haven't messed around there in quite some time. 

I can, however, comment on the PublicAutomation link you mentioned. That is where my idea for linking against the framework came to be. I've had a few Twitter discussions with Pete, the maintainer, about the same issues. He was stumped then, as well.

Sorry I can't be of more help.

**Comment by mikelupo** [comment]
Joe,
Thanks for your comments on this topic.

To all, 
I think it's safe to say that we are all interested in non-jail broken devices....but I have to wonder if a jail broken device will suffer the same fate? 
Any comments or experiences shared are welcomed.

**Comment by sirnacnud** [comment]
I am running in to this same problem by enabling acknowledgeSystemAlert and then trying to use it on my device. I'm running iOS 8.4.1 and using an iPhone 5.

**Comment by irshad365** [comment]
I just came across this post. @mikelupo: In jailbroken device, we won't face such issues. Even if you get this error, you can easily fix this by 
1. manually editing "com.apple.UIAutomation.plist". 
You can find this plist in "/var/mobile/Library/Preferences/" & "/var/root/Library/Preferences/".
2. If you have a launchdeamon plist, you can solve this by adding proper user in it.  added a sample below on how to add
	<key>UserName</key>
	<string>mobile</string>

**Comment by zhaodazhou** [comment]
I use UIAutomation private API on jailbroken, and manually editing "com.apple.UIAutomation.plist".
Then, run the jailbroken, the result is not reporting "UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.", but report "AXError: Could not auto-register for pid status change. Failed to enable accessiblity, kAXErrorServerNotFound."
I can not fix the problem, anyone have any clue.
Thanks.

**Comment by AllocAndInit** [comment]
@phatmann  @joemasilotti  I have the same problem with @mikelupo ,when I try to call the acknowledgeSystemAlert method on a device , Is now has any solution to solve this problem?
I would appreciate that , thanks a lot

**Comment by yanmingsysu** [comment]
@justinseanmartin has this issue been solved? I get stuck in the same problem now
