### ISSUE TITLE
Feature Request: KIF Asserts like XCTAssert

### ISSUE THREAD

**Issue by mikelupo** [kif-framework/KIF#709]
Write some KIF asserts that behave the same way as the XCTAsserts, but when there is a failure, cause the screenshot to be written.
When using XCTAssert and the test fails, no screenshot is taken.

For example:
KIFAssertTrue(expression...,);
etc...

Maybe I'm missing something and KIF already has this kind of functionality built in?

Thanks in advance

**Comment by phatmann** [comment]
@mikelupo, when a test fails for any reason a screenshot should be written. Is this not working for you, or am I misunderstanding the request?

**Comment by mikelupo** [comment]
Hi,
The problem is that when I want to use an XCT style assert that I don't get a screenshot because I suppose the XCTest framework does not do that. 


So I had the bright idea that maybe we could do something like that in KIF for the sole reason of grabbing a screenshot in one line.
This would lend KIF Framework to unit/system style testing.


Relevance:
I have some tests that use KIF to navigate to a specific place in the UI.
Once I navigate there, I use a MOCK to introduce an error response to a request.
The expectation is a BUNCH of dynamic UI disappears or does not appear at all.
Yes, I could do if [! tryFindingViewWithAccessibilityLabel:@"SomeView" ]
{
   [tester failWithException myNewException ];
}
 
Sometimes in this case, waitForAbsence could also be used but not reliably.
Often times, I'm having to get cells from indexpaths.
and then using that indexPath on a row/section that is no longer available will throw.
So that's is sometimes the thing I test for 
XCTAssertThrow(expressionThatThrows...)


If this fails, I want to see why I had a good indexpath when I expected a thrown exception.


Ultimately, I'm wanting to use KIF for a unit style test with UI with the convenience of a screenshot.
Crazy? maybe! That's why the ask is a feature request.


Thanks for listening.
Mike



-----Original Message-----

**Comment by phatmann** [comment]
@mikelupo did you know what you can call `writeScreenshotForException` from a test? Is that enough to do what you want?
