### ISSUE TITLE
Recommended way to run KIF tests when using the .app and .Xctest folders

### ISSUE THREAD

**Issue by arpras** [kif-framework/KIF#714]
Hi all,
I am beginning to write KIF tests. I have built and generated the APP.app and TEST.xctest folders. Now I am going to transfer these files (zipped folders) remotely and extract and want to run the KIF tests on simulator/device.

Is there any recommended way?

Thanks very much.

**Comment by phatmann** [comment]
@arpras, this is more a question about unit tests in general and not about KIF. You asked the same question in the KIF forum and @mikelupo was kind enough to [answer you](https://groups.google.com/forum/#!topic/kif-framework/0anXM4TckT8). You might also want to try stackoverflow.com.
