### ISSUE TITLE
[Objective-c] KIF and Quick/Nimble

### ISSUE THREAD

**Issue by tomomura** [kif-framework/KIF#719]
I found that I had to add a category to Quick's `QuickSpec`

``` objc
@interface QuickSpec (WithObjC) <KIFTestActorDelegate>

@end
```

``` objc
@implementation QuickSpec (WithObjC)

- (void)failWithException:(NSException *)exception stopTest:(BOOL)stop
{
  self.continueAfterFailure = !stop;
  [self recordFailureWithDescription:exception.description
                              inFile:exception.userInfo[@"SenTestFilenameKey"]
                              atLine:[exception.userInfo[@"SenTestLineNumberKey"] integerValue]
                            expected:YES];
}

- (void)failWithExceptions:(NSArray *)exceptions stopTest:(BOOL)stop
{
  NSException *lastException = exceptions.lastObject;
  for (NSException *exception in exceptions) {
    [self failWithException:exception stopTest:(exception == lastException ? stop : NO)];
  }
}
```

``` objc
QuickSpecBegin(LoginViewSpec)

describe(@"this is describe block", ^{
  it(@"this test is example", ^{
    [tester enterText:@"user@example.com" intoViewWithAccessibilityLabel:@"Login User Name"]; // not exist
  });
});

QuickSpecEnd
```

but, all examples is executed.
is it possible to use Quick with KIF?

Thanks for the help.
- Xcode 6.3.2
- iOS 7 or later
- Quick 0.3.1
- Nimble 1.0.0

**Comment by phatmann** [comment]
A few things:
* In the latest KIF release, the exception keys changed to "FilenameKey" and "LineNumberKey".
* I have not used Quick and I do not know it works with KIF or not. Can you determine why you need to add the extra methods above?

**Comment by tomomura** [comment]
@phatmann 

Thank you for your reply.

> In the latest KIF release, the exception keys changed to "FilenameKey" and "LineNumberKey".

I'm not used latest KIF.
So, these values exists in SenTestFilenameKey and SenTestLineNumberKey

> Can you determine why you need to add the extra methods above?

I added the extra methods based on [this](https://github.com/kif-framework/KIF#use-with-other-testing-frameworks).

probably, [this](https://github.com/Quick/Quick/commit/ee5538a744b52f70b8fb39ed68f1f9d864f53cfd) commit is relation.

**Comment by phatmann** [comment]
Thanks for the explanation. So what is the issue that you are running into?
