### ISSUE TITLE
Tests failing with unrecognized selector with Xcode 7

### ISSUE THREAD

**Issue by sumitagarwal** [kif-framework/KIF#721]
Almost all of my tests except a few are failing with the following error. The error was not there before Xcode 7 . I have checked all the configuration and other settings and the same tests are working fine on the test server which has the previous Xcode. 

UIAccessibilityElement _addAccessibilityElementsAndOrderedContainersWithOptions:toCollection:]: unrecognized selector sent to instance 0x7f86b6259d30

**Comment by goyalankit** [comment]
+1

**Comment by phatmann** [comment]
Can I see the backtrace? I would like to know what calls led to this error.
