### ISSUE TITLE
EXC_BAD_ACCESS in UIView (KIFAdditions) IOS 9

### ISSUE THREAD

**Issue by sellingsolutions** [kif-framework/KIF#729]
Hi!

Here are the steps that re-produce issue https://github.com/kif-framework/KIF/issues/13 for me with ios 9.

1) I installed El Capitano and the latest xcode on a new mac mini
2) I cloned my project from github + pod setup etc
3) Tried to run my application tests with the default iOS 9 simulator, got the same crash as described in issue https://github.com/kif-framework/KIF/issues/13
4) I installed the iOS 8.1 Simulator in Xcode 7
5) Ran the tests again, now with the 8.1 simulator, everything is working just fine

**Comment by mciarlo** [comment]
Having a similar issue with Xcode and iOS 9.1. It appears to be similar to an older issue documented here: https://github.com/kif-framework/KIF/pull/582

My stack is remarkably similar:
<img width="307" alt="screen shot 2015-11-02 at 10 42 19 am" src="https://cloud.githubusercontent.com/assets/378406/10886166/e47745d4-814e-11e5-8180-1c9d1c6578c7.png">

**Comment by phatmann** [comment]
Is this specific to 9.1 or does it happen in 9.0 as well?

**Comment by mciarlo** [comment]
@phatmann I was using KIF 3.2 not 3.3. I've updated and this issue was resolved. I have a different set of issues now (unable to find views that I can see using the accessibility inspector).

**Comment by phatmann** [comment]
Glad KIF 3.3 fixed it. Please file a new issue if you have any problems you cannot resolve.
