### ISSUE TITLE
Build error when running c++ tests in KIF

### ISSUE THREAD

**Issue by snoopying** [kif-framework/KIF#733]
System macro is causing issues when running C++ tests in KIF 

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/locale:192:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:131:9: error: expected unqualified-id

using ::system;

```
    ^
```

In file included from /Users/test/Documents/iOS/Tests/test.mm:19:

In file included from /Users/test/Library/Developer/Xcode/DerivedData/frxusjxqwcj/Build/Products/Debug-iphonesimulator/include/KIF/KIF.h:12:

/Users/test/Library/Developer/Xcode/DerivedData/fwcj/Build/Products/Debug-iphonesimulator/include/KIF/KIFSystemTestActor.h:13:16: note: expanded from macro 'system'
# define system KIFActorWithClass(KIFSystemTestActor)

```
           ^
```

In file included from /Users/test/Documents/iOS/Tests/test.mm:19:

In file included from /Users/test/Library/Developer/Xcode/DerivedData/frxzxqwcj/Build/Products/Debug-iphonesimulator/include/KIF/KIF.h:10:

/Users/test/Library/Developer/Xcode/DerivedData/frxusqwcj/Build/Products/Debug-iphonesimulator/include/KIF/KIFTestActor.h:18:34: note: expanded from macro 'KIFActorWithClass'
# define KIFActorWithClass(clazz) [clazz actorInFile:[NSString stringWithUTF8String:**FILE**] atLine:**LINE** delegate:self]

```
                             ^
```

1 error generated.

Also reported here...

https://groups.google.com/forum/#!topic/kif-framework/qgWxVL644DU 

Is there a workaround for this issue or will this be fixed?

Thanks

**Comment by mikelupo** [comment]
Tony/Brian, I don't know this area of KIF code at all, but I'm curious to know what we can do about the issue.


Thanks,
Mike





-----Original Message-----

**Comment by phatmann** [comment]
Clearly using macros with no prefix at global scope is a terrible idea. At the very least we could rename the macros to  KIF_system and KIF_tester. But really we should get rid of them entirely. We need to anyway for Swift compatibility.

Tony

**Comment by bnickel** [comment]
Renaming to `KIF_system` and `KIF_tester` would be a breaking change.  (Major version bump.)  I'd rather not go down that road until we're ready for v5.  We also can't really get rid of them entirely because the only way to get `__FILE__` and `__LINE__` in Objective-C without brutal boilerplate is macros.

Assuming that KIF doesn't today work for anyone using C++, we could wrap it:

```
#ifdef __cplusplus
#define systemTester KIFActorWithClass(KIFSystemTestActor)
#else
#define system KIFActorWithClass(KIFSystemTestActor)
#endif
```

I am interested in why you're using Objective-C++ for tests.  Are you using a C++ testing framework?  Generally speaking, even if your app is written in Objective-C++, you should be able to do your KIF testing with Objective-C (or Swift).

**Comment by snoopying** [comment]
App is in C++ and these were existing C++ tests that I'm trying to automate.  I've used KIF before for another app in objective C which worked well.

tried adding the following to KIFSystemTestActor.h but getting a bunch of linker errors

#ifdef __cplusplus
#define systemTester KIFActorWithClass(KIFSystemTestActor)
#else
#define system KIFActorWithClass(KIFSystemTestActor)
#endif

Errors:

Undefined symbols for architecture i386:
  "_NSStringFromCGPoint", referenced from:
      ___35-[KIFUITestActor tapScreenAtPoint:]_block_invoke in libKIF.a(KIFUITestActor.o)
  "_OBJC_CLASS_$_UIAccessibilityElement", referenced from:
      l_OBJC_$_CATEGORY_UIAccessibilityElement_$_KIFAdditions in libKIF.a(UIAccessibilityElement-KIFAdditions.o)
      objc-class-ref in libKIF.a(UIAccessibilityElement-KIFAdditions.o)
      objc-class-ref in libKIF.a(KIFUITestActor.o)
      objc-class-ref in libKIF.a(UIView-KIFAdditions.o)
      objc-class-ref in libKIF.a(KIFUITestActor-IdentifierTests.o)
      objc-class-ref in libKIF.a(KIFUITestActor-ConditionalTests.o)
  "_OBJC_CLASS_$_UIApplication", referenced from:

**Comment by snoopying** [comment]
bump

is there another workaround for this issue?

**Comment by bnickel** [comment]
That means your test target is failing to link against UIKit.  You need to add UIKit to your linked libraries and make sure you're using your app as the test host.  Even if you already have a working unit test target, it's usually easiest to create a separate test target for KIF.  I would just create a new Unit Testing Bundle and select the app as the test host.

**Comment by snoopying** [comment]
Thank you!! that got the tests running.

**Comment by voznesenskym** [comment]
I opened a PR here: https://github.com/kif-framework/KIF/pull/988
