### ISSUE TITLE
KIF and bitcode error

### ISSUE THREAD

**Issue by anas10** [kif-framework/KIF#734]
XCTest framework doesn't have bitcode enabled. (Since Xcode 7 beta 3 it's treated as an error.)

![image](https://cloud.githubusercontent.com/assets/5764537/10882672/f99e5790-816c-11e5-8d33-4e960df5efb2.png)

Xcode 7.1
OSX 10.11.1
KIF (master 7e8df0980a39372424144730c899d94c3c167b1d)

**Comment by anas10** [comment]
I just found out that this error seems to happen only when testing on a real device.

**Comment by phatmann** [comment]
Closing this since we have #735 in play.
