### ISSUE TITLE
are there way that how to test URL link on WKWebview?

### ISSUE THREAD

**Issue by shiratsu** [kif-framework/KIF#738]
Hi there.
I am writing test code at my application by KIF.
I have got a problem.
I am making it with referencing KIF sample code.
I would like to make 'WebView Test'.
The sample code says
```
[tester tapViewWithAccessibilityLabel:@"A link"];
```
This accessbility label is that I already got accessbility label from iOS simulator.

My code is the following gocd
```
- (void)testWeb {
    // This is an example of a functional test case.
    // Use XCTAssert and related functions to verify your tests produce the correct results.
    [tester tapRowAtIndexPath:[NSIndexPath indexPathForRow:2 inSection:0] inTableViewWithAccessibilityIdentifier:@"history_view"];
    
    [tester tapRowAtIndexPath:[NSIndexPath indexPathForRow:2 inSection:0] inTableViewWithAccessibilityIdentifier:@"work_view"];
    
    [tester tapViewWithAccessibilityLabel:@"シフト"];
    
    [tester tapViewWithAccessibilityLabel:@"求人情報"];
    
    [tester tapViewWithAccessibilityLabel:@"職場の情報"];
    
    [tester tapViewWithAccessibilityLabel:@"Web応募"];
    
//    [tester swipeViewWithAccessibilityIdentifier:@"work_view" inDirection:KIFSwipeDirectionUp];
    
}
```

What is this problem?

**Comment by mikelupo** [comment]
Not enough information to in your initial post to help you. 

What does the UI in your project look like? 
What line in the code that you provided is giving you a failure?

Can you zip up your entire project and send it?

**Comment by shiratsu** [comment]
Sorry.I forgot to write my problem.
And i am not able to send project.
Because this project is owned by my company.

I would like to test changing page by link or form submit.

```
[tester tapViewWithAccessibilityLabel:@"求人情報"];

    [tester tapViewWithAccessibilityLabel:@"職場の情報"];

    [tester tapViewWithAccessibilityLabel:@"Web応募"];
```

The above code is accessibilityLabel of Link or submit button on our WebSite.
But they have no response and put out this error
```
-[ShiftKifTest testWeb] failed: The step timed out after 10.00 seconds: Failed to find accessibility element with the label "シフト"

```
I could check that it has above accessiblity label.
I attached captures
<img width="388" alt="2015-11-09 21 37 21" src="https://cloud.githubusercontent.com/assets/918490/11033858/233a1298-872a-11e5-8bb4-256d977b8088.png">
<img width="377" alt="2015-11-09 21 37 12" src="https://cloud.githubusercontent.com/assets/918490/11033860/261a965e-872a-11e5-8275-b33fa438a1fb.png">
<img width="373" alt="2015-11-09 21 36 54" src="https://cloud.githubusercontent.com/assets/918490/11033864/279fd0c0-872a-11e5-9ea1-bf7609a53917.png">


. 

What is this problem?

**Comment by shiratsu** [comment]
I found https://github.com/kif-framework/KIF/issues/708
i will close.
