### ISSUE TITLE
EXC_BAD_ACCESS tapAtPoint

### ISSUE THREAD

**Issue by charlesstitchfix** [kif-framework/KIF#740]
EXC_BAD_ACCESS at line  [[UIApplication sharedApplication] sendEvent:event]

line 423 in UIView-KIFAdditions.m

The event returned by the call [self eventWithTouch:touch] in tapAtPoint is not nil

This is on iOS 9.1

Thread 1Queue : com.apple.main-thread (serial)
#0	0x000000010f2b74ac in IOHIDEventGetEventWithOptions ()
#1	0x000000010f2b780b in IOHIDEventGetIntegerValueWithOptions ()
#2	0x000000010a8975f5 in -[_UITouchForceObservable _shouldFilterDueToSystemGesturesForTouches:] ()
#3	0x000000010a896e10 in __48-[_UITouchForceObservable receiveObservedValue:]_block_invoke ()
#4	0x000000010a961d99 in +[_UITouchForceMessage observe:] ()
#5	0x000000010a896d17 in -[_UITouchForceObservable receiveObservedValue:] ()
#6	0x000000010a942899 in -[UIGestureRecognizer _updateForceClassifierWithEvent:] ()
#7	0x000000010a942914 in -[UIGestureRecognizer _touchesBegan:withEvent:] ()
#8	0x000000010a4d96c8 in -[UIWindow _sendGesturesForEvent:] ()
#9	0x000000010a4dabf6 in -[UIWindow sendEvent:] ()
#10	0x000000010a48a2fa in -[UIApplication sendEvent:] ()
#11	0x000000011bda8a29 in -[UIApplicationAccessibility sendEvent:] ()
#12	0x000000011fb643c0 in -[UIView(KIFAdditions) tapAtPoint:] at UIView-KIFAdditions.m:425

**Comment by charlesstitchfix** [comment]
iOS 9 only

**Comment by phatmann** [comment]
Which version of KIF are you using?

**Comment by charlesstitchfix** [comment]
3.0.0

**Comment by phatmann** [comment]
Please upgrade to 3.3 and this problem will go away.
