### ISSUE TITLE
During Multi-Touch Event( Zoom ) Sendevent fails on iOS 9 + Devices .

### ISSUE THREAD

**Issue by bittracer** [kif-framework/KIF#750]
Details are as below :

HandEvent::+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	Timestamp:           1208714699470
	Total Latency:       1483 us
	SenderID:            0x0000000000000000
	BuiltIn:             0
	ValueType:           Relative
	EventType:           Digitizer
	DisplayIntegrated:   0
	TransducerType:      Unknown
	TransducerIndex:     0
	Identity:            0
	EventMask:           2
	Events:              Touch 
	ButtonMask:          0
	Range:               0
	Touch:               1
	Pressure:            0.000000
	AuxiliaryPressure:   0.000000
	Twist:               0.000000
	GenerationCount:     0
	WillUpdateMask:      00000000
	DidUpdateMask:       00000000
	X:                   0.000000
	Y:                   0.000000
	Z:                   0.000000
	TiltX:               0.000000
	TiltY:               0.000000
	ChildEvents:        
	    -----------------------------------------------------------------------
	    ValueType:           Relative
	    EventType:           Digitizer
	    DisplayIntegrated:   0
	    TransducerType:      Finger
	    TransducerIndex:     1
	    Identity:            2
	    EventMask:           3
	    Events:              Range Touch     
	    ButtonMask:          0
	    Range:               1
	    Touch:               1
	    Pressure:            0.000000
	    AuxiliaryPressure:   0.000000
	    Twist:               0.000000
	    GenerationCount:     0
	    WillUpdateMask:      00000000
	    DidUpdateMask:       00000000
	    X:                   172.407425
	    Y:                   306.492798
	    Z:                   0.000000
	    Quality:             1.000000
	    Density:             1.000000
	    Irregularity:        1.000000
	    MajorRadius:         5.000000
	    MinorRadius:         5.000000
	    Accuracy:            0.000000
	    -----------------------------------------------------------------------
	+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

and then HW kbd: Failed to set (null) as keyboard focus .

**Comment by phatmann** [comment]
@bittracer: can you provide more context about what you were testing?

**Comment by bittracer** [comment]
@phatmann I guess we need to close this issue . I was missing following code as this was updated on Aug 6:

   
  // Starting with iOS 9, internal IOHIDEvent must be set for UITouch object

    NSOperatingSystemVersion iOS9 = {9, 0, 0};
    if ([NSProcessInfo instancesRespondToSelector:@selector(isOperatingSystemAtLeastVersion:)] &&      [[NSProcessInfo new] isOperatingSystemAtLeastVersion:iOS9]) {
        [self kif_setHidEvent];
    }

URL : https://github.com/kif-framework/KIF/blob/master/Additions/UITouch-KIFAdditions.m

**Comment by phatmann** [comment]
@bittracer, thanks for the update. Looks like it is time for a new KIF release!

**Comment by bittracer** [comment]
@phatmann waiting for new release with Doc !

**Comment by mikelupo** [comment]
I'll be doing the release today

**Comment by bittracer** [comment]
@mikelupo Thanks buddy !
