### ISSUE TITLE
tapViewWithAccessibilityLabel exception

### ISSUE THREAD

**Issue by kennebecstars** [kif-framework/KIF#754]
I get this exception when I try and access my button:

    [tester tapViewWithAccessibilityLabel:@"buttonS" traits:UIAccessibilityTraitButton];

What's going on?

  Assertions: failed: caught "NSInvalidArgumentException", "*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil"
(
	0   CoreFoundation                      0x031b5a84 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x02c76e02 objc_exception_throw + 50
	2   CoreFoundation                      0x03063211 -[__NSArrayM insertObject:atIndex:] + 881
	3   CoreFoundation                      0x03062e71 -[__NSArrayM addObject:] + 65
	4   KIFTests                            0x10de892a -[UIApplication(KIFAdditions) windowsWithKeyWindow] + 202
	5   KIFTests                            0x10de7b1b -[UIApplication(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 251
	6   KIFTests                            0x10de5bcd +[UIAccessibilityElement(KIFAdditions) accessibilityElementWithLabel:value:traits:error:] + 221
	7   KIFTests                            0x10de561f +[UIAccessibilityElement(KIFAdditions) accessibilityElement:view:withLabel:value:traits:tappable:error:] + 239
	8   KIFTests                            0x10dff193 __83-[KIFUITestActor waitForAccessibilityElement:view:withLabel:value:traits:tappable:]_block_invoke + 147
	9   KIFTests                            0x10df64be -[KIFTestActor tryRunningBlock:complete:timeout:error:] + 190
	10  KIFTests                            0x10df6830 -[KIFTestActor runBlock:complete:timeout:] + 176
	11  KIFTests                            0x10df6984 -[KIFTestActor runBlock:complete:] + 180
	12  KIFTests                            0x10df6ac2 -[KIFTestActor runBlock:] + 98
	13  KIFTests                            0x10dff078 -[KIFUITestActor waitForAccessibilityElement:view:withLabel:value:traits:tappable:] + 360
	14  KIFTests                            0x10e00ab0 -[KIFUITestActor tapViewWithAccessibilityLabel:value:traits:] + 240
	15  KIFTests                            0x10e0099f -[KIFUITestActor tapViewWithAccessibilityLabel:traits:] + 127
	16  KIFTests                            0x10db9a87 -[KIFTests testSegueToInfoInPortraitAndBackToMyApp] + 199
	17  CoreFoundation                      0x0308db3d __invoking___ + 29
	18  CoreFoundation                      0x0308d9e6 -[NSInvocation invoke] + 342
	19  XCTest                              0x0e0792f6 __24-[XCTestCase invokeTest]_block_invoke_2 + 174
	20  XCTest                              0x0e0b6712 -[XCTestContext performInScope:] + 229
	21  XCTest                              0x0e07923b -[XCTestCase invokeTest] + 193
	22  XCTest                              0x0e0797f5 -[XCTestCase performTest:] + 529
	23  XCTest                              0x0e0a6d75 -[XCTest runTest] + 354
	24  XCTest                              0x0e076e94 -[XCTestSuite performTest:] + 427
	25  XCTest                              0x0e0a6d75 -[XCTest runTest] + 354
	26  XCTest                              0x0e076e94 -[XCTestSuite performTest:] + 427
	27  XCTest                              0x0e0a6d75 -[XCTest runTest] + 354
	28  XCTest                              0x0e076e94 -[XCTestSuite performTest:] + 427
	29  XCTest                              0x0e0a6d75 -[XCTest runTest] + 354
	30  XCTest                              0x0e060088 __25-[XCTestDriver _runSuite]_block_invoke + 61
	31  XCTest                              0x0e08762a -[XCTestObservationCenter _observeTestExecutionForBlock:] + 736
	32  XCTest                              0x0e05ffad -[XCTestDriver _runSuite] + 491
	33  XCTest                              0x0e061028 -[XCTestDriver _checkForTestManager] + 318
	34  XCTest                              0x0e0614fd -[XCTestDriver runTestConfiguration:completionHandler:] + 399
	35  XCTest                              0x0e0b7e0b _XCTestMain + 715
	36  IDEBundleInjection                  0x001c7658 ____XCBundleInjection_block_invoke_2 + 20
	37  CoreFoundation                      0x030cfd00 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 16
	38  CoreFoundation                      0x030c5683 __CFRunLoopDoBlocks + 195
	39  CoreFoundation                      0x030c4db8 __CFRunLoopRun + 1016
	40  CoreFoundation                      0x030c4706 CFRunLoopRunSpecific + 470
	41  CoreFoundation                      0x030c451b CFRunLoopRunInMode + 123
	42  GraphicsServices                    0x04e4f664 GSEventRunModal + 192
	43  GraphicsServices                    0x04e4f4a1 GSEventRun + 104
	44  UIKit                               0x0102e1eb UIApplicationMain + 160
	45  MyApp                             0x000935ea main + 234
	46  libdyld.dylib                       0x039e6a21 start + 1
)
  File: UIApplication-KIFAdditions.m:110

**Comment by phatmann** [comment]
Your app, for some reason, is not creating a window on launch.

This keeps coming up. We need to patch KIF to give a better error message when there is no key window. I will file an issue to track this.

**Comment by phatmann** [comment]
Filed issue #755.

**Comment by kennebecstars** [comment]
My app delegate indeed does create a window. What's maybe a new wrinkle is that in Xcode 7.2, you now have to have a launch screen storyboard. If you don't have one, Xcode will create you one. What is created is a single view storyboard, with a UiViewController containing a UIView with a couple labels. I fear that since there is no accessibility access to the launch screen storyboard (I had tried to add these) without the storyboard compiler giving you errors, KIF may be confused. I had run all the tests on the KIF.a target and these all worked, but the Test Host has no launch screen, which I didn't test, sorry. 

Any insight appreciated. KIF is still working on my other apps, so I'm hoping this is a new issue related to the new requirement if needing a launch screen storyboard, not just an image in xcasset form.

**Comment by phatmann** [comment]
The backtrace clearly indicates that no key window was found. I have not heard of a launch screen storyboard causing this to happen. Is there anything else funky about your app; e.g. no initial view controller?

**Comment by kennebecstars** [comment]
AppDelegate has this window property:

@property (strong, nonatomic) IBOutlet UIWindow *window;

ARC creates that for me if I use a storyboard. I don't know what else to check. I likely have a corrupted storyboard file. My KIF Xcode project's tests run fine; it's my project's KIF tests that don't run.

The storyboard has the main nav connected to the root view controller and the view is wired to the view.

**Comment by cicerohellmann** [comment]
Any news about this issue? I stuck with this same problem.

this is my application:didFinishLaunchingWithOptions:

(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];

ViewController *viewController = [[ViewController alloc] init];
self.window.rootViewController = viewController;

[self.window makeKeyAndVisible];

// always call after makeKeyAndDisplay.
#if TARGET_IPHONE_SIMULATOR
[[DCIntrospect sharedIntrospector] start];
#endif

return YES;
}

**Comment by phatmann** [comment]
@cicerohellmann: For some reason your TestHost is not creating a window at launch. Make sure you are using the proper unit test target and not a UI test target, and that your app delegate is creating a window in all circumstances.

**Comment by kennebecstars** [comment]
This issue has not changed for me. In comparing the TEST_HOST storyboard with my own, I noticed that  mine uses auto layout and size classes. I also noted that deployment target on that storyboard file is 6.1, so I had to bring that up to >= iOS 8 to test the TEST_HOST with auto layout and size classes. This seemed to work okay. I have compared the TEST_HOST to my own and only noticed that TEST_HOST doesn't create the accessibility id's in the storyboard, whereas mine does.

Maybe I could provide a test case with my data and you could take a look? What else do you suggest?

I have also followed the path of adding the code to make sure that even though I am using a storyboard, that I have a reference in the appDelegate to the window -> no difference...I still get the errant message.

**Comment by cicerohellmann** [comment]
Delete everything a do it from scratch, that worked for me


Cicero Hellmann Jacobi
+55 11 964201124
Mobile Developer and QA engineer

**Comment by kennebecstars** [comment]
Reverted to Xcode 7.1.1 and this issue went away.
