### ISSUE TITLE
Error in executing KIF Test cases from command line

### ISSUE THREAD

**Issue by sandeeplakshmi** [kif-framework/KIF#756]
I am trying yo execute KIF test cases from command line using "xcodebuild test" command.

I am receiving below when i do so -

fatal error: 'KIF/KIF.h' file not found
#import < KIF/KIF.h >
        ^
1 error generated.

Testing failed:
    'KIF/KIF.h' file not found
** TEST FAILED **
Tests are working fine when they are executed from xcode.

Please point me in right direction.

**Comment by mikelupo** [comment]
Can you make/share a sample project that mirrors your own and exhibits the problem. Good chance that I can help.

**Comment by sandeeplakshmi** [comment]
Hi Mikelupo, 

Code is present at 
https://github.com/sandeeplakshmi/unitautomation

i am using the below command to trigger unit test cases -

xcodebuild test -project "sample.xcodeproj" -scheme "sampleunittests" -destination 'platform=iOS Simulator,OS=8.4,name=iPhone 6'

Thank you in advance :)

**Comment by mikelupo** [comment]
@sandeeplakshmi, I have created a pull request to your repo. In the comments, and in the git commit message, I summarized what I did to get it working. 
I hope this helps.
