### ISSUE TITLE
enterText:intoViewWithAccessibilityLabel: could not enter the first character as lower case under auto-capitalization

### ISSUE THREAD

**Issue by keithyipkw** [kif-framework/KIF#757]
It seemed that the shift key was not checked or not toggled before entering the first character. In other iOS and KIF versions, the first character was entered properly.

Simulator 9.2 as iPhone 6s
iOS 9.2
KIF v3.3.1

In the test,
[tester enterText:@"example" intoViewWithAccessibilityLabel:@"Title"];

In the console,
The step timed out after 1.00 seconds: Failed to get text "example" in field; instead, it was "Example"

**Comment by phatmann** [comment]
Do you know which KIF version this broke in?

**Comment by keithyipkw** [comment]
v3.3.1

**Comment by ryuzmukhametov** [comment]
I have same problem. It seems that it's a Simulator 9.2 issue. Thus the problem still exists when I use KIF  3.3.0 and Simulator "iPad 2, iOS 9.2" but in iOS9.1 everything is correct.

**Comment by justinseanmartin** [comment]
Apparently iPad & iPhone have different default behaviors for autocapitalization, at least in iOS 9.2. It appears that even explicitly setting the value to "none" doesn't work. The solution that I've got is exposing the search control via an outlet and explicitly setting the autocapitalization to none after the view controller has been initialized. PR coming shortly.

**Comment by mikelupo** [comment]
@justinseanmartin ....Just a thought.... I wonder if the right fix is inside the enterText methods.
if we can get the view instance from the waitFor... methods and cast it properly to the UISearchBar class perhaps we can detect how the autocapitalization is set on the field. Once we know, perhaps we can pass that down into the KIF internals and make some decisions on how we evaluate the entered text vs resulted text. 
I suspect that this would be done down in the "- (void)expectView:(UIView *)view toContainText:(NSString *)expectedResult" method. 

I realize that you're fixing the local test case and that has no impact on KIF itself (other than perhaps if it will compile and merge cleanly). 
Can you investigate this?

cc: @phatmann

**Comment by justinseanmartin** [comment]
I don't think that KIF should be cognizant of the autocapitalization rules of the dialog that it is typing into, or if it is made to be, it seems out of scope of simply fixing this failing test case.

**Comment by keithyipkw** [comment]
I am not sure if I understand the conversation above correctly. The bug also occurred in UITextField. Please don't miss that if there will be a fix.

**Comment by RoyalPineapple** [comment]
I Agree with Justin that KIF shouldn't worry about the autocapitalization setting. The disconnect between iPhone and iPad default behavior is Apple's bug and is outside the scope of KIF's responsibility. A developer knows what to expect from their app and KIF should be able to verify their expectations.

Autocapitalization is a first class feature of text fields/views and should be respected. When encountering this behavior a developer has the choice to provide either an expectedResult or pass in an already capitalized string.

**Comment by justinseanmartin** [comment]
I'm re-reading the thread now, I thought it was referring specifically to the test behavior and not the general KIF behavior. I apologize, I shouldn't have marked the issue as resolved in my PR. From @ryuzmukhametov's statement, it appears to be OS related that app behavior may be inconsistent. 

Potentially the behavior of `enterText:` without the `expectedText:` parameter shouldn't validate the entered text at all, and leave that up to the caller. I do like the automatic validation though, and in general I think it a reasonable assertion. Maybe a flag could exist for setting on the test actor that removes the check of what text appears?

Alternatively, I'd recommend setting the `expectedText:` explicitly in your test. I think this is the most straightforward solution to the issue.
