### ISSUE TITLE
Cannot tap on UIAlertView / UIAlertController when tests running by Xcode CI server

### ISSUE THREAD

**Issue by Judaszu** [kif-framework/KIF#766]
i have issues in my project with alert views, when i'm running tests locally, I'm getting expected results of my tests, but when tests are running by Xcode CI, then it fails everytime, when i have to click alert view.

I started debugging from checking out example from your repo and run tests - even locally more than 100 test cases have failed. Can i ask why? 

screenshot from running your example tests: 
![screen shot 2016-01-07 at 19 23 53](https://cloud.githubusercontent.com/assets/16598047/12179161/89734678-b575-11e5-9200-b537279a1c75.png)

**Comment by zaxy78** [comment]
@ghost Did you found out why it didn't work?
