### ISSUE TITLE
Will KIF break with Xcode 7.3 (private frameworks removed from SDK)?

### ISSUE THREAD

**Issue by raphaklr** [kif-framework/KIF#770]
In the [Release Notes](http://adcdownload.apple.com/Developer_Tools/Xcode_7.3_beta/Xcode_7.3_beta_Release_Notes.pdf) of Xcode 7.3 beta, Apple says:
>The Apple private frameworks have been removed from the iOS/watchOS/tvOS SDKs. If your application fails to link, please make sure that you are not using any private frameworks. The use of private frameworks is an unsupported configuration and applications that use non-public APIs will be rejected by the App Store - see App Store Guideline 2.5 (https:// developer.apple.com/app-store/review/guidelines/#functionality). (22330301)

I think KIF uses private Apple APIs, so will the test target even compile in Xcode 7.3?

**Comment by bnickel** [comment]
Private frameworks are things like Accessibility.framework, AccountsUI.framework, etc that live in /System/Library/PrivateFrameworks.  These are frameworks used by Apple apps but are not exposed to 3rd party devs.

For the most part what KIF does is not access private frameworks but private APIs in public frameworks.  It also doesn't link against private APIs at build time so compiling should work.  That said, KIF does load a private framework, /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport, at runtime.  It is possible that Apple will at some point block this but these release notes don't seem to imply that.

Still, it would be good for someone to test.

**Comment by mikelupo** [comment]
Brian, I saw that message this morning. As a result, I am having a Macbook Pro imaged with El Capitan which is a requirement to run that version of XCode. 
I hope to be able to report something back today. If not, then I suspect by tomorrow latest.


Thanks,
Mike



-----Original Message-----

**Comment by Jaymon** [comment]
We ran all our tests with 9.3 beta today and they all passed, so it looks like we dodged a bullet.

**Comment by raphaklr** [comment]
Thank you guys, I will close this for now.
