### ISSUE TITLE
Can't build KIFFramework target 

### ISSUE THREAD

**Issue by kennebecstars** [kif-framework/KIF#784]
This happens in 3.3.0 or 3.3.1 with different results. log1 is 3.3.0, log2 is 3.3.1.

[log1.log.zip](https://github.com/kif-framework/KIF/files/100589/log1.log.zip)
[log2.log.zip](https://github.com/kif-framework/KIF/files/100595/log2.log.zip)

**Comment by kennebecstars** [comment]
This makes using KIF from Carthage impossible.

**Comment by phatmann** [comment]
This should be fixed by #763. Can you try using the HEAD branch and let me know?

**Comment by kennebecstars** [comment]
Please forgive my inexperience, what exactly do you want me to clone? If I clone the master, I get 3.3.1 with the same issues.

kennebecstars -bash [KIF-763]  9225 $ git clone https://github.com/kif-framework/KIF/pull/763
Cloning into '763'...fatal: repository 'https://github.com/kif-framework/KIF/pull/763/' not found

**Comment by kennebecstars** [comment]
I found the link to browse the repos at that point and was able to make the download and tested positive. Thanks for your patience, @phatmann.

**Comment by phatmann** [comment]
Excellent! Time to push a new release...

**Comment by phatmann** [comment]
Fixed in 3.3.2

**Comment by kennebecstars** [comment]
My wording of 'tested positive' was misleading; there are KIF tests that do not work based on that HEAD branch, but my testing of the KIFFramework target is that it builds that target, now. The tests failing are primarily in the gesture tests.

**Comment by phatmann** [comment]
Sorry, I am still confused. Can you tell me what defects still exist in HEAD?
