### ISSUE TITLE
What's the best way to set up a view controller for KIF?

### ISSUE THREAD

**Issue by raphaklr** [kif-framework/KIF#786]
I have a fairly large app with multiple tabs, navigation controllers and so on. When I want to test a feature, I usually set the corresponding view controller as the app's root view controller like so:
```
- (void)setup {
   [UIApplication sharedApplication].keyWindow.rootViewController = viewControllerToTest;
}
```
In `tearDown`, I'm setting `viewControllerToTest` to `nil` to make sure that everything is cleaned up. So I was wondering: Is this the right way in terms of resetting the test environment? In other projects, the application's rootViewController is set up (once) as a `UINavigationController` and all view controllers under test get pushed on to it and get popped again when the test finishes. What do you guys recommend? Are there any best practices?

And as a follow-up: Are there any differences between `setup <--> beforeEach` and `tearDown <--> afterEach` respectively?

**Comment by Judaszu** [comment]
KIF extending XCTestCase, so you should use methods implemented in KIFTestCase. Just read implementation of KIFTestCase and you will understand. 

If you have simple app, and start point isn't depend on specific conditions, you can ujust grab the navigation controller and push view controller.
```
    UIWindow *window = [[[UIApplication sharedApplication] delegate] window];
    UINavigationController *navigationController= (UINavigationController *)window.rootViewController;
```

then just push view controller whatever you want. 

you should do that navigation in `beforeEach`
