### ISSUE TITLE
ApplicationDidBecomeActive not happening when app launched using KIF 

### ISSUE THREAD

**Issue by mikelupo** [kif-framework/KIF#788]
The following article in the link below describes something that I experience often when running my app with KIF.
It tends to happen when I use Xcode 7 to compile and an iOS 8.4 device to run the tests.
I don't know if the article has nailed my issue but it seems plausible. 
@bnickel or @phatmann I wonder if you have any experience with this or can shed some light on a workaround/fix? 

http://stackoverflow.com/questions/26059927/applicationdidbecomeactive-not-called-when-launching-app-from-banner-custom-acti

**Comment by phatmann** [comment]
Sorry, nothing jumps to mind. I will leave this issue open.

**Comment by mikelupo** [comment]
I have since learned that this is an issue with Apple. It happens in our apps that are compiled using XCode 7. Apple's been pretty quiet about it.
