### ISSUE TITLE
waitForAnimationsToFinish doesn't wait for animations on sublayers of views

### ISSUE THREAD

**Issue by rciobanu-omnifone** [kif-framework/KIF#789]
Hi everyone,
I've encountered this issue (which I believe to be a bug) when using the `SVProgressHUD` cocoapod. The way that component works is by adding a sublayer to the HUD's layer and animating that sublayer.
Although I have my gripes with `SVProgressHUD` and spinners in general, I think in this particular case it's a `KIF` shortcoming as a user would see the HUD as animating and would wait for it to go away before progressing. Obviously when running tests this can lead to actions being attempted when the VC isn't in a ready state yet.
I've tracked the issue to the `- (void)waitForAnimationsToFinishWithTimeout:(NSTimeInterval)timeout` method and particularly line 153:
```obj-c
BOOL hasAnimation = view.layer.animationKeys.count != 0 && ![view.layer.animationKeys isEqualToArray:@[@"_UIParallaxMotionEffect"]];
```
I am ready to submit to your consideration a pull request that fixes the issue.

**Comment by phatmann** [comment]
Fixed in the PR
