### ISSUE TITLE
KIF 'You must rebuild it with bitcode enabled' Xcode v7.1 OS Xv10.10.5

### ISSUE THREAD

**Issue by johnslay** [kif-framework/KIF#796]
```
❌  ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm getting this error when all targets have the setting 'ENABLE_BITCODE' set to 'No' and it only appears when testing on a physical device.

 Xcode 7.1 and Mac OS X Yosemite 10.10

**Comment by devladinci** [comment]
:+1: Same here

**Comment by devladinci** [comment]
:+1: Same here, when build on device. @johnslay possible workaround 

- Pods
- KIF
- Enable Bitcode = NO

**Comment by johnslay** [comment]
Yeah I can do that locally, however, my company uses Jenkins that runs the pods scripts and there's no way for me to modify that pod setting (that I know of).

**Comment by phatmann** [comment]
Is this a KIF issue because the KIF pod is not enabling bit code?

**Comment by jjnino** [comment]
Hello has there been an update to this issue?

**Comment by phatmann** [comment]
No update yet. Any suggested fix?

**Comment by phatmann** [comment]
Here is a [proposed solution](http://stackoverflow.com/questions/32640149/disable-bitcode-for-project-and-cocoapods-dependencies-with-xcode7):

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by Zhukn1** [comment]
Hi @phatmann. I use Bitrise as a CI solution. Had the exact same error.

The solution fixed the problem for me, so thx man! 🍻
