### ISSUE TITLE
Pods/Headers/Public/KIF/KIFTestActor.h:174:26: Expected ')'  compile error

### ISSUE THREAD

**Issue by sdupuis1** [kif-framework/KIF#797]
I installed KIF using cocoa pods and can't figure out why it is having problems building complaining about the macro Delegate

@interface KIFTestActor (Delegate) <KIFTestActorDelegate>
                                        ^

Expanded from macro 'Delegate'
to match this '('

**Comment by sdupuis1** [comment]
nvm, I had a macro defined called Delegate ughhhhh

**Comment by mikelupo** [comment]
Curious Is your test project built from the unit tests framework or is it built from UI Test. It only works with The Unit test framework. Not sure that it's what ails ya but a lot of people make that mistake when first starting out.
