### ISSUE TITLE
UIPickerView with NSAttributedStrings are not working.

### ISSUE THREAD

**Issue by schwindt** [kif-framework/KIF#799]
UIPickerViews only works when this delegate is used:

`- (NSString *)pickerView:(UIPickerView *)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component`

instead of this here:

`- (NSAttributedString *)pickerView:(UIPickerView *)pickerView attributedTitleForRow:(NSInteger)row forComponent:(NSInteger)component{`

This took me a long time to figure out, so would be nice if both would be supported.

**Comment by phatmann** [comment]
Good catch! Do you have the time to put a pull request together with a fix?
