### ISSUE TITLE
KIF not building as a .framework

### ISSUE THREAD

**Issue by mtitolo** [kif-framework/KIF#809]
Hey folks,

I spent the better part of today figuring out why KIF wouldn't build as a framework in my project. It turns out that there's a private header (`UIScreen+KIFAdditions.h`) that's being used by a public header (`KIFUITestActor.h`), and when using clang modules this is a no-no. This issue only shows up when `KIFUITestActor` is imported, which is apparently not often. I verified that moving this header into Public Headers fixes the issue.

I'm happy to submit a short PR to fix this but would like some direction before doing so. There are two ways to fix this:

1. Rename `UIScreen+KIFAdditions.h/m` to `UIScreen-KIFAdditions.h/m` to get picked up by the current podspec regex.
2. Add `UIScreen+KIFAdditions.h` to the `public_header_files` in the podspec.

The first follows the guidelines but the second is less of a breaking change (even though this is currently a private class).

Let me know and I'll get a PR up ASAP as this is a blocker for my team.

Cheers!

**Comment by RoyalPineapple** [comment]
I just opened  https://github.com/kif-framework/KIF/pull/810

**Comment by mtitolo** [comment]
Awesome, thank you!

**Comment by phatmann** [comment]
#810 is merged. Thanks for helping us fix this!
