### ISSUE TITLE
How to make KIF work in the new iOS UI Testing Bundle target

### ISSUE THREAD

**Issue by leoqiu** [kif-framework/KIF#815]
Hi
I think currently KIF only work under iOS Unit Testing Bundle,
Is there anyway that I can make it work under iOS UI Testing Bundle?

My boss want something can use both UI Testing (for ios9) & KIF (for ios8), but KIF only works under Unit Test bundle and UI Testing only works on UI Testing Bundle.

Or anyway to work this around?

Thx a bunch!
Leo

**Comment by mikelupo** [comment]
Hi Leo, As one of the newer KIF maintainers, I'm going to go out on a limb. If I'm wrong, I am sure that @bnickel or @phatmann will correct me. 


I don't think that's possible today for a hybrid as KIF is built on top of the XCTest framework.
KIF runs "in-process", same as unit tests do. It's my understanding that the UI test framework does not run in-process. The architectures are very different. 


Now if you have the time to investigate this in the form of a Pull Request, we would surely be willing to have a good look at it. 


Regards,
Mike



-----Original Message-----

**Comment by leoqiu** [comment]
@mikelupo  Hi Mike, thx  for your answer, we were able to hack it around to make it work last Friday,

Short story, 1. running same test codes under different targets, UITesting Bundle & Unit Test Bundle
                    2. Use preprocessor marco to determine which to run at runtime. 

Thx again, I might have future questions about KIF that I wana ask you about, thx again :+1: 

Leo

**Comment by maryamaffinityclick** [comment]
I was trying to use KIF in my UITest target classes but it is not working. is it true that its not working  on UITest target classes ??

**Comment by justinseanmartin** [comment]
@maryamaffinityclick - KIF works more like a unit test than the Apple UI test framework. KIF tests should be added to a Unit Test XCTest target.
