### ISSUE TITLE
Building KIF with XCode Version 7.3 beta (7D162j) errors on logical not case

### ISSUE THREAD

**Issue by tmcw** [kif-framework/KIF#817]
![2016-03-21 at 11 58 am](https://cloud.githubusercontent.com/assets/32314/13924841/43a68fbc-ef5c-11e5-95a5-772ab7d47ccf.png)

These two lines in TappingTest.m are highlighted as errors:

* https://github.com/kif-framework/KIF/blob/master/KIF%20Tests/TappingTests.m#L77
* https://github.com/kif-framework/KIF/blob/master/KIF%20Tests/TappingTests.m#L95

I'm an obj-c newbie but [according what I can find on Operator Precedence](http://www.techotopia.com/index.php/Objective-C_2.0_Operator_Precedence), this error is legitimate: the line

```objc
if (! newValue == (originalValue -1))
```

Will be interpreted as

```objc
if ((! newValue) == (originalValue -1))
```

Because ! has higher precedence than ==, so the comparison will be

```objc
if (NO == (originalValue -1))
```

Which I assume is incorrect. Happy to write a PR if this is the case.

**Comment by phatmann** [comment]
You are absolutely right. These lines should be using the `!=` operator. Please do file a PR. Thanks!
