### ISSUE TITLE
[UIScreen majorSwipeDisplacement] unrecognized selector

### ISSUE THREAD

**Issue by vasarhelyia** [kif-framework/KIF#827]
Hi,

I'm experimenting with KIF in my [dummy Swift project](https://github.com/vasarhelyia/todo-list-swift).

The problem I ran into is that when [using `KIFUITestActor`'s `swipeRowAtIndexPath`](https://github.com/vasarhelyia/todo-list-swift/blob/master/TodoListTests/TodoTableViewUITests.swift#L49) function, the test crashes with unrecognized selector for `[UIScreen majorSwipeDisplacement]`. 

[Implementing the `UIScreen+KIFAdditions` category (extension) in my project](https://github.com/vasarhelyia/todo-list-swift/blob/master/TodoListTests/TodoListTests.swift#L34) of course solves the issue and turns the test green.

Can you please help me out a bit, why my project can't seem to find this category? I hope it's just me, but I'm really out of ideas.

I'm using Xcode 7.3 and KIF 3.4.1 with Carthage.

**Comment by phatmann** [comment]
Any chance that #825 solves your issue?

**Comment by phatmann** [comment]
#825 is merged, so you can try out the HEAD branch

**Comment by RoyalPineapple** [comment]
Looks like UIScreen+KIFAdditions.h is included in the framework, but UIScreen+KIFAdditions.m is not

**Comment by RoyalPineapple** [comment]
PR #828

**Comment by phatmann** [comment]
I merged #828. @vasarhelyia, please let me know if this issue is now fixed for you.

**Comment by vasarhelyia** [comment]
Yes, it did! Thank you so much for the fix.
