### ISSUE TITLE
How to capture screen in a real device for KIF

### ISSUE THREAD

**Issue by 346285234** [kif-framework/KIF#832]
KIF use capture API to snapshot, but it must set KIF_SCREENSHOTS first,  so how can I set KIF_SCREENSHOTS to a sandbox folder for a real device? Thanks.

**Comment by phatmann** [comment]
I suggest using NSLog on the device to print the path to the folder you want to use, then hard code that path into KIF_SCREENSHOTS.

**Comment by 346285234** [comment]
Thanks.
