### ISSUE TITLE
Rename system macro

### ISSUE THREAD

**Issue by kkodev** [kif-framework/KIF#834]
**system** macro is way too common name and causes clashes with other libraries/code. I suggest renaming it to **kif_system**.

**Comment by phatmann** [comment]
I would like to get rid of the macros entirely. If you have an idea, let us know.

**Comment by kkodev** [comment]
Well, this (and **tester**) could just be convenience static initialisers in appropriate classes.

**Comment by phatmann** [comment]
Sounds good to me. Would you consider modifying #835 to do this so we can all see how it looks and feels? As  long as it is performant and terse I imagine it will pass muster.

**Comment by phatmann** [comment]
Also worth mentioning: for backwards compatibility we probably want to do the following:

1. In a new build, keep the macros around, but wrap them around the new methods. Warn users that macros are deprecated.
1. In a following build, move the macros into a separate header file that users can choose to include.

**Comment by kkodev** [comment]
I will give it a go.
For new build perhaps the problem can be resolved with some #indef to allow to disable macros + warnings as you suggested.
Like #ifndef KIF_DISABLE_MACROS or similar.

**Comment by bnickel** [comment]
I believe directives like that won't work if KIF is compiled as a framework and it would always be treated as though `KIF_DISABLE_MACROS` is undefined.

**Comment by justinseanmartin** [comment]
Closing this, it is already covered by #733
