### ISSUE TITLE
Launch test close the app and prevent XCTestActor to find view

### ISSUE THREAD

**Issue by qclmnt** [kif-framework/KIF#842]
Hi everyone,

I'm trying to use KIF to make some test on my app. I did create a Target MyAppUITest and I run my test on this target. I succeed to run my test.

But when I launch my tests that open the app and then put directly my app in background mode without stop my tests, then my tests failed  `Failed to find accessibility element with the label` whereas the accessibility Label is defined. And if I force the app to stay open (by clicking on the app) everything works. (But I would like to do not have to click on my app to keep it active...)

Build with Xcode 7.3 on simulator with iOS 9.3

**Comment by phatmann** [comment]
Are you using a UI Test or Unit Test target? KIF will not work with UI Tests.

**Comment by qclmnt** [comment]
Exactly this was my mistake, with a Unit Test target it works perfectly!
