### ISSUE TITLE
BUG: Problem Entering Text on UITextfield with Placeholder Text

### ISSUE THREAD

**Issue by abbeyjackson** [kif-framework/KIF#843]
I have discovered a bug. I have encountered this several times but this is the first time I have actually figured out what is going on.

When there is a textfield that has placeholder text KIF uses the placeholder text as the accessibility label, even if you set an accessibility label that is different. So you must set an accessibility label but then in KIF you must use the placeholder text as part of intoViewWithAccessibilityLabel:"Placeholder Text".

If you do not set an accessibility label you will get a confusing error. For example let's say I was trying to do 
`tester().enterText("TEST", intoViewWithAccessibilityLabel: "Placeholder Text")`

The error I would get would be:

> The step timed out after 1.00 seconds: Failed to get text "TEST" in field; instead, it was "Placeholder Text"

This error would be confusing because looking at the simulator you can see that KIF did indeed enter TEST into the textfield.

I do not know what is causing this in KIF itself but if you experience this error the fix is:
1. In your classfile set an accessibility label on the textfield
2. In KIF use the placeholder text for intoViewWithAccessibilityLabel:
- I suggest setting the accessibility label to the placeholder text for congruency

**Comment by qliam** [comment]
Hi, have you solved this problem ?
Thx

**Comment by phatmann** [comment]
@qliam No fix has been proposed.

**Comment by herbert1119** [comment]
I have a workaround solution: use`tapViewWithAccessibilityLabel` to tap on that filed and use `enterTextIntoCurrentFirstResponder` to enter a text.

**Comment by JohnJGL** [comment]
@herbert1119 `enterTextIntoCurrentFirstResponder` seems not working for me, the textField not really enter the text

**Comment by justinseanmartin** [comment]
We use it all throughout our tests and have no issues. We use the newer `KIFUIViewTestActor` methods exposed by `viewTester`, but they should end up doing the same thing.

```
[[viewTester usingFirstResponder] enterText:@"blah"]
```

If you set a breakpoint in `-[KIFUITestActor enterTextIntoCurrentFirstResponder:fallbackView:]` is `+[KIFTypist enterCharacter:]` returning YES or NO? If NO, then is the `fallbackView` the one that you're expecting to receive the text input?

You could also try the above suggestion of calling `tap` on it before attempting to enter text. If you find a bug in the framework, pull requests are always welcome!

**Comment by justinseanmartin** [comment]
Reading the original post, a downside of using the `accessibilityLabel` that UIKit automatically provides for a UITextField is that it is different when the field has text typed into it and when it is empty (showing the placeholder). One way we've worked around issues like this in our app is that we set the placeholder text as the `accessibilityIdentifier` for all UITextField elements to have a consistent way of finding these fields regardless of their content.

**Comment by abbeyjackson** [comment]
@justinseanmartin  The original ticket is from 18 months ago also. I am not working on a project that uses KIF right now so I can't say if the problem was fixed but many many versions have been released since the first posting.

@JohnJGL I suggest you open a new issue, your post is not the same as the original issue, it is about a different api function.

Since there have been no reports of the original issue in a year I am going to close this issue.

**Comment by maryamaffinityclick** [comment]
Im having the same issue ! still not fixed. 

it checks with the placeholder and expectation will fail!

**Comment by justinseanmartin** [comment]
Please see my comment above regarding having the app code set the `accessibilityIdentifier` to match on the placeholder text even when the field has contents. This isn't something that KIF can fix, as it is reflective of the accessibility behavior of your app.

**Comment by maryamaffinityclick** [comment]
You are right about `accessibilityLabel` ! thanks for mentioning that.
I have worked around this issue by setting the `accessibilityLabel` manually in code ( with the placeholder ) with having an extension of UIView.  and it is working fine for textFields not having text at the beginning and also for any class that you doesnt have the `accessibilityLabel`  by default.  This is what I did: 

`extension UIView {

    open override func awakeFromNib() {
        // "Empty list" check is for UITableView,
        // "" check is for UITextView
        // and we check to set accessibility on specified classes not all of them. cause it will ruin all the cells accessibility labels.
        // isMember will match exactly the same class. (isKindOf will look in subclasses which we dont want to.)
        if accessibilityLabel == nil  && classes.contains(where: { self.isMember(of: $0) }) ||
            (accessibilityLabel == "" && self.isMember(of: UITextView.self) ) {
            // By default we make the class name as the accesiibility label
            accessibilityLabel = classForCoder.description()
            
            // but for UITextField we will set the placeholder or attributedPlaceholder
            if self.isMember(of: UITextField.self) {
                if let placeholder = (self as? UITextField)?.placeholder {
                    self.accessibilityLabel = placeholder
                } else if let attributedPlaceholder = (self as? UITextField)?.attributedPlaceholder {
                    self.accessibilityLabel = attributedPlaceholder.string
                }
            }
        }
        super.awakeFromNib()
    }
    
}`

**Comment by justinseanmartin** [comment]
Keep in mind that accessibilityLabel is user facing via screen reader, so this will alter the behavior for blind users compared to the default UIKit behavior. This is why I've been setting the identifier in this case, because I assume that Apple would make UIKit behave that way by default if that's what made sense. It totally depends on how this impacts the expectations of someone using accessibility tools though.

**Comment by justinseanmartin** [comment]
Also, thanks for sharing!

**Comment by maryamaffinityclick** [comment]
Exactly! that is an important point which is why I put the override in in my Test target. So Firstly,  I dont have to set any `AccessibilityLabel` in my main target codes, I will handle all in my test target override function, 
Secondly, I will not touch any accessibilityLabel set by default or the one is already set by other developers.

**Comment by kwakueshun** [comment]
> I have a workaround solution: use`tapViewWithAccessibilityLabel` to tap on that filed and use `enterTextIntoCurrentFirstResponder` to enter a text.

This worked for me.
