### ISSUE TITLE
Tests got failed on Xcode 7.3

### ISSUE THREAD

**Issue by viraj** [kif-framework/KIF#844]
My app pass all UI tests on Xcode 7.2. But after I upgrade to Xcode 7.3 it all got failed.
**Reason : App is not coming to foreground during tests on Xcode 7.3**
But if I manually click on the app and take into foreground then all good. All tests get pass.
So I guess there is no issue with the test cases.

Kindly let me know if there is a solution for this.
Thanks

**Comment by mikelupo** [comment]
I am using KIF with Xcode 7.3. I don't have that problem. The last version published dealt with some Xcode 7.3 issues. So please make sure you have the latest version of KIF.

**Comment by viraj** [comment]
Hi thanks for the tip. 
But I have tried with latest. I use CocoaPods so tried the with tag 3.4.2, Branch v4 ( has some crashes )  and branch master ( I think its same as tag 3.4.2 ) but in all versions in Xcode 7.3 **App is not coming to foreground during tests**. 
What I'm working on is a bit complex app with ResearchKit and I cannot share it. But I have created a [sample app](https://www.dropbox.com/s/515mm8q0oidqd48/vt%20-%20Not%20working%20on%20Xcode%2073.zip?dl=0) to verify this issue. Kindly have a look. All good on Xcode 7.2 but failed to come to foreground on Xcode 7.3. In this sample app tests get passed even though the app is in background.
Thanks

**Comment by mikelupo** [comment]
Hi Viraj,
I downloaded your zip file and ran it. I am able to reproduce exactly what you see.

I'm bringing @phatmann into the discussion. 

Here is how I reproduced:

prerequisites:
- Assumes you have cocoapods installed (if not, go to a terminal window and type, "sudo gem install cocoapods")
- OSX 10.11 (El Capitan) with XCode 7.3.

Steps:
download sample app, unzip. (I unzipped to vt_example)
in terminal, navigate to vt_example directory and run, "pod install" wait till it completes (about 30 secs)
In finder window, navigate to vt_example folder.
tap on the WORKSPACE (not the .xcodeproj file) to open Xcode.
COMMAND + U to run the tests. 

Actual:
Notice that the app comes to foreground briefly, but then returns to back ground.
No action is taken in the App UI (the "button" isn't pressed.)
The tests erroneously pass.
There are errors regarding UI Accessibility in the run-time log below. These may hold a clue.

Expected:
The App comes to foreground, the "button" ui object is pressed and an alert appears. The test waits for the alert and then clears it.

===== Entire test run output ======
2016-04-26 10:09:45.569 vtt[69071:11592550] KIFTester loaded
10:09:45.923 vtt[69071:11592608] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
10:09:45.929 vtt[69071:11592604] _IDE_startExecutingTestPlanWithProtocolVersion:16
Test Suite 'All tests' started at 2016-04-26 10:09:47.925
Test Suite 'vttUITests.xctest' started at 2016-04-26 10:09:47.927
Test Suite 'firstTest' started at 2016-04-26 10:09:47.927
**2016-04-26 10:09:48.077 vtt[69071:11592550] UIAccessibility Error adding -[DOMNode _moveRight:withHistory:]
2016-04-26 10:09:48.077 vtt[69071:11592550] UIAccessibility Error adding -[DOMNode _moveLeft:withHistory:]
2016-04-26 10:09:48.077 vtt[69071:11592550] UIAccessibility Error adding -[DOMNode _updateSelectionWithTextRange:withAffinityDownstream:]
2016-04-26 10:09:48.078 vtt[69071:11592550] UIAccessibility Error adding +[DOMNode safeCategoryBaseClass]
2016-04-26 10:09:48.078 vtt[69071:11592550] UIAccessibility Error adding -[UIWebFormAccessory initWithFrame:]
2016-04-26 10:09:48.078 vtt[69071:11592550] UIAccessibility Error adding -[UIWebFormAccessory _accessibilityLoadAccessibilityInformation]
2016-04-26 10:09:48.078 vtt[69071:11592550] UIAccessibility Error adding +[UIWebFormAccessory safeCategoryBaseClass]
2016-04-26 10:09:48.078 vtt[69071:11592550] UIAccessibility Error adding +[UIWebFormSelectPeripheral createPeripheralWithDOMHTMLSelectElement:]
2016-04-26 10:09:48.078 vtt[69071:11592550] UIAccessibility Error adding +[UIWebFormSelectPeripheral safeCategoryBaseClass]
2016-04-26 10:09:48.079 vtt[69071:11592550] UIAccessibility Error adding -[UIWebSelectSinglePicker _accessibilityServesAsFirstElement]
2016-04-26 10:09:48.079 vtt[69071:11592550] UIAccessibility Error adding +[UIWebSelectSinglePicker safeCategoryBaseClass]
2016-04-26 10:09:48.079 vtt[69071:11592550] UIAccessibility Error adding -[UIWebSelectMultiplePicker _accessibilityServesAsFirstElement]
2016-04-26 10:09:48.079 vtt[69071:11592550] UIAccessibility Error adding +[UIWebSelectMultiplePicker safeCategoryBaseClass]
2016-04-26 10:09:48.079 vtt[69071:11592550] UIAccessibility Error adding -[UIWebPlugInView webPlugInStart]
2016-04-26 10:09:48.079 vtt[69071:11592550] UIAccessibility Error adding +[UIWebPlugInView safeCategoryBaseClass]**
Test Case '-[firstTest test0_CloseSettingsPageWithDismissButton]' started.
    t =     0.00s     Start Test
    t =     0.00s     Set Up
    t =     2.22s     Tear Down
Test Case '-[firstTest test0_CloseSettingsPageWithDismissButton]' passed (2.220 seconds).
Test Case '-[firstTest test1_CloseSettingsPageWithDismissButton]' started.
    t =     0.00s     Start Test
    t =     0.00s     Set Up
    t =     2.19s     Tear Down
Test Case '-[firstTest test1_CloseSettingsPageWithDismissButton]' passed (2.188 seconds).
Test Suite 'firstTest' passed at 2016-04-26 10:09:53.514.
Executed 2 tests, with 0 failures (0 unexpected) in 4.408 (5.587) seconds
Test Suite 'vttUITests.xctest' passed at 2016-04-26 10:09:53.515.
Executed 2 tests, with 0 failures (0 unexpected) in 4.408 (5.589) seconds
Test Suite 'All tests' passed at 2016-04-26 10:09:53.516.
Executed 2 tests, with 0 failures (0 unexpected) in 4.408 (5.590) seconds


Test session log:
/Users/mlupo/Library/Developer/Xcode/DerivedData/vtt-arrassjrmhzcovchywvqtnmytzki/Logs/Test/C2BD94AC-BB9A-414F-A49B-EF4C555FDBA1/Session-2016-04-26_10:09:41-nOm6jk.log

**Comment by mikelupo** [comment]
@viraj 
I tried another integration. This time, I removed all traces of the cocoapod install. I performed the github installation which is the method I am most comfortable with.

This time, when I ran the tests, I launched from the xcodeproj file. I dragged the KIF.xcodeproj file into the project. Added KIF as a dependency in Build settings.
Added the libkif.a and IOKit.Framework to the "Link Binary with Libraries".
Able to compile and run.
I set up an exception breakpoint to catch.

2016-04-26 10:42:52.091 vtt[69597:11605202] KIFTester loaded
10:42:52.437 vtt[69597:11605290] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
10:42:52.439 vtt[69597:11605282] _IDE_startExecutingTestPlanWithProtocolVersion:16
Test Suite 'All tests' started at 2016-04-26 10:42:54.438
Test Suite 'vttUITests.xctest' started at 2016-04-26 10:42:54.439
Test Suite 'firstTest' started at 2016-04-26 10:42:54.440
2016-04-26 10:42:54.593 vtt[69597:11605202] +[UIAccessibilityElement accessibilityElement:view:withLabel:value:traits:tappable:error:]: unrecognized selector sent to class 0x10b278bd0
(lldb) po 0x10b278bd0
UIAccessibilityElement

My own projects are set up to run like this. 
What I don't understand is, why this project? What's different?

**Comment by phatmann** [comment]
Before I dive in, a question: if the unit tests are run without KIF installed, does the app behave normally?

**Comment by viraj** [comment]
Yes it does. But once i install KIF ( with pod installation  ) and run a simple KIF test this issue is happening.

**Comment by phatmann** [comment]
The problem is that your KIF tests are part of the `vttUITests` target instead of the `vttTests` target. Since KIF tests are just normal unit tests, they need to be with the other unit tests.

**Comment by viraj** [comment]
Thanks, But then...
1. why is it working on Xcode 7.2 ?
2. why is it working even on Xcode 7.3 when we manually load the app into foreground ?
BTW if I add my KIF tests into unit test target I get error at 
#import <KIF/KIF.h>
Because KIF is part of vttUITests target not vttTests. Kindly see my Podfile. If all that are wrong then why is it working on Xcode 7.2 ?

**Comment by phatmann** [comment]
In your Podfile KIF should be added to vttTests not vttUITests.

KIF is not designed to work in a UITests target. It may have worked in Xcode 7.2 but this was a happy accident.

**Comment by viraj** [comment]
Thanks @phatmann all good now. I will close the issue.
