### ISSUE TITLE
KIF Integration issue  with Xcode 7.3

### ISSUE THREAD

**Issue by Manoj412** [kif-framework/KIF#848]
Hi,

I am also facing an  issue . In Xcode 7.2 its worked fine. but in Xcode 7.3 I am facing this issue. 
So How you solve this? Please help its almost wasted 3 days .

`Failed to load test bundle from file:///private/var/containers/Bundle/Application/.../LibraryNotFoundDemo.app/PlugIns/LibraryNotFoundDemoTests.xctest: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/var/containers/Bundle/Application.../LibraryNotFoundDemo.app/PlugIns/LibraryNotFoundDemoTests.xctest/LibraryNotFoundDemoTests): Library not loaded: @rpath/KIF.framework/KIF
` 

From one of post in KIF issues I found its cocoa pod issue . So now i added directly into my project with same build settings in test target but still same issue.

**Comment by vasarhelyia** [comment]
And it's also the case when using Carthage, so I don't think it's a CocoaPods issue. I have no idea what it is though, unfortunately. [Here's the project](https://github.com/NSBudapest/TodoList-Swift) with the applied workaround described in #822, if you'd like to reproduce.

**Comment by Manoj412** [comment]
Yes , I think its an issue with KIF in Xcode 7.3

**Comment by phatmann** [comment]
Will take a look at sample project, thanks.

**Comment by phatmann** [comment]
The problem is that your KIF tests are part of the `vttUITests` target instead of the `vttTests` target. Since KIF tests are just normal unit tests, they need to be with the other unit tests.

**Comment by viraj** [comment]
@phatmann I think your last comment is related to my issues #844 which is similar to this :)

**Comment by phatmann** [comment]
@Manoj412: are you using a unit tests target or UI tests target?

**Comment by Manoj412** [comment]
@phatmann :  I am using unit tests target

**Comment by kennebecstars** [comment]
I have an issue related to Xcode 7.3.1 where my app won't run with both KIF and XCTest as optional link libraries. I had build KIF using carthage with versions >= KIF 3.4.1

I get this dyld out of the loader:

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: ./MyApp/build/Products/Debug-iphonesimulator/KIF.framework/KIF
  Reason: image not found

**Comment by kennebecstars** [comment]
Should I just remove the KIF and XCTest framework entries from the build. I hope I'm right about this: KIF setup of the app target should have KIF & XCTest frameworks as optional, but I usually remove these before final deployment of the release build.

**Comment by Manoj412** [comment]
Did KIF issue resolved in latest XCode 7.3 or 7.3.1 ?

**Comment by kennebecstars** [comment]
7.3.1
