### ISSUE TITLE
Create page objects with KIF

### ISSUE THREAD

**Issue by kudlatyCode** [kif-framework/KIF#853]
Hi, i wanted to create PageObjects with KIF, so i extended KIFTestActor and create helpers for each sceen in app. 
Now the problem is that every exception make crash.
How should i init objects that inherit from KIFTestActor?

**Comment by phatmann** [comment]
Can you share some code? I have done something similar in the past and I had no issues like this,

**Comment by kudlatyCode** [comment]
let's say we have Login screen to test, so i would like to create LoginPageObject
```
@interface LoginPageObject : KIFTestActor
- (void)loginTap;
@end
```
```
@implementation LoginPageObject
- (void)loginTap {
    [tester tapViewWithAccessibilityLabel:@"Login_button"]; // just simple code to clarify the problem
}
@end
```
i created this class with `[LoginPageObject new]`
and now, when view is not present on the screen, exception  crash test and test failure hint is not showing up in tests file. latter i tried `initWithFile:atLine:delegate`  but it's hard to find line when somethings goes wrong with test case. 

i managed to fix this by using "tester-like" macro, placed in LoginPageObject: 
```
#define login KIFActorWithClass(LoginPageObject)
```
 now it seems to be work fine, but i don't want to invoke methods on macro

**Comment by phatmann** [comment]
This was "fixed" by #849, which basically forces you to use the macro approach. So your workaround is correct. 

I am hoping we can get rid of the macros at some point. But for now we are stuck with them.

**Comment by kudlatyCode** [comment]
for that, entire exception handling mechanism would have to change, now i'm aware of this.
i will try to make pull request with better solution ;)

**Comment by phatmann** [comment]
If you can find a macro-less solution that @bnickel approves of, you will be the new KIF hero :-)

**Comment by CurlyHeir** [comment]
Just update for those that want to make Page Object before kif refactor - the workaround i made seems to be working for KIF, but don't work for OCMockito, xcode just mark line that failed in PageObject class, in tests it's not visible

**Comment by phatmann** [comment]
Thanks for the update.

**Comment by Nmbr-13** [comment]
Is it possible to make something similar in Swift (since there are no macros in Swift)?
