### ISSUE TITLE
KIF not detecting changes in UINavigationController stack

### ISSUE THREAD

**Issue by jessieserrino** [kif-framework/KIF#856]
I'm trying to get started writing UI tests using KIF because I want to make sure our navigation flow works.

It seems that KIF is not detecting changes in the `UINavigationController`. I have one view controller in a `UINavigationController` with a `UIButton` titled `Button0`. I have a second view controller with another `UIButton` titled `Button1`. On tap of `Button0`, it navigates to the second view controller. I wrote the following test to verify that the second view controller is being shown:

```
- (void)testTrySomeStuff
{
    [tester tapViewWithAccessibilityLabel:@"Button0"];
    [tester waitForViewWithAccessibilityLabel:@"Button1"];
}
```

When I present the second view controller modally on button tap, the preceding test passes. However, if I push it onto the `UINavigationController` stack, the test fails. Is there a workaround for the failure in the case of the `UINavigationController`, or am I missing something?

**Comment by mikelupo** [comment]
Look at that second button in the accessibility inspector. What is the accessibility label on that second button?

**Comment by jessie-serrino** [comment]
The accessibility label says Button1-- I manually added it in.

**Comment by jessie-serrino** [comment]
![image](https://cloud.githubusercontent.com/assets/1577899/15484878/140a6c62-20f1-11e6-9d67-796067c07a3f.png)

**Comment by mikelupo** [comment]
Jessie,
Sorry for the reply earlier.

I'm going to defer to @bnickel or @phatmann. 
If you have an example project that you can share, it might help bring about an answer quicker.


Thanks,
Mike




-----Original Message-----

**Comment by jessie-serrino** [comment]
Hi Mike,

No worries, thanks for the speedy response! @bnickel and @phatmann can look at the sample project that I created here: https://github.com/jessie-serrino/kif-experimentation/

**Comment by bnickel** [comment]
The problem you've run into is that your testing target is an iOS UI Testing Bundle rather than an iOS Unit Testing Bundle.  Somewhat ironically, KIF needs to be in a unit testing bundle because it runs inside the app's code and UI testing bundles run outside of the app.

**Comment by jessie-serrino** [comment]
Perfect, thank you so much for the response. I just changed that, and the sample project now works. I'm going to now reflect that in the real project I'm using KIF for.
