### ISSUE TITLE
Lost connection to test manager service

### ISSUE THREAD

**Issue by ciminuv** [kif-framework/KIF#867]
I am not sure this is KIF issues or not but this happen randomly only when running UI tests target (KIF).

Environment: 
XCode: 7.3.1
KIF: 3.4.2

Has anyone encountered this problem before?

**Comment by mikelupo** [comment]
@ciminuv I have not encountered this. I use KIF daily with Xcode 7.2 and 7.3.1. I don't install from Cocoapods though. I directly integrate KIF as a sub-project into my own code-base.

Make sure that your test target is a UNIT test target and not a UI test target. 
Many people newer to KIF do that. It sounds to me like your tests work OK though.

@bnickel this sounds like code you'd be familiar with. Any hints on what else could cause this?

Thanks,
Mike

**Comment by ciminuv** [comment]
@mikelikespie: I have worked with KIF in a few different projects and of course all the tests passed normally, but sometime a few (1-2) tests getting failure cause by `Lost connection to test manager service`.

Some more information that might be helpful to you. I installed KIF via `cocoapods` version `1.0.0`, and use KIF together with [Quick](https://github.com/Quick/Quick).

Thanks.
![screen shot 2016-05-28 at 8 53 07 pm](https://cloud.githubusercontent.com/assets/6657053/15627700/6711aafa-2516-11e6-93ff-482cc3b5ec32.png)

**Comment by mikelupo** [comment]
@ciminuv 
I don't know much (more like anything) about Quick. I wonder if there is a conflict between Quick and KIF? I've been using KIF for a few years now and I can say without abandon that I've never experienced a disconnect from the test manager.

@abbeyjackson, have you encountered anything like this? If so, how did you resolve it?

**Comment by abbeyjackson** [comment]
No actually I've never seen this! @ciminuv you might want to post on Quick also. Hopefully one of the KIF developers will reply here. I'm not too familiar with the inner workings of KIF so I don't really have a suggestion about what could be the issue.

**Comment by CurlyHeir** [comment]
i had this problem, the reason: something is still performing when tests ends unexpected. 
i don't know what exactly provides this behaviour, but i get rid of those failures by restarting app for each KIFTestCase

**Comment by phatmann** [comment]
You are probably using a UI Test target instead of a Unit Test target.

Tony
