### ISSUE TITLE
Javascript Core crash when increasing animation speed

### ISSUE THREAD

**Issue by foulkesjohn** [kif-framework/KIF#874]
I'm seeing this crash when I set animation speed set to anything greater than 1:

```
bool _WebTryThreadLock(bool), 0x7fc0cb9cfd80: Multiple locks on web thread not allowed! Please file a bug. Crashing now...
1   0x10c92d34e WebRunLoopLock(__CFRunLoopObserver*, unsigned long, void*)
2   0x105753c37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
3   0x105753ba7 __CFRunLoopDoObservers
4   0x1057496a9 __CFRunLoopRun
5   0x1057490f8 CFRunLoopRunSpecific
6   0x10c92d325 RunWebThread(void*)
7   0x1064ef99d _pthread_body
8   0x1064ef91a _pthread_body
9   0x1064ed351 thread_start
```

Animation speed set like so: `[[UIApplication sharedApplication] setAnimationSpeed:100];`

This happens at different points during tests. There are a few UIWebView's in the app, they aren't constantly on screen and get removed inbetween tests. The web views only ever display HTML strings, they don't make any requests to the network.

**Comment by botwin** [comment]
I am also seeing this crash under the same circumstances as described above. We have increased our animation speed and are getting this crash at what appear to be random points throughout our tests. We also suspect UIWebView involvement, as we do have some webviews visible in various places throughout the app.

Please let me know if there's anything I can do to help diagnose the issue.
