### ISSUE TITLE
KIF Test Crash at UIView-KIFAdditions.m class

### ISSUE THREAD

**Issue by YuvarajManickam** [kif-framework/KIF#882]
Hi Team,

Am an iOS developer and I want to write UI automation testing for one of my projects. I have did the following steps to setup the environment,
1. Create  a new project (KIFDemo) with “**Include Unit Tests**” and “**Include UI Tests**”.
2. Created a Login page with “Username, Password TextFields and Login button”. Added Accessibility Label values.
3. Added KIF through Cocoa Pod like this

> target 'KIFDemo' do
>   # Uncomment this line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for KIFDemo
> 
>   target 'KIFDemoTests' do
>     inherit! :search_paths
>     # Pods for testing
>     pod 'KIF', '~> 3.2.0'
>     pod 'Specta', '~> 1.0.2'
>   end
> 
>   target 'KIFDemoUITests' do
>     inherit! :search_paths
>     # Pods for testing
> 
>   end
> 
> end
1. Created one UITests.m (SubClass of KIFTestCase) under “KIFDemoTests” folder.
2. I have added this “beforeAll” function and code,

> - (void)beforeAll {
>   
>   [tester enterText:@"user@example.com" intoViewWithAccessibilityLabel:@"UsernameTF"];
>   [tester enterText:@"thisismypassword" intoViewWithAccessibilityLabel:@"PasswordTF"];
>   
>   [tester tapViewWithAccessibilityLabel:@"LoginButton"];
>   }
1. When I try to test this, am getting crash on following line,

> // Handle touches in the normal way for other views
>     UITouch *touch = [[UITouch alloc] initAtPoint:point inView:self];
>     [touch setPhaseAndUpdateTimestamp:UITouchPhaseBegan];
> 
> ```
> UIEvent *event = [self eventWithTouch:touch];
> 
> [[UIApplication sharedApplication] sendEvent:event];// Getting Thread 1: EXC_BAD_ACCESS 
> ```

Can anyone please help me to fix this and test the app?  Looking forward help. Thanks in advance.

Thanks,
Yuvaraj M

**Comment by phatmann** [comment]
Are you using a UI test or a Unit test?

**Comment by YuvarajManickam** [comment]
@phatmann  Am very new to test cases. Yes I want to do UI test for iOS app. I have setup the configuration for Xcode and doing simple test cases. Am not able to dismiss the "UIAlertController" by clicking the buttons. 

> UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"KIF Demo" message:@"This is TV Screen Alert" preferredStyle:UIAlertControllerStyleAlert];
>     
>     UIAlertAction *okAction = [UIAlertAction actionWithTitle:@"Ok" style:UIAlertActionStyleCancel handler:^(UIAlertAction * _Nonnull action) {
>         
>     }];
>     
>     [alert addAction:okAction];
>     [self presentViewController:alert animated:YES completion:^{
>         
>     }];

Test case:

> [tester tapViewWithAccessibilityLabel:@"Ok"];

Can you please help me? Thanks.

**Comment by mikelupo** [comment]
@phatmann asked if you set the test suite up as a UI Test or Unit Test suite. We understand that you want to run tests that interact with the UI. Else you would not be using KIF ;)

KIF relies on the UNIT test framework. Not the UI test framework. It's a bit confusing because KIF is interacting with the UI yet you need to use KIF inside a unit test project.  Not a UI test project.

**Comment by YuvarajManickam** [comment]
@mikelupo  and @phatmann Sorry for the misunderstanding :). Am trying to do the UI testing for the existing app. Am able to execute the test cases without any errors. Now, I need your help on tapping UITabBarController tab bar buttons. I have added three UIViewControllers to the UITabBarController in Storyboard. Also, I have added the "Accessibility label" to the tab bar items but, couldn't tap the tab bar item in KIF test case. 
Am not able to tap the UITabBarController, Not able to dismiss the UIAlertController "Ok" button action.

Can you please help me on this? Thanks.

"- (void)beforeAll {
    
    // Entering the username, password
    [tester enterText:@"user@example.com" intoViewWithAccessibilityLabel:@"UsernameTF"];
    [tester enterText:@"thisismypassword" intoViewWithAccessibilityLabel:@"PasswordTF"];
    
    // Tapping Login button
    [tester tapViewWithAccessibilityLabel:@"LoginButton"];

    // Tapping UITabBar Buttons.. This is not executing..
    [tester tapViewWithAccessibilityLabel:@"HomeTab"];
    [tester tapViewWithAccessibilityLabel:@"GalleryTab"];
    [tester tapViewWithAccessibilityLabel:@"SettingsTab"];
    
    // Selecting Table view row
    [tester tapRowAtIndexPath:[NSIndexPath indexPathForRow:2 inSection:0] inTableViewWithAccessibilityIdentifier:@"HomeTV"];
    
    // Tapping UIButton
    [tester tapViewWithAccessibilityLabel:@"ShowAlertButton"];

    // Trying to dismiss UIAlertView. This is not executing.. 
    [tester tapViewWithAccessibilityLabel:@"Ok"];
}"

**Comment by mikelupo** [comment]
Can you put together a small foo project that exemplifies the problem? Zip it up
And attach it? 

Thanks

**Comment by YuvarajManickam** [comment]
@mikelupo Thank you for your reply. I have attached the demo application which has KIF framework installed. I have "UITests" test case file under "KIFDemoTests" folder. I need your help on following items,

1. How to scroll UITableview till the end?
2. How to click the button in UITableViewCell?
3. How to dismiss the UIAlertController button?

Can you please help me on this? Looking forward your help. Thanks. 

[KIFDemo.zip](https://github.com/kif-framework/KIF/files/370866/KIFDemo.zip)

**Comment by YuvarajManickam** [comment]
@mikelupo Can you please debug my demo project and let me know where am going in a wrong way? Looking forward your reply. Thanks.

**Comment by mikelupo** [comment]
@YuvarajManickam 
Let me suggest a site (by Ray Wenderlich) that can perhaps help get you started. It helped me. 
[UI Testing with KIF](https://www.raywenderlich.com/61419/ios-ui-testing-with-kif)

Your HomeTV table has every row with exactly the same text and exactly the same Accessibility Label. Accessibility labels must be unique! Else, it's ambiguous to KIF.
I fixed that in your HomeViewController. You will see how I dynamically add the accessibility labels (I avoid using the storyboard for setting labels if I can help it) 
See the attached zip file.

Scrolling:
Also, you can look at the tests that come with KIF (for the purpose of testing KIF itself). There are scrolling tests in there. You can use that as an example. 
Also, I have included a way that I like to scroll about my own apps in the attached zip file. It's implemented in your testExample test case.

Buttons
Again, you have to use proper accessibility labels. You can tap any button that is created by and displayed by your app. 

Like you I (surprisingly) cannot tap the button in the alert view in your app.
I cannot recall every having this issue with my  own apps. I can see the visible button change upon the tap, but no action is processed. 

@phatmann can you chime in?


** caveats:I do not use cocoapods in my projects. I use KIF xcodeproj directly in my project, link and build. 
[KIFDemo.zip](https://github.com/kif-framework/KIF/files/373848/KIFDemo.zip)

**Comment by YuvarajManickam** [comment]
@mikelupo  Thanks a lot for your help. I will go through your commends and the code. Thanks again. Ve a great day!
