### ISSUE TITLE
PullToRefresh tests are failing

### ISSUE THREAD

**Issue by phatmann** [kif-framework/KIF#886]
On Travis one or more PullToRefresh tests are failing on iOS 9 iPad Air:

Failing tests:
    -[AccessibilityIdentifierPullToRefreshTests testPullToRefreshByAccessibilityIdentifierWithDuration]
    -[PullToRefreshTests testPullToRefreshByAccessibilityLabelWithDuration]
    -[PullToRefreshTests testPullToRefreshWithBigContentSize]

@mikelupo: Can you please look into this? Until we fix this, Travis tests will remain flakey. If we cannot fix in the short term, I might disable these tests so we can at least get a general idea of KIF health.

**Comment by mikelupo** [comment]
@phatmann Thank you for the information. 
I will look at this this week. By EOBD (east coast time) on Friday.

**Comment by mikelupo** [comment]
@phatmann Brief update:
I have Xcode 7.3. With the iPad air 9.3 I don't have the issue with the tests failing. 
I'll be setting up a Docker image to run the tests locally as described in [Running Travis locally ](http://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally). 
Will advise....

**Comment by mikelupo** [comment]
@phatmann  
Scrapped the idea of running docker locally. It's a bit too involved.
Installed Xcode 7.2. Re-ran the test suite from xcode on the iPad Air 9.2 and still the tests are running and passing 100%. 
Any ideas to help would be appreciated.

**Comment by kenji21** [comment]
you might test with Xcode 7.3 / iPad 9.2 to check if it is linking with the latest SDK that make your test fail.

**Comment by mikelupo** [comment]
@phatmann  @kenji21  Did as you suggested. No change. All tests pass.
Is anyone in this audience able to run travis tests locally in docker?

**Comment by justinseanmartin** [comment]
Nope, but I'll see if I can repro locally.

**Comment by phatmann** [comment]
@mikelupo: for now I am going to disable these tests, since they are stopping Travis from passing and they cover functionality that many clients won't use.
