### ISSUE TITLE
Why the hard cutoff for support at 8.4?

### ISSUE THREAD

**Issue by billburgess** [kif-framework/KIF#900]
My app currently supports iOS 8.0 and up and was curious why the hard cutoff at 8.4 vs 8.0? I can't find anything in the commits that prevents this. I wasn't sure how to get this question answered so I created an issue.

**Comment by phatmann** [comment]
Newer versions of Xcode don't have simulators that support anything below 8.4 and Travis has the same issue. I have also found that 8.0 has lots of weird bugs that are fixed by 8.4. so I would not personally support 8.0 in any case.

**Comment by justinseanmartin** [comment]
You can install the simulators back as far as iOS 8.1 in the Xcode > Preferences menu for Xcode 7.3.1. It seems reasonable to at least support back that far IMO.

The reason we recently bumped from supporting iOS 5+ (I think that was what it was set to) was different things were broken and/or untested on older versions.

**Comment by phatmann** [comment]
If you verify KIF works on 8.1 I will adjust project and podspec.

**Comment by justinseanmartin** [comment]
Letting CI do the work

**Comment by phatmann** [comment]
👍

**Comment by phatmann** [comment]
@billburgess: now KIF gives you 8.1 support thanks to @justinseanmartin's #901 work. Turns out 8.0 support was too tricky. Hope this works for you.

**Comment by billburgess** [comment]
This should help. Only having to cut support for 1 minor version vs 4 minor versions will help a lot. Thanks for looking into the issue. I'm sure it will help other developers that want to continue supporting iOS 8 users.

**Comment by justinseanmartin** [comment]
The project config changes should work with iOS 8.0, but the CI configuration on Travis seemed like it didn't have 8.0 simulators available, so I set it up to run against 8.1 sims.
