### ISSUE TITLE
isTappable does not work with TextField not visible behind another view

### ISSUE THREAD

**Issue by 1adormae** [kif-framework/KIF#902]
Returns yes is a TextField has a tapRecognizer but it hidden behind another view. 
The comment in the code says "// Is this view currently on screen?", so I would think it is checking also if the view is visible and tappable for a user. The method looks like: 
- (BOOL)isTappable;
  {
  return ([self hasTapGestureRecognizer] ||
          [self isTappableInRect:self.bounds]);
  } 
  Shouldn't the OR be and AND?

**Comment by phatmann** [comment]
Please see #395. Perhaps a similar approach is in order?

**Comment by 1adormae** [comment]
Hi again, 
I am not sure if I am right, but my problem is that the concept of isTappable only checks if the View is tappable in theory not if it actually would be tappable for a user. So you agree that this function should also check weather the view is actually visible and tappable for a user? If you agree I can work on a solution and make a pull request :-) Thanks man, you did great stuff!

**Comment by phatmann** [comment]
If a user can tap it, then KIF should recognize it as tappable. So yes please, submit a PR.
