### ISSUE TITLE
Clarify iOS support

### ISSUE THREAD

**Issue by bootstraponline** [kif-framework/KIF#903]
The documentation says:

> KIF's test suite has been run against iOS 5.1 and above (including iOS 9), though lower versions will likely work.

The pull request & .travis.yml say iOS 8+.

- https://github.com/kif-framework/KIF/pull/885

Does KIF only support iOS 8 and above?

**Comment by phatmann** [comment]
Good catch! Fixed 6d74b9c947.

**Comment by phatmann** [comment]
KIF officially supports iOS 8.1+ due to testing constraints. But it might work all the way back to iOS 5!

**Comment by bootstraponline** [comment]
Thanks!

**Comment by justinseanmartin** [comment]
The project is configured with 8.0+ supported

**Comment by phatmann** [comment]
I am okay leaving the project at 8.0, since KIF likely works just fine with that version of iOS. But if anyone thinks it should be 8.1, I will accept a PR.
