### ISSUE TITLE
No such module 'KIF' - cocoapods

### ISSUE THREAD

**Issue by ivanruizscm** [kif-framework/KIF#904]
I've installed KIF through cocoapods.

    source https://github.com/CocoaPods/Specs.git
    use_frameworks!
    
    target 'MyApp' do

         target 'MyAppUITests' do
	          pod 'KIF', '~> 3.0'
        end
    end

And then i installed the pod:
....
Installing KIF (3.4.2)

I created a bridging header in MyAppUITests target with the following:
#import <KIF/KIF.h>

And then when i try to import KIF:
![captura de pantalla 2016-09-02 a las 14 03 50](https://cloud.githubusercontent.com/assets/15628215/18203260/2672a62e-7116-11e6-9ec1-09eddd9ee691.png)

I'm using Xcode 7.3.1. I'm able to cmd+click KIFTestCase and see the contents, but if i remove the KIF import i cant build.

**Comment by phatmann** [comment]
KIF only works with unit tests, not UI tests.
