### ISSUE TITLE
Xcode Crash when there's a failure in `beforeAll`

### ISSUE THREAD

**Issue by designatednerd** [kif-framework/KIF#905]
This was a fun one. I got repeated crashes using Xcode 7.3.1, KIF 3.4.2 (sadly still haven't been able to drop 8 support), and Swift 2.2 when I had something in my `beforeAll` that would otherwise have simply caused a failure. 

Here's the stack trace I got, which doesn't appear to really have anything to do with that: 

```
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
NSFileHandleReadCompletionNotification
ProductBuildVersion: 7D1014
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-10188.1/IDEFoundation/Testing/OCUnit/IDEOCUnitTestRunner.m:1039
Details:  Assertion failed: [suiteRecord.suiteIdentifier isEqualToString:suiteIdentifier]
Object:   <IDEOCUnitTestRunner: 0x7f95b743f480>
Method:   -testSuite:willFinishAt:rawOutput:sessionState:
Thread:   <NSThread: 0x7f95d3e178e0>{number = 1, name = main}
Hints:   
  0: Creation Backtrace for Notification Token:

  0   -[_DVTNotificationReceiver initWithObserver:selector:] (in DVTFoundation)
  1   -[NSNotificationCenter(DVTNSNotificationCenterAdditions) dvt_addObserver:selector:name:object:] (in DVTFoundation)
  2   -[IDEConsoleAdaptor _addObserverToReadCompletion:selector:] (in IDEFoundation)
  3   -[IDEConsoleAdaptor _setStandardOutput:] (in IDEFoundation)
  4   -[IDEConsoleAdaptor initWithType:standardInput:standardOutput:standardError:] (in IDEFoundation)
  5   __41-[IDELaunchiPhoneSimulatorLauncher start]_block_invoke (in IDEiOSSupportCore)
  6   __43-[DVTDispatchLock asyncPerformLockedBlock:]_block_invoke (in DVTFoundation)
  7   __DVTDispatchBarrierAsync_block_invoke (in DVTFoundation)
  8   _dispatch_call_block_and_release (in libdispatch.dylib)
  9   _dispatch_client_callout (in libdispatch.dylib)
 10   _dispatch_queue_drain (in libdispatch.dylib)
 11   _dispatch_queue_invoke (in libdispatch.dylib)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   _dispatch_root_queue_drain (in libdispatch.dylib)
 14   _dispatch_worker_thread3 (in libdispatch.dylib)
 15   _pthread_wqthread (in libsystem_pthread.dylib)
 16   start_wqthread (in libsystem_pthread.dylib)

Backtrace:
  0   -[IDEAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in IDEKit)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _DVTAssertionFailureHandler (in DVTFoundation)
  4   -[IDEOCUnitTestRunner testSuite:willFinishAt:rawOutput:sessionState:] (in IDEFoundation)
  5   __117-[_IDETestManagerAPIMediator _XCT_testSuite:didFinishAt:runCount:withFailures:unexpected:testDuration:totalDuration:]_block_invoke (in IDEFoundation)
  6   -[_IDETestManagerAPIMediator _considerDispatchingDelegateBlock] (in IDEFoundation)
  7   __67-[_IDETestManagerAPIMediator parseConsoleOutputFromOriginalOutput:]_block_invoke (in IDEFoundation)
  8   -[_IDETestManagerAPIMediator parseConsoleOutputFromOriginalOutput:] (in IDEFoundation)
  9   -[IDEConsoleAdaptor _getData:overflowBuffer:] (in IDEFoundation)
 10   -[IDEConsoleAdaptor _getOutput:] (in IDEFoundation)
 11   DVTInvokeWithLazyFailureHint (in DVTFoundation)
 12   -[_DVTNotificationReceiver receiveNotification:] (in DVTFoundation)
 13   __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ (in CoreFoundation)
 14   ___CFXRegistrationPost_block_invoke (in CoreFoundation)
 15   _CFXRegistrationPost (in CoreFoundation)
 16   ___CFXNotificationPost_block_invoke (in CoreFoundation)
 17   -[_CFXNotificationRegistrar find:object:observer:enumerator:] (in CoreFoundation)
 18   _CFXNotificationPost (in CoreFoundation)
 19   -[NSNotificationCenter postNotificationName:object:userInfo:] (in Foundation)
 20   -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:] (in DVTFoundation)
 21   -[IDEMasterPtyFileHandle _gotData:] (in IDEFoundation)
 22   __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ (in CoreFoundation)
 23   ___CFXRegistrationPost_block_invoke (in CoreFoundation)
 24   _CFXRegistrationPost (in CoreFoundation)
 25   ___CFXNotificationPost_block_invoke (in CoreFoundation)
 26   -[_CFXNotificationRegistrar find:object:observer:enumerator:] (in CoreFoundation)
 27   _CFXNotificationPost (in CoreFoundation)
 28   -[NSNotificationCenter postNotificationName:object:userInfo:] (in Foundation)
 29   -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:] (in DVTFoundation)
 30   _performFileHandleSource (in Foundation)
 31   __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ (in CoreFoundation)
 32   __CFRunLoopDoSources0 (in CoreFoundation)
 33   __CFRunLoopRun (in CoreFoundation)
 34   CFRunLoopRunSpecific (in CoreFoundation)
 35   RunCurrentEventLoopInMode (in HIToolbox)
 36   ReceiveNextEventCommon (in HIToolbox)
 37   _BlockUntilNextEventMatchingListInModeWithFilter (in HIToolbox)
 38   _DPSNextEvent (in AppKit)
 39   -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (in AppKit)
 40   -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in DVTKit)
 41   -[NSApplication run] (in AppKit)
 42   NSApplicationMain (in AppKit)
 43  0x000000010a9b839b (in Xcode)
 44   start (in libdyld.dylib)

abort() called

Application Specific Signatures:
[suiteRecord.suiteIdentifier isEqualToString:suiteIdentifier]
```

I tried changing the name of the class, deleting and recreating the class, rebooting my computer, deleting derived data, running it on CI, and shouting very bad words at my computer. In all cases Xcode crashed with a very similar stack trace. 

However, when I moved what had been getting called in `beforeAll` to a test directly, it just failed. I refactored to fix the failure, and when I put it back into `beforeAll` Xcode crashage ceased. 

I'm not 100% sure if this is something on the KIF end or the Xcode end, but it does look like [there's a bit of magic going on with this](https://github.com/kif-framework/KIF/blob/v3.4.2/Classes/KIFTestCase.m#L79) to get it invoked as part of the class's `setUp` method but still be done as part of the instance of that test class. That link is to the 3.4.2 branch specifically but it appears the code is [about the same in `master`](https://github.com/kif-framework/KIF/blob/master/Classes/KIFTestCase.m#L76). 

Let me know if there's further information I can provide to help track this down.

**Comment by phatmann** [comment]
There have been various reports of failures in `beforeAll` causing issues, and there have been a myriad of fixes to address them. Based on your experiences, we clearly still have issues. To fix these issues might require a substantial rewrite of the XCTest integration code, and no one, including @bnickel, relishes that idea. Furthermore, it might be a basic problem with any XCTest integration, in that failure in `setUp` is not handled well. At this point I am not sure, but it bears further research.

I will leave this issue open so folks can chime in.

**Comment by johnkdoe** [comment]
i am seeing this same thing outside of KIF, running simple XC8 unit tests (well, maybe not so simple).

**Comment by phatmann** [comment]
@johnkdoe that is interesting. Can you determine the cause of the unit test crashes when not using KIF?

**Comment by designatednerd** [comment]
Still running into this issue, FWIW. 

My thought is it's got to do with the lifecycle of `XCTest` being a little weird with the static versions of `setUp` and `tearDown`. [Jon Reid's got a decent little article](http://qualitycoding.org/teardown/) on stuff around this, but I suspect because the failure is thrown when a test is not actually in progress, that's why it's crashing Xcode.

**Comment by justinseanmartin** [comment]
@bnickel - If you've got a sec, I'm curious on the historical context of introducing the before/after each/all variants. I assume something in OCUnit/SenTestingKit necessitated not just using the default setUp and tearDown? I can't determine it from scanning previous issues on the project, but didn't find a conclusive answer, but it appears to always have been this way.

It seems like we could deprecate them in favor of just using the builtin XCTest methods, but would be unnecessary churn if it weren't for this issue.

@designatednerd - Do you have a sample example project with a simple repro that could be investigated? Do you know if the issue happens if you try it with Xcode 8.x?

An alternative that you could use is to wrap the stuff you want executed only once in a `dispatch_once` block within the `beforeEach` method if it is causing problems for you.

**Comment by bnickel** [comment]
It had to do with failure handling I think. Failing in `setUp` would crash the test. Also, testers delegate logging to the instance of the test class. And maybe something about the output format needing the error to be inside a test to show up correctly in the error list.

**Comment by justinseanmartin** [comment]
Cool, thanks for the insight!
