### ISSUE TITLE
After resetting simulator waitForViewWithAccessibilityLabel: crashes

### ISSUE THREAD

**Issue by nkonforty** [kif-framework/KIF#907]
After resetting simulator ("Reset Content and Settings..") on the first test, on waitForViewWithAccessibilityLabel: KIFTestActor crashes on tryRunningBock:complete:timeout:error: 
(the test passes successfully when not resetting the simulator first )

![screen shot 2016-09-07 at 5 42 39 pm](https://cloud.githubusercontent.com/assets/14818973/18316393/13964360-7523-11e6-80b1-4f495414e6d0.png)

**Comment by mikelupo** [comment]
Hi. 
Same as your other bug, could use some context here.
Also, a host app that could reliably reproduce it is never a bad idea.

**Comment by nkonforty** [comment]
Hi, 
the problem is in our side, you can close this issue. 

Thanks!

**Comment by mikelupo** [comment]
Glad you resolved it and thanks for using KIF.
