### ISSUE TITLE
Podspec changed without version change

### ISSUE THREAD

**Issue by billburgess** [kif-framework/KIF#908]
After the minimum deploy target was changed, issue #900, the podspec version was not bumped or pushed up to the Spec repo, leaving the old one referencing 8.4 in place. Can we get someone to either increment the version to 3.5.1 and push up the new Spec, or overwrite the existing podspec that is in place now so that clean installs will work with the new changes?

**Comment by phatmann** [comment]
Will do ASAP

**Comment by billburgess** [comment]
Thanks!

**Comment by phatmann** [comment]
Done
