### ISSUE TITLE
Crash on XCode8 , iOS SDK 10, [KIFTestActor _enableAccessibility]

### ISSUE THREAD

**Issue by miserya** [kif-framework/KIF#910]
-[AccessibilitySettingsController setAXInspectorEnabled:specifier:]: unrecognized selector sent to instance 0x7f9673005600
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AccessibilitySettingsController setAXInspectorEnabled:specifier:]: unrecognized selector sent to instance 0x7f9673005600'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f48234b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ee5421e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f4f1f34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010f407c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010f407798 _CF_forwarding_prep_0 + 120
	5   IAWLSample                          0x000000011f43e097 +[KIFTestActor _enableAccessibility] + 711
	6   IAWLSample                          0x000000011f43dd98 +[KIFTestActor load] + 72
	7   libobjc.A.dylib                     0x000000010ee562ce call_load_methods + 715
	8   libobjc.A.dylib                     0x000000010ee56da3 load_images + 70
	9   ???                                 0x000000010ba61c5e 0x0 + 4490402910
	10  ???                                 0x000000010ba6d0aa 0x0 + 4490449066
	11  ???                                 0x000000010ba6c23a 0x0 + 4490445370
	12  ???                                 0x000000010ba6c2cf 0x0 + 4490445519
	13  ???                                 0x000000010ba649eb 0x0 + 4490414571
	14  ???                                 0x000000010ba68c20 0x0 + 4490431520
	15  libdyld.dylib                       0x0000000111594ea4 dlopen + 59
	16  CoreFoundation                      0x000000010f434b09 _CFBundleDlfcnLoadBundle + 153
	17  CoreFoundation                      0x000000010f43498d _CFBundleLoadExecutableAndReturnError + 333
	18  Foundation                          0x000000010e93ae4e -[NSBundle loadAndReturnError:] + 521
	19  IDEBundleInjection                  0x000000010bae17c1 __XCBundleInjection + 1036
	20  ???                                 0x000000010ba7122b 0x0 + 4490465835
	21  ???                                 0x000000010ba7142e 0x0 + 4490466350
	22  ???                                 0x000000010ba6d0bc 0x0 + 4490449084
	23  ???                                 0x000000010ba6c23a 0x0 + 4490445370
	24  ???                                 0x000000010ba6c2cf 0x0 + 4490445519
	25  ???                                 0x000000010ba62048 0x0 + 4490403912
	26  ???                                 0x000000010ba65706 0x0 + 4490417926
	27  ???                                 0x000000010ba61249 0x0 + 4490400329
	28  ???                                 0x00007fff694b77ac 0x0 + 140734959941548
	29  ???                                 0x00007fff694b604f 0x0 + 140734959935567
	30  ???                                 0x00007fff694b2276 0x0 + 140734959919734
	31  ???                                 0x00007fff694b2036 0x0 + 140734959919158
	32  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by phatmann** [comment]
Are you using KIF in a UI Test instead of a Unit Test?

**Comment by lgauthier** [comment]
I just experienced the same crash (in a unit test). It looks like the issue has already been addressed though with this commit: 1c67bcbb0bb24dc150c4bbde70f6b321105df2ff

I just updated to 3.5.1 and the crash is fixed.

**Comment by phatmann** [comment]
Thanks for the update, @lgauthier! I will close the issue.
