### ISSUE TITLE
UserNotification Support

### ISSUE THREAD

**Issue by sirnacnud** [kif-framework/KIF#913]
iOS 10 added support to display notifications (local & remote) while the app is in the foreground using the system notification look. Has anyone had luck in getting KIF to interact with these notifications? I tried using `waitForViewWithAccessibilityLabel`, with the accessibility label provided by Accessibility Inspector, but it fails to find it.

**Comment by phatmann** [comment]
Like many system dialogs, these notification windows are probably running in a system process and are therefore not reachable via KIF and the accessibility engine. That said, there might be private APIs to allow this, so I will leave this issue open in the hope that we can find a way to get at these.

**Comment by sirnacnud** [comment]
I actually can up with a solution that overrides the `UNUserNotificationCenterDelegate` in order to detect when a notification will be displayed. It will work for detecting when either a remote or local notification is displayed while the app is in the foreground. I will try to get a PR up shortly.

**Comment by mikelupo** [comment]
That's cool. Is there any black magic way to prevent the notification from appearing or to handle it programmatically [especially] in the case that it is a system note?

**Comment by sirnacnud** [comment]
`USUserNotificationCeneterDelegate` only handles notifications for your app. If a notification is displayed from another app or the system, you won't be notified of it.

**Comment by krisdyZJU** [comment]
@sirnacnud, any update on this, for all kinds of system dialogs, I eager to find a way to handle them automatically in my automatic testing, thanks.

**Comment by mikelupo** [comment]
There is no way to dismiss system dialogs on the actual device using KIF (or any other app)
Apple security simply does not allow it.

That's not to say you can't with a jail broken device. Though I've never jail broken an iOS device so I cannot attest to this.

**Comment by krisdyZJU** [comment]
thanks @mikelupo 
System dialogs is now really a big stopper for CI automation, but as you say, currently there may be no good way to prevent it on a non-jail broken device...

**Comment by mikelupo** [comment]
Very welcome.
One thing that I have done to workaround dialogs, is to prevent them in the first place. For example, in our UI test suite we conditionally stop the app from registering with Apple push services.
But if your app is doing things like accessing photos, then yeah, you'll get them darn dialogs the first time.


I have thought of some interesting ways to get around this in a non-jailbroken way but would require some robotic hackery and coming up with a recipe that others could follow with relative ease.



What this world needs is a mobile testing conference. A place to share such ideas, inspire and be inspired. I'm off-topic now.
end of rant.






-----Original Message-----

**Comment by justinseanmartin** [comment]
We've used the same approach to swizzle and prevent requests for Location/Push and instead replace the APIs with fakes that we can control in our tests and don't end up prompting a system alert.

**Comment by mikelupo** [comment]
Could probably do that with other permission requiring APIs as well, but that does nothing to grant you access to the API. I wonder out loud though, if you somehow knew/assumed the screen coordinates for the OK button, is there some other sort of screen tap that could work (short of a physical mechanical device)?




-----Original Message-----
