### ISSUE TITLE
Non public API uses

### ISSUE THREAD

**Issue by muzammil-triffort** [kif-framework/KIF#914]
I have submitted my new iOS app update on iTunes after adding KIF. After processing on iTunes, I got a mail from itunes connect that my app contains Private API uses (which is used inside KIF).
###### 

_We have discovered one or more issues with your recent delivery for "My App Name". To process your delivery, the following issues must be corrected:_

**Non-public API usage:**

The app references non-public symbols in oogababyHealth: _IOHIDEventAppendEvent, _IOHIDEventCreateDigitizerEvent, _IOHIDEventCreateDigitizerFingerEventWithQuality, _IOHIDEventSetIntegerValue

Please let me know how to fix this.

Best, Muzammil

**Comment by phatmann** [comment]
Sorry to hear this. How are you adding KIF to your project? You need to make sure the KIF library is added to your test target and not your app target.

**Comment by muzammil-triffort** [comment]
Okay, I see. That could be the issue as I have added this in both App and Test Targets. Will try this again. Thank you.

**Comment by muzammil-triffort** [comment]
Hi @phatmann, After removing KIF from main project target and only added for Test Targest (via Pods) I am getting new error 'XCTest' not found. I rechecked all project files to make sure they are added for Main Project but no luck. Any suggestion?

**Comment by phatmann** [comment]
Please post your Podfile so I can look at it. I am wondering if you are adding KIF to the UI Test Target rather than Unit Test Target by mistake.
