### ISSUE TITLE
Undefined symbol in armv7

### ISSUE THREAD

**Issue by pratimas** [kif-framework/KIF#917]
I am getting this linker error from KIF library.
Any help will be appreciated.

Undefined symbols for architecture armv7:
  "_OBJC_IVAR_$_UITouch._touchFlags", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in ---
  "_OBJC_IVAR_$_UITouch._tapCount", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
  "_OBJC_IVAR_$_UITouch._timestamp", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
      -[UITouch(Synthesize) setPhase:] in libVerifayaStudio.a(UIQuery.o)
      -[UITouch(Synthesize) setLocationInWindow:] in 
  "_OBJC_IVAR_$_UITouch._window", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
  "_OBJC_IVAR_$_UITouch._view", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
  "_OBJC_IVAR_$_UITouch._previousLocationInWindow", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
      -[UITouch(Synthesize) setLocationInWindow:] in l
  "_OBJC_IVAR_$_UITouch._phase", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
      -[UITouch(Synthesize) setPhase:] in
  "_OBJC_IVAR_$_UITouch._locationInWindow", referenced from:
      -[UITouch(Synthesize) initInWindow:withLocation:] in 
      -[UITouch(Synthesize) setLocationInWindow:] in 
ld: symbol(s) not found for architecture armv7

**Comment by phatmann** [comment]
Are you using KIF from a UI Test instead of a Unit Test?
