### ISSUE TITLE
Fails in release mode

### ISSUE THREAD

**Issue by RobinClowers** [kif-framework/KIF#918]
When I try to compile kif in release mode, I get errors about undefined symbols for `x86_64`. Is this normal? Or am I doing something wrong?

I'm on xcode 8.0, using KIF 3.5.1.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_KIFSystemTestActor", referenced from:
      objc-class-ref in TestSupport.o
  "_OBJC_CLASS_$_KIFTestActor", referenced from:
      l__CATEGORY_KIFTestActor_$_Acceptance_Tests in TestSupport.o
  "_OBJC_CLASS_$_KIFTestCase", referenced from:
      _OBJC_CLASS_$__TtC16Acceptance_Tests15SimpleSwiftTest in RefuelTest.o
  "_OBJC_CLASS_$_KIFUITestActor", referenced from:
      objc-class-ref in TestSupport.o
  "_OBJC_METACLASS_$_KIFTestCase", referenced from:
      _OBJC_METACLASS_$__TtC16Acceptance_Tests15SimpleSwiftTest in RefuelTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by phatmann** [comment]
Does it compile fine in Debug mode? Why do you need to compile it in Release mode?

**Comment by RobinClowers** [comment]
It does compile in debug mode, but I'm trying to run kif tests again a react-native project on a CI server, and it needs to be in release mode to bundle all the assets correctly.

**Comment by mikelupo** [comment]
My suspicion is in your build settings. 
If you don't end up figuring it out on your own, create a small "foo" project that exemplifies the issue. ZIp it up and attach along with any necessary reproduction instructions.  I'll take a look.


Sorry if you get this twice. I'm in a bad connectivity area.






-----Original Message-----

**Comment by RobinClowers** [comment]
I can do that, but just to be clear, should KIF compile for x86_64? Or should my build not target that architecture?

**Comment by phatmann** [comment]
KIF can run on simulator or the device. So targeting x86_64 is valid.
