### ISSUE TITLE
Support for tvOS?

### ISSUE THREAD

**Issue by CodingItWrong** [kif-framework/KIF#922]
Has anyone looked into the possibility of adding tvOS support to KIF? If not, it's something I'd be interested in investigating to see how feasible it would be. tvOS seems pretty closely related to iOS, so I imagine the main differences would be the UI paradigm. What little of XCUI testing I was able to get working recorded individual up/down/left/right button clicks, but a KIF test targeting focusable views by accessibility ID/label would make for much more readable and robust tests.

**Comment by phatmann** [comment]
You are the first to ask. Please go for it!

Tony

**Comment by billburgess** [comment]
+1 I would kill for tvOS support. I have several radars outstanding for issues with Apples own UI Testing. Recording is busted. There just isn't a great way to write UI tests for tvOS. Not to mention mocking and stubbing in not possible with how UI tests run for XCUITest. Please please please bring KIF to tvOS.
