### ISSUE TITLE
My app crashes with error "Symbol not found" on IOS 10

### ISSUE THREAD

**Issue by tannguyen1011** [kif-framework/KIF#923]
Hi,

I have added a customize UITouch class in my app. However, my app crashes with below error once running on iOS 10

Termination Description: DYLD, Symbol not found: _OBJC_IVAR_$_**UITouch._locationInWindow**

Could you help me resolve my problem?

Thank you in advance!

**Comment by phatmann** [comment]
What kind of test target are you using?

**Comment by tannguyen1011** [comment]
I am checking on iOS native app.

**Comment by phatmann** [comment]
Are you using a Unit Test target or UI Test Target for KIF?

**Comment by tannguyen1011** [comment]
I am using KIF framework to stimulate touch action on UI test target.

**Comment by phatmann** [comment]
KIF only supports unit tests targets, not UI test targets.
