### ISSUE TITLE
QLPreviewController content

### ISSUE THREAD

**Issue by davbeck** [kif-framework/KIF#926]
I've run into an issue testing QLPreviewController. For instance, using a txt file, the accessibility inspector shows a value of the files contents, but KIF times out waiting for it.

<img width="1440" alt="screen shot 2016-11-14 at 8 11 31 am 2" src="https://cloud.githubusercontent.com/assets/340006/20272209/15f5c366-aa42-11e6-91bf-69a5582805d0.png">

```swift
tester().waitForView(withAccessibilityLabel: nil, value: "This is a file attachment.", traits: UIAccessibilityTraitNone)
```

**Comment by phatmann** [comment]
Many of these system dialogs run in a different process and KIF cannot see them. That is probably what is going on here. Unfortunately, I don't have a workaround to suggest, but take a look at #510 to see if that will help you out.
