### ISSUE TITLE
No way to test WKWebView content

### ISSUE THREAD

**Issue by joseph-cliqz** [kif-framework/KIF#931]
I have a web view where html body is initially empty and html content is added dynamically using javascript. When I load the web view in my application, the modified html content is visible but if I try to search for an element in the loaded web view using javascript , and I’m accessing WebView using KIF and it returns an empty body with no children or childNodes.   I have tried adding delays, however i get the same result. I wonder if KIF has problems with testing Webview with dynamic content?

**Comment by phatmann** [comment]
Dup of #708.
