### ISSUE TITLE
Increased running time on macOS Sierra (10.12)

### ISSUE THREAD

**Issue by reidmain** [kif-framework/KIF#933]
Has anyone else noticed an increase in the running time of their tests when updating to macOS Seirra?

I recently provisioned three additional Mac Minis, running Sierra, for our CI cluster and they take about 32-34 minutes to run our test suite while our two other Mac Minis still running El Capitan (10.11) complete the same suite in 24 minutes.

I then took a MacBook Pro we had lying around and ran the tests in El Capitan. They consistently finished in 23 minutes but when I upgraded to Sierra the running time increased to 27 minutes.

I have turned on "Reduce Motion" and "Reduce Transparency" under the display accessibility features but it does not seem to have made a difference.

Some quick Googling hasn't raised any obvious flags that could be affecting performance and none of the other major testing frameworks seems to have any issues regarding this. Perhaps not many people have upgraded their CI nodes to Sierra?

**Comment by reidmain** [comment]
Gladly but what kind of profiling or diagnostics would be most useful in this kind of situation?

My first thought was to gather the output from the build and extract the running times of each test, compare the percentage increase in runtimes and see if there is similar gains across the board or only to certain tests. From there I could maybe try to figure out if there is something about certain tests that are causing this.

**Comment by phatmann** [comment]
Extracting running times sounds like a good start.
