### ISSUE TITLE
any way to dismiss system dialog on device until now?

### ISSUE THREAD

**Issue by krisdyZJU** [kif-framework/KIF#938]
I searched in all issues, and find some discussion about this( I list them as below), but it seems kif can only achieve this on simulator, is there any way to dismiss system dialog on device?

Add support for dismissing system alerts [https://github.com/kif-framework/KIF/pull/510](url)
UserNotification Support [https://github.com/kif-framework/KIF/issues/913](url)
Restore on device testing [https://github.com/kif-framework/KIF/pull/520](url)

**Comment by phatmann** [comment]
Simulator only, sorry!
