### ISSUE TITLE
Can't access to my swift code through an swift class created on KIF Testing Target

### ISSUE THREAD

**Issue by Rolvar** [kif-framework/KIF#941]
I am working on a project with both swift and obj-c code, and I am making some UI test with KIF. I can access to some enums and values from objc classes but when I try to do the same with some enums on swift classes I can't access to them.

The UI Test cases are written in Swift, and I already did the tester and system extensions and import KIF on bridging header.

Could you help me please?

thanks in advance!

**Comment by phatmann** [comment]
Can you please post some sample code?
