### ISSUE TITLE
dyld: Library not loaded:XXXXXXXXXX  Reason: image not found

### ISSUE THREAD

**Issue by lidongyang-Leo** [kif-framework/KIF#942]
Xocde: 8.1
language: Swift 3.0

I use CocoaPods KIF, but  command + R run this Project, this error 
<img width="555" alt="2017-02-07 9 59 58" src="https://cloud.githubusercontent.com/assets/21758593/22674693/4ef67af8-ed1c-11e6-8665-a55c2a84adaf.png"> 

how to solve this issues?

**Comment by phatmann** [comment]
Make sure KIF is in a Unit Test bundle, not a UI test bundle nor your main app.

**Comment by justinseanmartin** [comment]
A couple other things:
1. Make sure you've got XCTest as a linked dependency in your test target
2. Make sure that the "Runpath Search Paths" variable is configured with the defaults for the test target. For a test target it should be `$(inherited) @executable_path/Frameworks @loader_path/Frameworks`

**Comment by snowywolfie** [comment]
I faced the same issue after I clean my my project. However I solved it with a tricky way. You run the test first. Then only go build+run.

**Comment by justinseanmartin** [comment]
@arun-perk - That issue is not a KIF issue. I recommend asking on StackOverflow or elsewhere.
