### ISSUE TITLE
User cannot set `stopTest`

### ISSUE THREAD

**Issue by hfkansteiner** [kif-framework/KIF#943]
Most times, e.g. [here](https://github.com/kif-framework/KIF/blob/bcb58d0419cfaefe286f3df1c8618bac43b45921/Classes/KIFUITestActor.m#L90) it is not possible to set `stopTest`. I obviously agree as mentioned [here](https://github.com/kif-framework/KIF/pull/531#issuecomment-68266048) that it makes no sense to continue but in my case I would like to add some additional error handling within the test before terminating it manually.
I could create a pull request with an optional argument for `stopTest` so nothing changes for everyone who does not want to use it?

**Comment by phatmann** [comment]
Please make the PR and we can take a look. Thanks!

**Comment by justinseanmartin** [comment]
You could create a custom subclass of `KIFTestCase` for all your tests to use that overrides the behavior of `failWithException:stopTest:`.
