### ISSUE TITLE
Not able to run tests.Quitting simulator with following message in console.(Not using cocoapods)

### ISSUE THREAD

**Issue by dhanakrishnaiOSDev** [kif-framework/KIF#947]
objc[14044]: Class PLBuildVersion is implemented in both /Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x13e3644c) and /Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x13c77b78). One of the two will be used. Which one is undefined.
objc[14044]: Class SSKeychain is implemented in both /Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/StoreServices.framework/StoreServices (0x128c09f4) and /Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data/Containers/Bundle/Application/0BB1AAFA-9A1C-4832-9F4A-F4DADCEA1DFD. One of the two will be used. Which one is undefined.
2017-02-24 11:16:09.547[14044:103258] Failed to load test bundle from file:///Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/.xctest: Error Domain=NSCocoaErrorDomain Code=3585 "dlopen_preflight(/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/.xctest/Tests): no suitable image found.  Did find:
	/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/.xctest/Tests: mach-o, but wrong architecture" UserInfo={NSLocalizedRecoverySuggestion=Try installing a universal version of the bundle., NSFilePath=/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/Tests.xctest/Tests, NSLocalizedFailureReason=The bundle doesn’t contain a version for the current architecture., NSLocalizedDescription=The bundle “Tests” couldn’t be loaded because it doesn’t contain a version for the current architecture., NSDebugDescription=dlopen_preflight(/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/Tests.xctest/Tests): no suitable image found.  Did find:
	/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/Tests.xctest/Tests: mach-o, but wrong architecture, NSBundlePath=/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/PlugIns/.xctest}
2017-02-24 11:16:09.547 [14044:103258] IDEBundleInjection Arguments: (
    "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data/Containers/Bundle/Application/0BB1AAFA-9A1C-4832-9F4A-F4DADCEA1DFD/.app/",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
2017-02-24 11:16:09.548 [14044:103258] IDEBundleInjection Environment: {
    "CFFIXED_USER_HOME" = "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data/Containers/Data/Application/EF4CC38E-98A1-4E1C-85C8-5ED19A59E317";
    CLASSIC = 0;
    "CUPS_SERVER" = "/private/tmp/com.apple.launchd.HiNg0azUEH/Listeners";
    "DTX_CONNECTION_SERVICES_PATH" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
    "DYLD_FALLBACK_FRAMEWORK_PATH" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks";
    "DYLD_FALLBACK_LIBRARY_PATH" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib";
    "DYLD_FRAMEWORK_PATH" = "/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator:/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator:/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks";
    "DYLD_INSERT_LIBRARIES" = "";
    "DYLD_LIBRARY_PATH" = "/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator:/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator:/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks";
    "DYLD_PRINT_STATISTICS" = 1;
    "DYLD_ROOT_PATH" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
    "DYLD_SHARED_REGION" = avoid;
    HOME = "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data/Containers/Data/Application/EF4CC38E-98A1-4E1C-85C8-5ED19A59E317";
    "IOS_SIMULATOR_SYSLOG_SOCKET" = "/private/tmp/com.apple.CoreSimulator.SimDevice.1F970762-0A26-4F84-B036-8AC7CA141BE5.launchd_sim/syslogsock";
    "IPHONE_SHARED_RESOURCES_DIRECTORY" = "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data";
    "IPHONE_SIMULATOR_CLASS" = J72;
    "IPHONE_SIMULATOR_ROOT" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/bin:/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/bin:/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/sbin:/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/sbin:/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/local/bin";
    "SIMULATOR_CAPABILITIES" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/CoreSimulator/Profiles/DeviceTypes/iPad Air.simdevicetype/Contents/Resources/capabilities.plist";
    "SIMULATOR_DEVICE_NAME" = "iPad Air";
    "SIMULATOR_HOST_HOME" = "/Users/xxxx";
    "SIMULATOR_LEGACY_ASSET_SUFFIX" = ipad;
    "SIMULATOR_LOG_ROOT" = "/Users/xxxx/Library/Logs/CoreSimulator/1F970762-0A26-4F84-B036-8AC7CA141BE5";
    "SIMULATOR_MAINSCREEN_HEIGHT" = 2048;
    "SIMULATOR_MAINSCREEN_PITCH" = "264.000000";
    "SIMULATOR_MAINSCREEN_SCALE" = "2.000000";
    "SIMULATOR_MAINSCREEN_WIDTH" = 1536;
    "SIMULATOR_MEMORY_WARNINGS" = "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data/var/run/memory_warning_simulation";
    "SIMULATOR_MODEL_IDENTIFIER" = "iPad4,2";
    "SIMULATOR_PLATFORM_RUNTIME_OVERLAY_ROOT" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/CoreSimulator/RuntimeOverlay";
    "SIMULATOR_PRODUCT_CLASS" = J72;
    "SIMULATOR_ROOT" = "/Users/xxxx/Downloads/Xcode 8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
    "SIMULATOR_RUNTIME_BUILD_VERSION" = 14C89;
    "SIMULATOR_RUNTIME_VERSION" = "10.2";
    "SIMULATOR_SHARED_RESOURCES_DIRECTORY" = "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data";
    "SIMULATOR_UDID" = "1F970762-0A26-4F84-B036-8AC7CA141BE5";
    "SIMULATOR_VERSION_INFO" = "CoreSimulator 338.16 - Device: iPad Air - Runtime: iOS 10.2 (14C89) - DeviceType: iPad Air";
    "TESTMANAGERD_SIM_SOCK" = "/private/tmp/com.apple.launchd.o7r2de4LYH/com.apple.testmanagerd.unix-domain.socket";
    TMPDIR = "/Users/xxxx/Library/Developer/CoreSimulator/Devices/1F970762-0A26-4F84-B036-8AC7CA141BE5/data/Containers/Data/Application/EF4CC38E-98A1-4E1C-85C8-5ED19A59E317/tmp";
    XCInjectBundleInto = "/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator/.app/";
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/var/folders/fs/5cvb2w9s2r7g7lpnvz5t9qh80000gn/T/com.apple.dt.XCTest/BC3982A0-2BC1-4F1D-BAC4-C0F78F6D97EB/remote-container/tmp/Tests-BC3982A0-2BC1-4F1D-BAC4-C0F78F6D97EB.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.flightbagpro.redesign[0x7543]";
    "XPC_SIMULATOR_LAUNCHD_NAME" = "com.apple.CoreSimulator.SimDevice.1F970762-0A26-4F84-B036-8AC7CA141BE5.launchd_sim";
    "__XCODE_BUILT_PRODUCTS_DIR_PATHS" = "/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator";
    "__XPC_DYLD_FRAMEWORK_PATH" = "/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator";
    "__XPC_DYLD_LIBRARY_PATH" = "/Users/xxxx/Library/Developer/Xcode/DerivedData/-dqzjujccyxlbblbzcabdtccombpu/Build/Products/Debug-iphonesimulator";

**Comment by phatmann** [comment]
Are you running in a Unit Test target? (Not a UI Test Target)
