### ISSUE TITLE
Autocompletion not working (anymore)

### ISSUE THREAD

**Issue by LordNali** [kif-framework/KIF#948]
Hello,

I'm using the latest KIF release under Xcode 8.3 / Swift 3 with the KIF TestableSwift Example and the autocompletion from Xcode is not working (see #941). KIF itself works perfectly, but the autocompletion don't - cleaning derived data didn't help either and I've got the same issue on a different mac.

The approach from #941, i.e. using Swift Protocols to 'fix' this, but in the end, this isn't really a fix (IMHO)? I'm surprised no one else has / had the problems, are there any other Swift-Useres here?

Regarding my actual question: @mjarvis approach works for now, but we're struggling to include the waitFor(accessibilityIdentifier) headers as well:
```
(UIView *)waitForViewWithAccessibilityIdentifier:(NSString *)accessibilityIdentifier;
(UIView *)waitForTappableViewWithAccessibilityIdentifier:(NSString *)accessibilityIdentifier;
```
adding (e.g.) the following two Swift-Counterparts to the Protocol don't work:
```
func waitForView(withAccessibilityIdentifier accessibilityIdentifier: String!) -> UIView!
func waitForTappableView(withAccessibilityIdentifier: String!) -> UIView!
```
Xcode throws then:
```
/Testable Swift/__ObjC.KIFUITestActor:10:15: Method 'waitForView(withAccessibilityLabel:)' has different argument names from those required by protocol 'TestActor' ('waitForView(withAccessibilityIdentifier:)')
/Testable Swift/__ObjC.KIFUITestActor:57:15: Method 'waitForTappableView(withAccessibilityLabel:)' has different argument names from those required by protocol 'TestActor' ('waitForTappableView(withAccessibilityIdentifier:)')
```
What are we're missing here? (My Objective-C is literally non-existing).

**Comment by johnslay** [comment]
I got mine working but going to my scheme -> Build -> Check Analyze for the KIF target. After that just do Product->Analyze and it comes back.

**Comment by phatmann** [comment]
Is there any way we can get closure on this ticket @LordNali?

**Comment by justinseanmartin** [comment]
Closing stale ticket
