### ISSUE TITLE
Pass test when exiting app 

### ISSUE THREAD

**Issue by zaxy78** [kif-framework/KIF#959]
I have a "logout" feature which exited the app when done.
I want to do few Log-In tests, which means I want to put the LogOut on my tearDown() method.

When it runs and logs out, that app exits and the test fails with: 
"Showing All Issues testLogin() encountered an error (Test session exited(0) without completing."

Any idea how to bypass that and make it look lie test have passed?

**Comment by phatmann** [comment]
Once the app ends KIF ends. You will need to use XCUI to do this.

**Comment by phatmann** [comment]
No easy workaround since ending the app ends the XC unit tests. Not really a KIF issue.

**Comment by zaxy78** [comment]
OK, Thanks.
