### ISSUE TITLE
Can KIF be integrated with Snapshot framework?

### ISSUE THREAD

**Issue by anshu10165** [kif-framework/KIF#962]
The function: setupSnapshot(app) where app = XCUIApplication() makes the snapshot framework to get integrated with XCUITest easily, and we can have the localized automated screenshots easily.

Planning to use fastlane, snapshot with KIF, any suggestion on how this could be achieved?

**Comment by phatmann** [comment]
KIF is not running as a UI test, but rather a unit test. So XCUIApplication is not available to it.

**Comment by justinseanmartin** [comment]
@anshu10165 - You could use https://github.com/facebook/ios-snapshot-test-case instead with KIF
