### ISSUE TITLE
Auto-correct is being kicked in more aggressively on iOS 10, should be disabled when typing for KIF

### ISSUE THREAD

**Issue by HdNate** [kif-framework/KIF#963]
NSString *text = @" 😓He😤ll👿o";
 [tester clearTextFromAndThenEnterText:text intoViewWithAccessibilityLabel:@"Greeting"];
This code is in the official KIF demo.put a breakPoint into the function "expectView: toContainText",will find that the expected value is not equal to the actual value in textfield.

**Comment by HdNate** [comment]
![Uploading FE9EA943-3C70-4074-93FD-71DF9CB5C152.png…]()

In theory,the expected value should equal to the actual value, but actually
 they are different on the picture.
In addition, it works well on iOS 8~9. 
guys, do u know how to fix the problem?

**Comment by phatmann** [comment]
What is the actual value?

**Comment by HdNate** [comment]
@phatmann   In most cases the actual value  is " 😓He😤lol👿o", but the value of a small number of cases is uncertain.

**Comment by justinseanmartin** [comment]
it is probably hitting auto-correct on the keyboard. I'd recommend disabling auto-correct for the text fields that you're typing into. Can you try setting your textField's `autocorrectionType` to `UITextAutocorrectionTypeNo` and see if it still fails?

It probably would make sense for us to do something along those lines within KIF automatically, as nobody should be relying on the system keyboard auto-correct in their tests. I'd be happy to look at a PR along those lines if you were interested.

**Comment by justinseanmartin** [comment]
Going to dupe this to #1012, which has similar issues with punctuation
