### ISSUE TITLE
"UITextField - View is not tappable" error when running test on CI

### ISSUE THREAD

**Issue by amarantedaniel** [kif-framework/KIF#977]
I have a test that clears a text field and enters text into it:
```
[tester clearTextFromAndThenEnterText:@"blabla@gmail.com" intoViewWithAccessibilityLabel:@"Email"];
```
When running the test locally everything works fine, but when running on circleci it fails with the following error:

```
testLogin, The step timed out after 10.00 seconds: View is not tappable: <UITextField: 0x7ff882c1d2b0; frame = (20 56.5; 728 30); text = 'blabla@gmail.com'; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x608000051490>; layer = <CALayer: 0x618000422ac0>>
```

**Comment by mikelupo** [comment]
Is there some modal on the screen?

**Comment by justinseanmartin** [comment]
I'd recommend trying to run the test with the simulator keyboard enabled. That generally is on by default in CI environments, but many people turn on "Simulate Hardware Keyboard" which doesn't present/dismiss the software keyboard by default. We've had this bit us before in the past.

If someone upstreamed a patch that would hard fail tests when the software keyboard wasn't enabled in the simulator, that would be a great improvement for making this failure mode much more obvious and upfront.

**Comment by justinseanmartin** [comment]
Going to close this issue and open a new issue with the idea for making tests hard fail when the software keyboard isn't enabled (or is collapsed) in the simulator.
