### ISSUE TITLE
memory leaks when use "tryFindingViewWithAccessibilityIdentifier" or "tryFindingViewWithAccessibilityLabel"

### ISSUE THREAD

**Issue by HdNate** [kif-framework/KIF#980]
<img width="960" alt="9d7c8f61-afab-4390-ba37-b3ec606e5925" src="https://cloud.githubusercontent.com/assets/24520408/26713374/f1172ada-479e-11e7-89ca-47429e6efcde.png">
memory is normal without using "tryFindingViewWithAccessibilityLabel" or "tryFindingViewWithAccessibilityIdentifier".
memory leaks, when using "[tester tryFindingViewWithAccessibilityLabel:@"Basic Calculator" error:&error]" to find a control.

**Comment by justinseanmartin** [comment]
If you pause and take a look at the "View Memory Graph Hierarchy" in Xcode 8+, which objects are being allocated and not deallocated? You can also turn on malloc stack logging in the Scheme Editor's Diagnostics tab. 

Does it continue to go up through the lifetime of the tests, as they progress from step to step? In some instances, they won't be released until encountering an autorelease pool. You could try wrapping the element searching code with an autorelease pool, as is done in `[UITestActor waitForViewWithAccessibilityLabel:]`. That seems like it would be appropriate to me, though the memory should still get freed upon starting a second test case and the autoreleasepool managed by XCTest in `invokeTest` kicks in.

Do you see the same memory behavior if you use the newer `UIViewTestActor` syntax, for example:

```
[[viewTester usingLabel:@"Basic Calculator"] tryFindingView];
```

I would presume so, but thought I'd check.

**Comment by justinseanmartin** [comment]
Closing stale issue.
