### ISSUE TITLE
crash on xcode8 iOS10

### ISSUE THREAD

**Issue by tcguo** [kif-framework/KIF#982]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AccessibilitySettingsController AXInspectorEnabled:]: unrecognized selector sent to instance 0x7f9ed380c400'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001076aab0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010710f141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010771a134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000107631840 ___forwarding___ + 1024
	4   CoreFoundation                      0x00000001076313b8 _CF_forwarding_prep_0 + 120
	5   SGAutoTestTests                     0x0000000115d6b123 -[KIFAccessibilityEnabler enableAccessibility] + 723
	6   SGAutoTestTests                     0x0000000115d6e9de __20+[KIFTestCase setUp]_block_invoke + 62
	7   libdispatch.dylib                   0x0000000109ea3792 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000109e8ea8d dispatch_once_f + 69
	9   SGAutoTestTests                     0x0000000115d6e964 +[KIFTestCase setUp] + 84
	10  XCTest                              0x0000000106ac0f86 __27-[XCTestSuite performTest:]_block_invoke + 58
	11  XCTest                              0x0000000106ac0c68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	12  XCTest                              0x0000000106ac0e4e -[XCTestSuite performTest:] + 214
	13  XCTest                              0x0000000106ac1078 __27-[XCTestSuite performTest:]_block_invoke + 300
	14  XCTest                              0x0000000106ac0c68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	15  XCTest                              0x0000000106ac0e4e -[XCTestSuite performTest:] + 214
	16  XCTest                              0x0000000106ac1078 __27-[XCTestSuite performTest:]_block_invoke + 300
	17  XCTest                              0x0000000106ac0c68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	18  XCTest                              0x0000000106ac0e4e -[XCTestSuite performTest:] + 214
	19  XCTest                              0x0000000106b0da86 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	20  XCTest                              0x0000000106acff27 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 574
	21  XCTest                              0x0000000106b0d925 -[XCTTestRunSession runTestsAndReturnError:] + 281
	22  XCTest                              0x0000000106aaba50 -[XCTestDriver runTestsAndReturnError:] + 254
	23  XCTest                              0x0000000106b0586e _XCTestMain + 559
	24  CoreFoundation                      0x0000000107650b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	25  CoreFoundation                      0x0000000107635e54 __CFRunLoopDoBlocks + 356
	26  CoreFoundation                      0x00000001076355ee __CFRunLoopRun + 894
	27  CoreFoundation                      0x0000000107635016 CFRunLoopRunSpecific + 406
	28  GraphicsServices                    0x000000010c210a24 GSEventRunModal + 62
	29  UIKit                               0x0000000107ace0d4 UIApplicationMain + 159
	30  SGAutoTest                          0x0000000105fcbf6f main + 111
	31  libdyld.dylib                       0x0000000109eec65d start + 1
	32  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by justinseanmartin** [comment]
What version of KIF are you using? KIF works fine for me with Xcode 8.3.2 and an iOS 10.3 simulator.

This code seems like it should be pretty safe to not generate an unrecognized selector error:
```
        NSString *settingsBundleLocation = @"/System/Library/PreferenceBundles/AccessibilitySettings.bundle/AccessibilitySettings";
        void *settingsBundle = loadDylibForSimulator(settingsBundleLocation);
        if (settingsBundle) {
            Class axClass = NSClassFromString(@"AccessibilitySettingsController");
            if (axClass) {
                id axInstance = [[axClass alloc] init];
                if ([axInstance respondsToSelector:@selector(AXInspectorEnabled:)]) {
                    NSNumber *initialValue = [axInstance AXInspectorEnabled:nil];
```
From here: https://github.com/kif-framework/KIF/blob/master/Classes/KIFAccessibilityEnabler.m#L52-L59

I'd recommend setting a breakpoint here and debugging from that point. You could see which dylib is being loaded in the call `loadDylibForSimulator` (make sure it is the one for iOS 10). You could use class-dump to ensure that the symbols do exist that are expected.
