### ISSUE TITLE
No such module 'KIF'

### ISSUE THREAD

**Issue by LeoTuring** [kif-framework/KIF#983]
CocoaPods set up KIF 
but TestTarget import KIF 
error is `No such module 'KIF'` 
how to solve it?

Xcode 8.3.2
Swift 3.1

**Comment by danlniel** [comment]
> IMPORTANT! Even though KIF is used to test your UI, you need to add it to your Unit Test target, not your UI Test target. The magic of KIF is that it allows you to drive your UI from your unit tests and reap all the advantages of testing in-process.
Have you try to add KIF on you test not UI Test?

**Comment by justinseanmartin** [comment]
Seems like a issue with the project's linker flags. Please reactivate if you think there is a problem with the framework or the instructions on how to get started. As always, pull requests welcome if you think there is some missing critical piece of information. Thanks!
