### ISSUE TITLE
Run test fail in Swift Program?

### ISSUE THREAD

**Issue by longjianjiang** [kif-framework/KIF#984]
Today, i use KIF as a beginner, then i read some article about KIF. 
So i test it on my own, i write a class extends `KIFTestCase`, then i add the test function like this:
```
  func testContinueWithoutSaving_ShowNextScreen_WithCorrectText() {
        
        tester().tapView(withAccessibilityLabel: "Continue, without saving")
        tester().waitForView(withAccessibilityLabel: "Welcome Player 1")
        tester().tapView(withAccessibilityLabel: "Start Over")
    }
```

PS: i add the bridging header that import `#import <KIF/KIF.h>`, i also add extension for `XCTestCase` from Github readme.

But when i run the test, it will failed in my own test class, i don't know why? so please tell me some reason about this situation.

**Comment by justinseanmartin** [comment]
There is insufficient information to understand how or why it is failing. Can you explain more about the behavior when you're seeing when it fails? For now, I'm going to close the issue, but please feel free to reactivate with more information.

Please note the disclaimer at the top of the README:
> IMPORTANT! Even though KIF is used to test your UI, you need to add it to your Unit Test target, not your UI Test target. The magic of KIF is that it allows you to drive your UI from your unit tests and reap all the advantages of testing in-process.

Thanks!
