### ISSUE TITLE
Missing documentation for Carthage setup

### ISSUE THREAD

**Issue by Sebkasanzew** [kif-framework/KIF#986]
I'm trying to setup the KIF framework in my project via Carthage.
According to #624 this is implemented and possible, but I cant find any documentation in the repository or other online sources.

Can someone add a step by step guide to the Readme.md?

**Comment by justinseanmartin** [comment]
I've never used Carthage personally, so don't know offhand how to do it. If you figure it out and have step-by-step instructions that you think would help others, please consider opening a pull request to the Readme!

**Comment by justinseanmartin** [comment]
Closing stale issue. Pull requests welcome.
