### ISSUE TITLE
How to enable accessibility Inspector for iOS 10.

### ISSUE THREAD

**Issue by anshu10165** [kif-framework/KIF#990]
I am using `KIFEnableAccessibility()` in my  `setUp()` function, and looks like its not working.
Error I am getting is "UIAutomation wont work because Accessibility Api is not enabled"
My KIF version is 3.5.1 and Xcode version : 8.3. Any thoughts on this? Running my test on iOS Sim 10.3

**Comment by justinseanmartin** [comment]
Is the test target that you've created a UI Testing target? It should be a "iOS Unit Testing Bundle":

![image](https://user-images.githubusercontent.com/5855270/28947312-00c9c88e-7864-11e7-8186-25957615b85b.png)

The thing that leads me to believe that this is wrong is the specific mention of UIAutomation.

**Comment by anshu10165** [comment]
Thanks @justinseanmartin. The test target we have is under **iOS UI Testing** . Can I edit the same and change to **iOS Unit testing target**, or should I delete the existing and create a fresh with **iOS unit testing** target ? Appreciate you help here, Thanks!

**Comment by anshu10165** [comment]
Hey @justinseanmartin : My Bad on earlier comment, my test target is under **iOS Unit testing target** only, Could you please help as to what might be wrong here ? Thanks a lot.

**Comment by justinseanmartin** [comment]
Possibly take a look at the comments in #944 to see if that helps? Others had reported seeing the same error.
